/** Private console. SQL authorizes every action; external outputs use separate serializers. */
import {CloudAPI} from '../web/modules/api.mjs';
import {escape as E,clock} from './core.mjs';
import {externalHTML,externalCSV,pngBlob,internalHTML,internalCSV} from '../web/modules/report-render.mjs';
const $=id=>document.getElementById(id),api=new CloudAPI(window.PULSO_V3_CONFIG);
let state=null,city='cde',busy=false,pendingCut=null,guard;
function message(text,ok=false){$('message').textContent=text;$('message').className=ok?'success':'';}
function clearPrivate(){state=null;pendingCut=null;$('workspace').hidden=true;$('access').hidden=false;$('mapping').replaceChildren();$('cuts').replaceChildren();}
function error(e){const code=String(e?.message||'');const errors={
 V3_ADMIN_ONLY:'Solo administración puede configurar nombres, códigos y permisos.',V3_ACCOUNT_DISABLED:'Cuenta desactivada. Acceso privado cerrado.',V3_SESSION_REQUIRED:'La sesión terminó. Ingrese de nuevo.',
 V3_RELOAD_REQUIRED:'La configuración cambió en otro equipo. Actualice el estado antes de continuar.',V3_ALIAS_CONTAINS_REAL_NAME:'El código contiene parte del nombre real. Use un código neutro.',V3_ALIAS_INVALID_OR_DUPLICATE:'Código inválido o repetido. Use entre 2 y 40 caracteres sin nombres ni Lista.',V3_ALIAS_CONFIRM_REQUIRED:'Confirme primero todos los códigos de esta ciudad.',V3_LIVE_RELEASE_BLOCKED:'Canal bloqueado: revise la política, el horario, la versión y el vencimiento (máximo 24 horas).',V3_REPORT_RELEASE_BLOCKED:'No se puede autorizar el corte antes de la política y hora permitidas.',V3_REPORT_STALE:'El corte no corresponde a la versión vigente. Cree un corte nuevo.',V3_REPORT_CUTOFF_INVALID:'El corte debe estar entre el inicio de la jornada configurada y ahora.',V3_CONSOLE_TIME:'Incluya una fecha válida con zona horaria, por ejemplo 2026-10-04T18:00:00-03:00.',V3_EXPORT_INCOMPLETE:'El archivo interno está incompleto. No se descargó; vuelva a consultar.',V3_CONNECTION_NOT_CONFIGURED:'La conexión privada todavía no está configurada.'};
 if(/SESSION_REQUIRED|ACCOUNT_DISABLED|ADMIN_ONLY/.test(code)||e?.status===401||e?.status===403)clearPrivate();
 message(errors[code]||(/PGRST202|MIGRATION_REQUIRED/.test(code)?'Backend pendiente: instale los complementos 009, 010 y 011. No se cambia la base desde esta pantalla.':/Invalid login credentials/i.test(code)?'Código o contraseña incorrectos.':'No se confirmó la operación. Actualice el estado y revise la lista antes de repetir una creación.'));
}
function iso(value,required=false){if(!value?.trim()){if(required)throw Error('V3_CONSOLE_TIME');return null;}const s=value.trim();if(!/(Z|[+-]\d{2}:\d{2})$/.test(s)||!Number.isFinite(Date.parse(s)))throw Error('V3_CONSOLE_TIME');return new Date(s).toISOString();}
const current=()=>state?.cities.find(c=>c.id===city);
async function listCuts(){const cuts=await api.rpc('v3_report_list');$('cuts').innerHTML=cuts.filter(c=>c.district_id===city).map(c=>`<article class="cut-row" data-cut="${E(c.id)}"><h3>Corte ${c.cut_number} · ${clock(c.cutoff_at)} <span class="status">${E(c.status)}</span></h3><div class="cut-actions">${[['internal-html','Interno · HTML/PDF'],['internal-csv','Interno · CSV completo'],['external-html','Externo · HTML/PDF'],['external-csv','Externo · CSV'],['external-png','Externo · PNG'],['release','Autorizar corte'],['revoke','Retirar corte']].map(([id,label])=>`<button type="button" data-download="${id}">${label}</button>`).join('')}</div></article>`).join('')||'<p>No hay cortes guardados para esta ciudad.</p>';}
function mapping(){const c=current(),q=c?.config;$('mapping').innerHTML=q?`<h2>Nombre real ↔ código externo · ${E(c.name)}</h2><p>Formulario v${q.version} · Códigos v${q.alias_revision} · ${q.confirmed?'Confirmados':'Pendientes de confirmar'}</p><form id="alias">${q.items.map((x,i)=>`<div class="mapping-row"><strong>${E(x.real_name)}</strong><small>${E(x.list)}</small><label>Código externo<input name="code-${i}" value="${E(x.code)}" required minlength="2" maxlength="40"></label></div>`).join('')}<label class="check"><input name="confirmed" type="checkbox" required> He comprobado todos los nombres y códigos. Modificar el cruce invalida el canal y las publicaciones anteriores.</label><button>Confirmar códigos de la ciudad</button></form>`:'<h2>Catálogo pendiente</h2><p>Publique primero el formulario de esta ciudad en el App V3. No se inventan candidaturas.</p>';
 const release=c?.release;$('release-state').textContent=release?`${release.enabled?'Permiso registrado':'Desactivado'} · vence ${release.expires_at} · sujeto a la política y versión vigentes.`:'Sin autorización continua registrada.';
 const f=$('channel');f.elements.enabled.checked=false;f.elements.expires.value='';f.elements.reference.value='';f.elements.confirmed.checked=false;
}
async function load(){const next=await api.rpc('v3_live_admin_state');if(next.schema!=='pulso-live-admin-1')throw Error('V3_CONNECTION_NOT_CONFIGURED');state=next;$('workspace').hidden=false;$('access').hidden=true;$('city').innerHTML=state.cities.map(c=>`<option value="${E(c.id)}">${E(c.name)}</option>`).join('');$('city').value=city;
 $('operation').textContent=`Modo ${state.operation_mode.toUpperCase()} · fase ${state.operation.phase} · lectura ${clock(state.server_time)}. Esta consola no abre ni cierra la recepción.`;
 const p=state.policy;$('policy').elements.enabled.checked=p.enabled;$('policy').elements.not_before.value=p.release_not_before||'';$('policy').elements.reference.value=p.authorization_reference||'';
 $('viewer-state').textContent=state.operation.viewer_enabled?'Viewer general habilitado. Cada ciudad todavía necesita su permiso.':'Viewer general bloqueado. El control interno no se bloquea.';$('viewer').elements.enabled.checked=state.operation.viewer_enabled;mapping();await listCuts();}
async function perform(form,task){if(busy)return;busy=true;form?.setAttribute('aria-busy','true');document.querySelectorAll('button').forEach(b=>b.disabled=true);try{await task();}catch(e){error(e);}finally{busy=false;form?.removeAttribute('aria-busy');document.querySelectorAll('button').forEach(b=>b.disabled=false);}}
function download(content,name,type){const url=URL.createObjectURL(content instanceof Blob?content:new Blob([content],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
async function internalAll(id){let offset=0,first=null,records=[],seen=new Set();while(true){const r=await api.rpc('v3_report_read',{p_id:id,p_audience:'internal',p_offset:offset,p_limit:500});if(!first)first=r;if(r.report_id!==id||r.total_records!==first.total_records||r.snapshot_at!==first.snapshot_at||r.status!==first.status)throw Error('V3_EXPORT_INCOMPLETE');for(const x of r.records){if(seen.has(x.id))throw Error('V3_EXPORT_INCOMPLETE');seen.add(x.id);records.push(x);}if(r.next_offset===null)break;if(!Number.isInteger(r.next_offset)||r.next_offset<=offset||r.next_offset>100000)throw Error('V3_EXPORT_INCOMPLETE');offset=r.next_offset;}if(records.length!==first.total_records)throw Error('V3_EXPORT_INCOMPLETE');return{...first,records,next_offset:null};}
$('login').addEventListener('submit',e=>{e.preventDefault();const f=e.target;perform(f,async()=>{await api.login(f.elements.code.value,f.elements.password.value);f.elements.password.value='';await load();message('Sesión de administración confirmada.',true);});});
$('reload').onclick=()=>perform(null,async()=>{await load();message('Estado actualizado desde el servidor.',true);});
$('logout').onclick=()=>perform(null,async()=>{await api.logout();clearPrivate();message('Sesión cerrada.',true);});
$('city').onchange=()=>perform(null,async()=>{city=$('city').value;pendingCut=null;mapping();await listCuts();});
$('workspace').addEventListener('submit',e=>{e.preventDefault();const f=e.target;perform(f,async()=>{if(!state)throw Error('V3_SESSION_REQUIRED');const q=current()?.config;
 if(f.id==='alias'){await api.rpc('v3_report_alias_save',{p_questionnaire:q.questionnaire_id,p_items:q.items.map((x,i)=>({candidate_id:x.candidate_id,code:f.elements['code-'+i].value.trim()})),p_expected:q.alias_revision,p_confirmed:f.elements.confirmed.checked});}
 else if(f.id==='policy'){await api.rpc('v3_report_policy_save',{p_enabled:f.elements.enabled.checked,p_not_before:iso(f.elements.not_before.value,f.elements.enabled.checked),p_reference:f.elements.reference.value.trim(),p_expected:state.policy.revision});}
 else if(f.id==='viewer'){await api.command('viewer.access',{enabled:f.elements.enabled.checked,reason:f.elements.reason.value.trim()},state.operation.revision);}
 else if(f.id==='channel'){await api.rpc('v3_live_authorize',{p_district:city,p_enabled:f.elements.enabled.checked,p_expires:iso(f.elements.expires.value,f.elements.enabled.checked),p_reference:f.elements.reference.value.trim(),p_confirmed:f.elements.confirmed.checked});}
 else if(f.id==='cut'){if(!q)throw Error('V3_ALIAS_CONFIRM_REQUIRED');const cutoff=iso(f.elements.cutoff.value),key=q.questionnaire_id+':'+cutoff;if(!pendingCut||pendingCut.key!==key)pendingCut={key,id:crypto.randomUUID()};await api.rpc('v3_report_create',{p_questionnaire:q.questionnaire_id,p_cutoff:cutoff,p_request_id:pendingCut.id});pendingCut=null;}
 await load();message('Operación confirmada por el servidor. La recepción de encuestas no se modificó.',true);
 });});
$('cuts').addEventListener('click',e=>{const button=e.target.closest('[data-download]');if(!button)return;const id=button.closest('[data-cut]').dataset.cut,action=button.dataset.download;perform(null,async()=>{
 if(action==='release'||action==='revoke'){const ref=prompt(action==='release'?'Referencia real de autorización de este corte (mínimo 10 caracteres):':'Motivo de retiro (mínimo 10 caracteres):');if(!ref)return;if(action==='release')await api.rpc('v3_report_release',{p_id:id,p_confirmed:true,p_reference:ref});else await api.rpc('v3_report_revoke',{p_id:id,p_reason:ref});await listCuts();message('Estado del corte actualizado.',true);return;}
 const internal=action.startsWith('internal'),r=internal?await internalAll(id):await api.rpc('v3_report_read',{p_id:id,p_audience:'external'}),name=`Pulso_${internal?'INTERNO_NO_DIFUNDIR':'EXTERNO_'+r.status}_${r.city_code}_Corte_${r.cut_number}`;
 if(action==='internal-csv')download(internalCSV(r),name+'.csv','text/csv;charset=utf-8');
 if(action==='internal-html')download(internalHTML(r),name+'.html','text/html;charset=utf-8');
 if(action==='external-csv')download(externalCSV(r),name+'.csv','text/csv;charset=utf-8');
 if(action==='external-html')download(externalHTML(r),name+'.html','text/html;charset=utf-8');
 if(action==='external-png')download(await pngBlob(r),name+'.png','image/png');
 message('Archivo independiente descargado. HTML: abrir y usar Imprimir → Guardar como PDF. El monitor en vivo continúa aparte.',true);
 });});
addEventListener('pagehide',()=>{clearInterval(guard);clearPrivate();});
addEventListener('pageshow',e=>{if(e.persisted)location.reload();});
(async()=>{try{const sb=await api.client();sb.auth.onAuthStateChange(event=>{if(event==='SIGNED_OUT')clearPrivate();});if(await api.session())await load();guard=setInterval(async()=>{if(!state||busy||document.hidden)return;try{await api.rpc('v3_live_admin_state');}catch(e){error(e);}},15000);}catch(e){error(e);}})();
