import {readinessCard} from './company-readiness.mjs';
/** Self-service company UI. All authorization is repeated by database functions. */
import {esc as E,ROLES,CITIES,city,time} from './core.mjs';
export const roleLabel=a=>ROLES[a?.role]||'Sin rol';
export function canManageAccount(me,target){return !!me&&!!target&&me.role==='admin'&&target.user_id!==me.user_id&&!target.is_super_admin&&(me.is_super_admin===true||target.role!=='admin');}
const button=(t,act,id='',cls='')=>`<button type="button" class="${cls}" data-action="${E(act)}" data-id="${E(id)}">${t}</button>`;
const input=(t,n,v,max=160,type='text',extra='')=>`<label class="field">${t}<input name="${n}" type="${type}" value="${E(v||'')}" maxlength="${max}" ${extra}></label>`;
const available=b=>b?.company_schema_version===12;
const warning=()=>'<section class="card callout warn"><h2>Actualización pendiente</h2><p>La gestión de cuentas no está disponible. Contacte al soporte de la plataforma.</p></section>';
function companyPageBase(S){
 const b=S.boot;if(b?.actor?.role!=='admin')return '<p>Acceso no autorizado.</p>';
 if(!available(b))return warning();
 const c=b.company||{},steps=[['catalog','1. Formularios y candidaturas','Preparar, editar y publicar la versión correcta de cada ciudad.'],['points','2. Locales y puntos','Crear la dirección real y aprobar cada punto por separado.'],['access','3. Cuentas y alcances','Crear accesos individuales con los permisos correspondientes.'],['people','4. Personal en campo','Incorporar personas cuando lleguen; corregir datos de la misma persona.'],['tasks','5. Asignaciones','Una persona, un punto y una versión por tarea.'],['settings','6. Operación','Confirmar la fecha y abrir únicamente los puntos preparados.']];
 return `<div class="heading"><div><div class="eyebrow">Pulso 3.1 · Gestión de empresa</div><h1>Empresa</h1><p class="muted">Datos de contacto y preparación del operativo.</p></div></div><section class="card"><h2>Datos de la empresa</h2><form id="company-form" data-revision="${Number(c.revision)||1}"><div class="formgrid">${input('Nombre de la empresa','name',c.name,160,'text','required')}${input('Contacto responsable','contact_name',c.contact_name,100)}${input('Correo de soporte','support_email',c.support_email,254,'email')}${input('Teléfono de soporte','support_phone',c.support_phone,60,'tel')}</div><label class="field">Notas internas de administración<textarea name="notes" maxlength="2000">${E(c.notes||'')}</textarea></label><p class="inline-note">No incluya datos de votantes, contraseñas ni claves. Las notas internas no se entregan a encuestadores ni a viewers.</p><button type="submit" class="primary">Guardar datos de empresa</button></form></section><section class="card"><h2>Preparación por pasos</h2><div class="grid">${steps.map(([id,title,desc])=>`<article><h3>${title}</h3><p>${desc}</p>${button('Abrir','nav',id,'small')}</article>`).join('')}</div></section><section class="card"><h2>Estado por ciudad</h2><div class="table-scroll"><table><thead><tr><th>Ciudad</th><th>Formulario publicado</th><th>Puntos aprobados / abiertos</th><th>Personas incorporadas</th></tr></thead><tbody>${CITIES.map(d=>{const q=b.questionnaires.find(q=>q.district_id===d.id&&q.state==='published');const ps=b.points.filter(p=>b.stations.some(s=>s.id===p.station_id&&s.district_id===d.id));return `<tr><td>${E(d.name)}</td><td>${q?'Versión '+q.version:'Pendiente'}</td><td>${ps.filter(p=>['approved','open','paused'].includes(p.state)).length} / ${ps.filter(p=>p.state==='open').length}</td><td>${b.people.filter(p=>p.home_district===d.id).length}</td></tr>`;}).join('')}</tbody></table></div><p>No iniciado significa sin cobertura, no cero votos. Una ciudad pendiente no debe mezclarse con otra.</p></section><section class="card"><h2>Informes y ayuda</h2><div class="actions"><a class="button primary" href="../live/?view=internal" target="_blank" rel="noopener">Pantalla en vivo · interna</a><a class="button" href="../live/control.html" target="_blank" rel="noopener">Códigos e informes externos</a><a class="button" href="manual-es.html" target="_blank" rel="noopener">Manual completo en español</a></div></section>`;
}
export function accessPage(S,V){const b=S.boot,me=b.actor,ready=available(b);
 return V.heading('Accesos y alcances','Cuentas individuales y permisos de trabajo.',ready?V.button('Crear acceso','access-new','','primary'):'')+(ready?'':warning())+`<section class="card"><h2>Cuentas</h2><p class="inline-note">Los códigos de ingreso permanecen fijos. Corregir un nombre no reemplaza a la persona. Para crear un administrador use una cuenta nueva, no una conversión de encuestador.</p>${b.actors.filter(a=>a.role!=='interviewer'&&!a.is_super_admin).map(a=>{const manage=ready&&canManageAccount(me,a);return `<div class="listrow"><div><strong>${E(a.code)} · ${E(a.display_name)}</strong><small>${E(roleLabel(a))} · ${a.active?'Activa':'Desactivada'}</small></div><div class="actions">${manage?V.button('Corregir nombre','actor-rename',a.user_id,'small'):''}${manage&&['viewer','coordinator'].includes(a.role)?V.button('Asignar alcance','grant-new',a.user_id,'small'):''}${manage?V.button('Cambiar rol','actor-role',a.user_id,'small')+V.button('Restablecer clave','reset-worker',a.user_id,'small')+(a.active?V.button('Desactivar','actor-disable',a.user_id,'small danger'):V.button('Reactivar','actor-enable',a.user_id,'small')):''}</div></div>`;}).join('')}</section><section class="card"><h2>Permisos emitidos</h2>${b.grants.map(g=>`<div class="listrow"><div><strong>${E(b.actors.find(a=>a.user_id===g.user_id)?.code||'Cuenta')}</strong><small>${E(city(g.district_id))} · ${g.point_id?E(V.namePoint(b,g.point_id)):'Todos los puntos de esa ciudad'}</small><small>${E(g.capabilities.map(x=>({operations:'Ver operación',recruit:'Incorporar personal',assign:'Asignar tareas',manage_points:'Gestionar puntos',control_points:'Controlar puntos',view_results:'Ver resultados'}[x]||x)).join(', '))} · Hasta ${time(g.valid_until)} ${g.revoked_at?'· REVOCADO':''}</small></div>${!g.revoked_at?V.button('Revocar alcance','grant-revoke',g.id,'small danger'):''}</div>`).join('')||'<p>Sin permisos de alcance.</p>'}</section><section class="card"><h2>Difusión por códigos</h2><p>Las pantallas externas y los informes usan códigos. La consulta interna no autoriza divulgar resultados.</p><a class="button" href="../live/control.html" target="_blank" rel="noopener">Administrar códigos / informes</a></section>`;
}

export function companyPage(S){return companyPageBase(S);}
