import {unzipSync,strFromU8} from 'fflate';
const LIMIT=5*1024*1024, MAX_ROWS=1000;
export const HEADERS={stations:['district_id','code','name','address','official_code'],points:['station_code','code','label','planned'],people:['district_id','display_name'],assignments:['person_code','point_code','reason'],questionnaires:['district_id','contest','methodology','sample_interval','reference','candidate_id','candidate_name','list_label']};
function checkValue(s){if(typeof s==='string'&&(/^[\s]*[=+@]/.test(s)||/[\u0000-\u0008\u000b\u000c\u000e-\u001f]/.test(s)))throw new Error('V3_IMPORT_UNSAFE_CELL');if(String(s).length>5000)throw new Error('V3_IMPORT_CELL_TOO_LARGE');return s;}
export function parseCSV(text){if(text.length>LIMIT)throw new Error('V3_IMPORT_LIMIT');text=text.replace(/^\ufeff/,'');let rows=[],r=[],s='',quoted=false,after=false;for(let i=0;i<text.length;i++){const c=text[i];if(quoted){if(c==='"'){if(text[i+1]==='"'){s+='"';i++;}else{quoted=false;after=true;}}else s+=c;}else if(c==='"'&&s===''&&!after)quoted=true;else if(c===','){r.push(checkValue(s));s='';after=false;}else if(c==='\r'||c==='\n'){if(c==='\r'&&text[i+1]==='\n')i++;r.push(checkValue(s));if(r.some(v=>v!==''))rows.push(r);r=[];s='';after=false;}else{if(after)throw new Error('V3_IMPORT_INVALID_CSV');s+=c;}}if(quoted)throw new Error('V3_IMPORT_INVALID_CSV');if(s!==''||r.length){r.push(checkValue(s));rows.push(r);}if(rows.length>MAX_ROWS+1)throw new Error('V3_IMPORT_LIMIT');return rows;}
function xml(bytes){const text=strFromU8(bytes);if(/<!DOCTYPE|<!ENTITY/i.test(text))throw new Error('V3_IMPORT_XML_UNSAFE');const doc=new DOMParser().parseFromString(text,'application/xml');if(doc.getElementsByTagName('parsererror').length)throw new Error('V3_IMPORT_INVALID_XML');return doc;}
const elems=(node,tag)=>[...node.getElementsByTagNameNS('*',tag)];
function columnIndex(ref){const letters=ref.match(/^[A-Z]+/)?.[0];if(!letters)throw new Error('V3_IMPORT_INVALID_CELL');let n=0;for(const c of letters)n=n*26+c.charCodeAt(0)-64;return n-1;}
export function readXLSX(buffer,kind){if(buffer.byteLength>LIMIT)throw new Error('V3_IMPORT_LIMIT');let total=0,count=0;const entries=unzipSync(new Uint8Array(buffer),{filter:entry=>{count++;total+=entry.originalSize;if(count>150||entry.originalSize>10*1024*1024||total>20*1024*1024||/\.\.\/|^\//.test(entry.name))throw new Error('V3_IMPORT_ZIP_UNSAFE');if(/vbaProject|externalLinks|\.bin$/i.test(entry.name))throw new Error('V3_IMPORT_MACROS_FORBIDDEN');return true;}});
 for(const [name,b] of Object.entries(entries)){if(name.endsWith('.rels')&&/TargetMode=["']External/.test(strFromU8(b)))throw new Error('V3_IMPORT_EXTERNAL_LINK');if(/xl\/worksheets\/.*\.xml$/.test(name)){const doc=xml(b);if(elems(doc,'f').length)throw new Error('V3_IMPORT_FORMULAS_FORBIDDEN');}}
 if(!entries['xl/workbook.xml']||!entries['xl/_rels/workbook.xml.rels'])throw new Error('V3_IMPORT_INVALID_XLSX');
 const workbook=xml(entries['xl/workbook.xml']),sheet=elems(workbook,'sheet').find(x=>x.getAttribute('name')===kind);if(!sheet)throw new Error('V3_IMPORT_SHEET_REQUIRED');const rid=sheet.getAttribute('r:id');const rel=elems(xml(entries['xl/_rels/workbook.xml.rels']),'Relationship').find(x=>x.getAttribute('Id')===rid);let target=rel?.getAttribute('Target');if(!target)throw new Error('V3_IMPORT_INVALID_XLSX');target=target.startsWith('/')?target.slice(1):'xl/'+target;if(!target.startsWith('xl/worksheets/')||!entries[target])throw new Error('V3_IMPORT_INVALID_XLSX');
 const shared=entries['xl/sharedStrings.xml']?elems(xml(entries['xl/sharedStrings.xml']),'si').map(si=>elems(si,'t').map(x=>x.textContent).join('')):[];
 const rows=elems(xml(entries[target]),'row').map(row=>{const values=[];for(const cell of elems(row,'c')){let value=elems(cell,'v')[0]?.textContent||'';if(cell.getAttribute('t')==='s')value=shared[Number(value)]??'';if(cell.getAttribute('t')==='inlineStr')value=elems(cell,'t').map(x=>x.textContent).join('');const idx=columnIndex(cell.getAttribute('r'));if(idx>30)throw new Error('V3_IMPORT_TOO_MANY_COLUMNS');values[idx]=checkValue(value);}return values;}).filter(r=>r.some(v=>v!==''));if(rows.length>MAX_ROWS+1)throw new Error('V3_IMPORT_LIMIT');return rows;
}
export function objectRows(rows,kind){const expected=HEADERS[kind];if(!expected||rows.length<2)throw new Error('V3_IMPORT_HEADER');const headers=rows[0].map(x=>String(x||'').trim());if(headers.length!==expected.length||expected.some((x,i)=>x!==headers[i]))throw new Error('V3_IMPORT_HEADER');const result=rows.slice(1).map(row=>{if(row.length>headers.length)throw new Error('V3_IMPORT_HEADER');return Object.fromEntries(headers.map((h,i)=>[h,checkValue(String(row[i]??'').trim())]));});if(kind==='points')result.forEach(r=>{if(!['','true','false','Sí','No','1','0'].includes(r.planned))throw new Error('V3_IMPORT_BOOL');r.planned=!['false','No','0'].includes(r.planned);});
 if(kind==='questionnaires'){const groups=new Map();for(const r of result){let g=groups.get(r.district_id);if(!g){g={district_id:r.district_id,contest:r.contest,methodology:r.methodology,sample_interval:Number(r.sample_interval),reference:r.reference,items:[]};groups.set(r.district_id,g);}if(g.contest!==r.contest||g.methodology!==r.methodology||g.sample_interval!==Number(r.sample_interval)||g.reference!==r.reference)throw new Error('V3_IMPORT_Q_METADATA');g.items.push({id:r.candidate_id||crypto.randomUUID(),name:r.candidate_name,list:r.list_label});}return [...groups.values()];}
 return result;
}
export async function parseFile(file,kind){if(file.size>LIMIT)throw new Error('V3_IMPORT_LIMIT');if(/\.csv$/i.test(file.name))return objectRows(parseCSV(await file.text()),kind);if(/\.xlsx$/i.test(file.name))return objectRows(readXLSX(await file.arrayBuffer(),kind),kind);throw new Error('V3_IMPORT_EXTENSION');}
