import fs from 'node:fs/promises';import path from 'node:path';import {build} from 'esbuild';import {fileURLToPath} from 'node:url';import crypto from 'node:crypto';
const root=path.dirname(path.dirname(fileURLToPath(import.meta.url))),repo=path.dirname(root),demo=process.argv.includes('--demo'),out=path.join(root,demo?'preview':'dist');await fs.rm(out,{recursive:true,force:true});await fs.mkdir(path.join(out,'vendor'),{recursive:true});
await build({entryPoints:[path.join(root,'web/app.mjs')],bundle:true,format:'esm',target:['es2022'],outfile:path.join(out,'app.js'),external:['./simulation.mjs'],minify:false,sourcemap:false});
for(const f of ['index.html','styles.css','manifest.webmanifest','icon.svg'])await fs.copyFile(path.join(root,'web',f),path.join(out,f));
const url=process.env.SUPABASE_URL||'',key=process.env.SUPABASE_PUBLISHABLE_KEY||'';
if(key.startsWith('sb_secret_')||(key.split('.').length===3&&JSON.parse(Buffer.from(key.split('.')[1],'base64url')).role!=='anon'))throw new Error('Public configuration rejected');
await fs.writeFile(path.join(out,'config.js'),'window.PULSO_V3_CONFIG='+JSON.stringify({supabaseUrl:demo?'':url,publishableKey:demo?'':key,environment:demo?'isolated-simulation':process.env.PULSO_ENVIRONMENT||'staging-unconfigured',build:'3.0.0-rc.1',simulation:demo})+';');
const vendor=process.env.SUPABASE_VENDOR_FILE||path.join(repo,'web/supabase-vendor.js');await fs.copyFile(vendor,path.join(out,'vendor/supabase.js'));
if(demo){await fs.writeFile(path.join(out,'qa-harness.html'),'<!doctype html><html><meta charset="utf-8"><title>Isolated QA harness</title><body>Isolated QA only.</body></html>');await build({entryPoints:[path.join(root,'tests/browser-harness.mjs')],bundle:true,format:'esm',platform:'browser',target:'es2022',outfile:path.join(out,'qa-harness.js')});await build({entryPoints:[path.join(root,'web/simulation.mjs')],bundle:true,format:'esm',target:'es2022',outfile:path.join(out,'simulation.mjs'),platform:'browser',minify:true});
 const pg=path.dirname(fileURLToPath(import.meta.resolve('@electric-sql/pglite')));for(const f of ['pglite.wasm','initdb.wasm','pglite.data'])await fs.copyFile(path.join(pg,f),path.join(out,f));
 let sql=`CREATE ROLE anon NOLOGIN; CREATE ROLE authenticated NOLOGIN;CREATE ROLE service_role NOLOGIN BYPASSRLS;CREATE SCHEMA auth;CREATE TABLE auth.users(id uuid PRIMARY KEY,email text,email_confirmed_at timestamptz,raw_app_meta_data jsonb NOT NULL DEFAULT '{}');CREATE TABLE auth.sessions(id uuid PRIMARY KEY,user_id uuid REFERENCES auth.users(id));CREATE FUNCTION auth.jwt() RETURNS jsonb LANGUAGE sql STABLE AS $$SELECT coalesce(nullif(current_setting('request.jwt.claims',true),''),'{}')::jsonb$$;CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$SELECT nullif(auth.jwt()->>'sub','')::uuid$$;GRANT USAGE ON SCHEMA auth TO anon,authenticated,service_role;CREATE PUBLICATION supabase_realtime;\n`;
 for(const f of ['001_schema.sql','002_municipales_2026.sql','003_safeupdate_compatibility.sql'])sql+=await fs.readFile(path.join(repo,'supabase/migrations',f),'utf8')+'\n';
 sql+=`INSERT INTO auth.users(id,email,email_confirmed_at) VALUES('11111111-1111-4111-8111-111111111111','qa-admin@example.invalid',now());INSERT INTO auth.sessions VALUES('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','11111111-1111-4111-8111-111111111111');INSERT INTO public.profiles(id,code,role,active) VALUES('11111111-1111-4111-8111-111111111111','COORD-01','admin',true);\n`;
 for(const f of ['004_v3_expand.sql','005_v3_api.sql','006_v3_enrollment.sql','007_v3_cutover.sql','008_v3_storage.sql'])sql+=await fs.readFile(path.join(repo,'supabase/migrations',f),'utf8')+'\n';
 sql+=`UPDATE pulso_v3.questionnaires SET items=(SELECT jsonb_agg(jsonb_build_object('id',x.v->>'id','name','Candidatura DEMO '||x.i,'list','Lista DEMO '||x.i)) FROM jsonb_array_elements(items) WITH ORDINALITY x(v,i)) WHERE state='draft';`;
 await fs.writeFile(path.join(out,'simulation-install.sql'),sql);
}
for(const name of ['templates','manual-es.html']){try{await fs.cp(path.join(root,'web',name),path.join(out,name),{recursive:true});}catch{}}
const files=(await fs.readdir(out)).filter(f=>/\.(js|css|html|svg|webmanifest)$/.test(f));const hash=crypto.createHash('sha256');for(const f of files)hash.update(await fs.readFile(path.join(out,f)));const cache='pulso-v3-'+hash.digest('hex').slice(0,16);
await fs.writeFile(path.join(out,'sw.js'),`const CACHE=${JSON.stringify(cache)},SHELL=${JSON.stringify(['./',...files.map(f=>'./'+f),'./vendor/supabase.js'])};self.addEventListener('install',e=>e.waitUntil(caches.open(CACHE).then(c=>c.addAll(SHELL))));self.addEventListener('activate',e=>e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k.startsWith('pulso-v3-')&&k!==CACHE).map(k=>caches.delete(k))))));self.addEventListener('fetch',e=>{const r=e.request,u=new URL(r.url);if(r.method!=='GET'||u.origin!==location.origin||!SHELL.some(p=>new URL(p,self.registration.scope).pathname===u.pathname))return;e.respondWith(fetch(r).then(res=>{if(res.ok)e.waitUntil(caches.open(CACHE).then(c=>c.put(r,res.clone())));return res;}).catch(()=>caches.match(r).then(x=>x||new Response('Sin conexión; conecte el dispositivo para instalar la versión.',{status:503}))));});`);
await fs.writeFile(path.join(out,'build-info.json'),JSON.stringify({version:'3.0.0-rc.1',simulation:demo,static_cache:cache,configured:!!url&&!demo,created_at:new Date().toISOString()},null,2));console.log(out);
