import {VERSION,MANUAL,validateConfig,loginEmail,permittedRpc,summarizePreflight,summarizeBoard,allowedError,safeCheck,verdict,record} from './core.mjs?v=pruebas-2';
import {diagnoseStorage,storageChecks} from './storage-diagnostic.mjs?v=pruebas-2';
const $=id=>document.getElementById(id),checks=[];
let cfg,client,busy=false,role=null,storageDiagnostic=null;
const labels={keyboard:'Teclado y errores de ingreso visibles',single_city:'Una ciudad legible',four_cities:'Cuatro ciudades legibles',orientation:'Orientación horizontal y vertical',return_to_app:'Bloquear teléfono y volver al App',downloads:'Abrir PNG / CSV descargados',live_write:'Ensayo: enviar una entrevista y comprobar +1 en otro monitor',offline_queue:'Ensayo: guardar sin red, reconectar y confirmar una sola recepción',role_scope:'Viewer / encuestador sin acceso a funciones de administración'};
for(const id of MANUAL){const label=document.createElement('label');label.textContent=labels[id];const select=document.createElement('select');select.name=id;for(const [value,text]of[['untested','NO PROBADO'],['pass','CONFORME — observado'],['fail','FALLA'],['not_applicable','NO APLICA — revisión necesaria']]){const o=document.createElement('option');o.value=value;o.textContent=text;select.append(o);}label.append(select);$('manual').append(label);}
function message(text){$('message').textContent=text;}
function add(id,status,detail,ms){const old=checks.findIndex(x=>x.id===id),r=safeCheck(id,status,detail,ms);if(old>=0)checks[old]=r;else checks.push(r);render();}
function render(){$('results').replaceChildren();for(const r of checks){const a=document.createElement('article');a.className=r.status;const title=document.createElement('strong');title.textContent=r.id;const status=document.createElement('span');status.textContent={pass:'CONFORME',fail:'FALLA',blocked:'PENDIENTE / REVISAR',untested:'NO PROBADO'}[r.status];const detail=document.createElement('small');detail.textContent=r.detail;a.append(title,status,detail);$('results').append(a);}$('verdict').textContent=verdict(checks);}
const device=()=>({width:innerWidth,height:innerHeight,pixel_ratio:devicePixelRatio,secure:isSecureContext,touch:navigator.maxTouchPoints});
async function run(id,fn){const t=performance.now();try{const detail=await fn();add(id,'pass',detail,performance.now()-t);return true;}catch(e){add(id,'fail',allowedError(e),performance.now()-t);return false;}}
function renderStorage(){
 const box=$('storage-details');box.replaceChildren();if(!storageDiagnostic)return;
 const labels={open:'Abrir base temporal',schema:'Crear almacén temporal',write:'Escribir y confirmar transacción',read:'Leer y confirmar transacción',close:'Solicitar cierre de la conexión',cleanup:'Eliminar solo la base temporal'};
 for(const r of storageDiagnostic.stages){const article=document.createElement('article');article.className=r.status;
  const title=document.createElement('strong');title.textContent=labels[r.stage];const detail=document.createElement('small');
  detail.textContent=`${r.stage} · ${r.status==='pass'?'CONFORME':r.status==='untested'?'NO PROBADO':r.status==='blocked'?'BLOQUEADO':'FALLA'} · ${r.error_name||'Sin error registrado'} · ${r.event_type} · ${r.duration_ms} ms`;
  article.append(title,detail);box.append(article);
 }
}
async function storageTests(){
 storageDiagnostic=null;for(let i=checks.length-1;i>=0;i--)if(checks[i].id.startsWith('browser.indexeddb'))checks.splice(i,1);renderStorage();render();
 message('Comprobando almacenamiento temporal… No cierre esta pestaña. No se modifican las colas del App.');
 storageDiagnostic=await diagnoseStorage();for(const c of storageChecks(storageDiagnostic))add(c.id,c.status,c.detail,c.duration_ms);renderStorage();
 message(storageDiagnostic.readwrite_status==='pass'?(storageDiagnostic.cleanup_status==='pass'?'Almacenamiento y limpieza conformes. Esto no certifica la cola real ni una prueba de envío.':'Lectura y escritura conformes; revise la limpieza temporal por separado. No borre los datos del App.'):'Revise la etapa y el nombre de error indicados abajo. No borre datos del sitio ni reinstale el App.');
}
async function deviceTests(){await run('browser.secure',async()=>{if(!isSecureContext)throw Error('HTTPS_REQUIRED');return 'Contexto HTTPS seguro.';});await run('browser.crypto',async()=>{const key=await crypto.subtle.generateKey({name:'AES-GCM',length:256},false,['encrypt','decrypt']),iv=crypto.getRandomValues(new Uint8Array(12)),s=new TextEncoder().encode('SYNTHETIC_PROBE'),cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,s),plain=await crypto.subtle.decrypt({name:'AES-GCM',iv},key,cipher);if(new TextDecoder().decode(plain)!=='SYNTHETIC_PROBE')throw Error('CRYPTO_FAILED');return 'Cifrado y descifrado del navegador comprobados con texto ficticio.';});await storageTests();const d=device();$('device-info').textContent=d.width+' × '+d.height+' · '+d.touch+' puntos táctiles. No certifica el modelo físico.';}
async function rpc(name,args={}){permittedRpc(name);const {data,error}=await client.rpc(name,args).abortSignal(AbortSignal.timeout(20000));if(error)throw error;return data;}
async function probe(){
 await run('rpc.bootstrap',async()=>{const b=await rpc('v3_bootstrap',{p_client:30000});if(!['admin','viewer','interviewer','coordinator'].includes(b?.actor?.role))throw Error('RESPONSE_INVALID');role=b.actor.role;return 'Ingreso real habilitado. Rol: '+b.actor.role+'. No se exportan nombres ni respuestas.';});
 if(!role){message('La sesión respondió, pero el App no autorizó la lectura. Revise rpc.bootstrap; no se realizaron cambios.');return;}
 if(role==='admin'){
  await run('rpc.preflight',async()=>JSON.stringify(summarizePreflight(await rpc('v3_preflight'))));
  await run('rpc.live_admin',async()=>{const b=await rpc('v3_live_admin_state');if(!b?.operation||!Array.isArray(b.cities))throw Error('RESPONSE_INVALID');return 'Control de administración legible. Ciudades configuradas: '+b.cities.length;});
  await run('rpc.live_internal',async()=>JSON.stringify(summarizeBoard(await rpc('v3_live_board',{p_audience:'internal',p_district:null}))));
 }else{
  await run('rpc.admin_denied',async()=>{try{await rpc('v3_live_admin_state');}catch(e){if(/ADMIN_ONLY|SCOPE_DENIED|42501/.test(String(e.code)+' '+String(e.message)))return 'La cuenta no administrativa fue rechazada correctamente.';throw e;}throw Error('ADMIN_ACCESS_EXPOSED');});
  if(role==='viewer'){try{const s=summarizeBoard(await rpc('v3_live_board',{p_audience:'released',p_district:null}));add('rpc.viewer','pass',JSON.stringify(s));}catch(e){add('rpc.viewer','blocked',allowedError(e)+' — la visualización puede no estar autorizada; no habilitarla para forzar esta prueba.');}}
 }
 await run('rpc.anonymous_denied',async()=>{const r=await fetch(cfg.url+'/rest/v1/rpc/v3_live_admin_state',{method:'POST',headers:{apikey:cfg.key,'Content-Type':'application/json'},body:'{}',cache:'no-store',signal:AbortSignal.timeout(20000)});const d=await r.json().catch(()=>({}));if(![401,403].includes(r.status)||d.code!=='42501')throw Error('ANONYMOUS_ACCESS_UNEXPECTED');return 'La consulta anónima al control privado fue rechazada.';});
 await run('edge.options',async()=>{const r=await fetch(cfg.url+'/functions/v1/field-enrollment',{method:'OPTIONS',cache:'no-store',signal:AbortSignal.timeout(20000)});if(r.status!==204)throw Error('EDGE_PREFLIGHT_FAILED');return 'OPTIONS 204. Solo prueba el acceso al endpoint; no acredita un alta.';});
 await run('edge.unsigned_admin_denied',async()=>{const r=await fetch(cfg.url+'/functions/v1/field-enrollment',{method:'POST',headers:{apikey:cfg.key,'Content-Type':'application/json'},body:JSON.stringify({action:'create_access'}),cache:'no-store',signal:AbortSignal.timeout(20000)});const d=await r.json().catch(()=>({}));if(r.status!==401||d.error!=='V3_SESSION_REQUIRED')throw Error('EDGE_AUTH_BOUNDARY_UNEXPECTED');return 'Petición sin sesión rechazada antes de crear cuentas o consumir presupuesto administrativo.';});
 message('Controles terminados. Revise lo observado, abra las pantallas y guarde un único JSON. No se activó V3 ni se registraron entrevistas.');
}
$('device-check').onclick=async()=>{if(busy)return;busy=true;$('device-check').disabled=true;$('storage-check').disabled=true;try{await deviceTests();}finally{busy=false;$('device-check').disabled=false;$('storage-check').disabled=false;}};
$('storage-check').onclick=async()=>{if(busy)return;busy=true;$('device-check').disabled=true;$('storage-check').disabled=true;try{await storageTests();}finally{busy=false;$('device-check').disabled=false;$('storage-check').disabled=false;}};
$('login-form').onsubmit=async e=>{e.preventDefault();if(busy||!cfg||!client)return;busy=true;$('login-button').disabled=true;role=null;for(let i=checks.length-1;i>=0;i--)if(!checks[i].id.startsWith('browser.'))checks.splice(i,1);render();message('Ingresando y verificando solo lecturas…');let password=e.target.elements.password.value;e.target.elements.password.value='';try{const {error}=await client.auth.signInWithPassword({email:loginEmail(e.target.elements.code.value),password});password='';if(error)throw error;add('auth.login','pass','Sesión real independiente creada. No se exportan tokens.');$('logout').hidden=false;await probe();}catch(error){password='';add('auth.flow','fail',allowedError(error));message('No se completó la prueba: '+allowedError(error)+'. No cambie cuentas ni repita rápidamente.');}finally{password='';busy=false;$('login-button').disabled=false;}};
$('logout').onclick=async()=>{if(busy)return;busy=true;try{const {error}=await client.auth.signOut({scope:'local'});if(error)throw error;await client.realtime.disconnect();$('logout').hidden=true;message('Sesión de prueba cerrada. El App mantiene su sesión independiente.');}catch(e){message('No se confirmó el cierre: '+allowedError(e));}finally{busy=false;}};
$('export').onclick=()=>{const manual=Object.fromEntries(new FormData($('manual-form'))),d=record(checks,manual,device(),manual.physical==='on',storageDiagnostic),url=URL.createObjectURL(new Blob([JSON.stringify(d,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='Pulso_Prueba_Real_'+new Date().toISOString().replace(/[^0-9]/g,'').slice(0,14)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);};
try{cfg=validateConfig(window.PULSO_V3_CONFIG);if(!window.supabase)throw Error('SDK_NOT_LOADED');client=window.supabase.createClient(cfg.url,cfg.key,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false,storageKey:'pulso-readonly-probe-'+crypto.randomUUID()}});$('target').textContent='Proyecto del sitio actual: '+cfg.project+' · pruebas sin escritura de encuestas.';$('login-button').disabled=false;}catch(e){message('Configuración no disponible. Abra esta página desde el sitio publicado, no desde file://. '+allowedError(e));}
