/** Build static frontend. Run with public project config; never supply a server secret. */
import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const url=(process.env.SUPABASE_URL||'').trim();
const key=(process.env.SUPABASE_PUBLISHABLE_KEY||'').trim();
try{
 const u=new URL(url);
 if(u.protocol!=='https:'||!u.hostname.endsWith('.supabase.co')||u.pathname!=='/'||u.search||u.hash)throw new Error('SUPABASE_URL must be the HTTPS project root.');
 let isPublic=key.startsWith('sb_publishable_');
 if(!isPublic&&key.split('.').length===3){try{isPublic=JSON.parse(Buffer.from(key.split('.')[1],'base64url').toString()).role==='anon';}catch{}}
 if(!isPublic)throw new Error('Only a publishable or legacy anon key is allowed. Never a secret/service_role key.');
 const sdk='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.116.0/dist/umd/supabase.js';
 const res=await fetch(sdk,{signal:AbortSignal.timeout(30000)});
 if(!res.ok)throw new Error(`SDK download failed (${res.status}). Nothing published.`);
 const js=await res.text();
 if(js.length<30000||/^\s*</.test(js)||!js.includes('createClient'))throw new Error('Unexpected SDK content. Nothing published.');
 await fs.writeFile(path.join(root,'web','supabase-vendor.js'),js);
 const cfg={supabaseUrl:u.origin,supabasePublishableKey:key,defaultDemo:false,allowDemo:false,version:'2.0.0',electionDate:'2026-10-04'};
 await fs.writeFile(path.join(root,'web','config.js'),'// Public configuration generated by the build. No server secrets.\nwindow.PULSO_CONFIG = '+JSON.stringify(cfg,null,2)+';\n');
 await fs.writeFile(path.join(root,'web','.nojekyll'),'');
 console.log('Frontend prepared: private login, public key only, SDK cached locally. Backend provisioning remains a separate step.');
}catch(e){console.error(e.message);process.exitCode=1;}
