import * as C from './modules/core.mjs';
import * as V from './modules/views.mjs';
import {CloudAPI} from './modules/api.mjs';
import {Vault,legacyPending} from './modules/vault.mjs';
import {parseFile} from './modules/importer.mjs';
import QRCode from 'qrcode';
const config=window.PULSO_V3_CONFIG||{},E=C.esc;
let api=new CloudAPI(config), vault=null;
const S={boot:null,page:'overview',error:null,lastSync:null,offline:!navigator.onLine,queue:[],pack:null,choice:null,geo:{status:'not_requested'},started:null,busy:false,refreshing:false,syncing:false,modal:false,unlock:false,vaultExists:false,loginCode:'',session:null,join:null,preview:null,records:[],moreRecords:false,simulation:config.simulation===true,demoAccounts:[]};
const environment=()=>config.supabaseUrl||'isolated-simulation-v3';
const device=()=>{let id=localStorage.getItem('pulso-v3-device');if(!C.uuidOK(id)){id=C.uuid();localStorage.setItem('pulso-v3-device',id);}return id;};
function setBusy(value){S.busy=value;document.getElementById('app').setAttribute('aria-busy',String(value));}
function render(){document.getElementById('app').setAttribute('aria-busy',String(S.busy));document.getElementById('app').innerHTML=S.unlock?V.unlock(S):S.boot?V.shell(S,V.pageView(S)):V.login(S);if(S.page==='paper')updatePaperCandidates();}
function toast(text){const n=document.getElementById('notice');n.textContent=text;clearTimeout(S.toastTimer);S.toastTimer=setTimeout(()=>n.textContent='',6500);}
function error(e,form=null){S.error=C.feedback(e);const safeRef=e?.reference&&C.uuidOK(e.reference)?e.reference:'';if(safeRef)S.error.code+=' / '+safeRef;
 if(form&&document.body.contains(form)){let box=form.querySelector('.form-error');if(!box){box=document.createElement('div');box.className='form-error';form.prepend(box);}box.innerHTML=V.notice(S.error);box.querySelector('[role=alert]')?.focus();box.scrollIntoView({block:'nearest'});}
 else{render();document.querySelector('#feedback')?.focus({preventScroll:false});}
}
function modal(title,body){S.modal=true;document.getElementById('modal-root').innerHTML=`<div class="modalback"><section class="modal" role="dialog" aria-modal="true" aria-label="${E(title)}"><header class="modalhead"><h2>${E(title)}</h2>${V.button('×','close-modal','','small')}</header>${body}</section></div>`;requestAnimationFrame(()=>document.querySelector('.modal input,.modal select,.modal button')?.focus());}
function close(){S.modal=false;document.getElementById('modal-root').replaceChildren();}
function form(title,id,body,extra=''){modal(title,`<form id="${id}" ${extra}>${body}<div class="actions"><button type="submit" class="primary wide">Confirmar</button></div><p class="inline-note">Espere la confirmación. En caso de error no cambie de código para repetir la operación.</p></form>`);}
function values(form){const d={};for(const [k,v]of new FormData(form)){d[k]=typeof v==='string'?(form.elements.namedItem(k)?.type==='password'?v:v.trim()):v;}for(const input of form.querySelectorAll('[data-type=number]'))d[input.name]=Number(input.value);for(const input of form.querySelectorAll('[data-type=nullable-number]'))d[input.name]=input.value===''?null:Number(input.value);for(const input of form.querySelectorAll('input[type=checkbox]:not([data-array])'))d[input.name]=input.checked;return d;}
const expected=el=>Number(el.dataset.revision||0);
const commandForm=(title,action,body,rev=0)=>form(title,'command-form',body,`data-command="${action}" data-revision="${rev}"`);
const hid=(k,v)=>`<input type="hidden" name="${k}" value="${E(v)}">`;
const reason=(defaultText='')=>V.textarea('Motivo / referencia','reason',defaultText,'required minlength="10" maxlength="500"');
const currentPerson=id=>S.boot.people.find(p=>p.id===id),currentPoint=id=>S.boot.points.find(p=>p.id===id),currentTask=id=>S.boot.assignments.find(p=>p.id===id),currentActor=id=>S.boot.actors.find(p=>p.user_id===id);
const permittedCity=()=>V.cities(S.boot).filter(d=>S.boot.actor.role==='admin'||(S.boot.grants||[]).some(g=>g.district_id===d.id&&!g.revoked_at));
async function openVault(user){vault=new Vault(environment(),user);await vault.open();S.vaultExists=await vault.exists();S.unlock=true;S.error=null;render();}
async function enter(session){S.session=session;S.boot=await api.rpc('v3_bootstrap',{p_client:C.CLIENT});S.loginCode=S.boot.actor.code;S.error=null;S.page=C.allowedPages(S.boot.actor.role)[0];S.lastSync=new Date().toISOString();localStorage.setItem('pulso-v3-last',JSON.stringify({user:session.user.id,environment:environment()}));
 if(S.boot.actor.role==='interviewer'){await openVault(session.user.id);return;}await refresh(true);await api.connect(()=>refresh());}
async function refresh(force=false){if(S.refreshing||!S.boot||S.unlock)return;S.refreshing=true;
 try{if(!navigator.onLine){S.offline=true;return;}const b=await api.rpc('v3_bootstrap',{p_client:C.CLIENT});S.boot=b;S.offline=false;S.lastSync=new Date().toISOString();
 if(b.actor.role==='interviewer'&&vault?.key){await vault.write('bootstrap',b);if(S.pack){const t=b.assignments.find(t=>t.id===S.pack.assignment.id),p=b.points.find(p=>p.id===S.pack.point.id);if(t)S.pack.assignment=t;if(p)S.pack.point=p;if(t?.status!=='active'||p?.state!=='open')S.choice=null;await vault.write('pack',S.pack);}S.queue=await vault.entries();}
 if(['admin','coordinator'].includes(b.actor.role)||b.actor.role==='viewer'&&b.operation.viewer_enabled)S.dashboard=await api.rpc('v3_dashboard');else S.dashboard=null;
 if(force||!S.modal&&!document.querySelector('form:not(#login-form)')&&!['capture','imports'].includes(S.page))render();
 else if(S.page==='capture'){const save=document.querySelector('#capture-form button[type=submit]');if(save)save.disabled=S.busy||S.pack?.assignment.status!=='active'||S.pack?.point.state!=='open'||b.operation.phase!=='running'||Date.now()>Date.parse(S.pack?.grant.capture_until);}
 }catch(e){if(/V3_ACCOUNT_DISABLED|V3_SESSION_REQUIRED/.test(e.message)){vault?.lock();S.pack=null;S.boot=null;S.queue=[];S.unlock=false;close();error(e);}else{S.offline=!navigator.onLine;if(force)error(e);}}
 finally{S.refreshing=false;}}
async function loadRecords(append=false){const last=append?S.records.at(-1):null;const rows=await api.rpc('v3_records',{p_before:last?.received_at||null,p_before_id:last?.id||null,p_limit:100});S.records=append?[...S.records,...rows]:rows;S.moreRecords=rows.length===100;}
async function navigate(page){if(!C.allowedPages(S.boot?.actor.role).includes(page))throw new Error('V3_SCOPE_DENIED');if(S.page==='capture'&&S.choice&&!confirm('¿Salir sin guardar esta selección? Los pendientes ya guardados se conservan.'))return;S.page=page;S.error=null;S.choice=null;
 if(['records','review'].includes(page))await loadRecords();if(page==='queue')S.queue=await vault.entries();if(page==='capture')S.started=new Date().toISOString();if(page==='overview'||page==='results')await refresh();render();scrollTo(0,0);}
async function sync(manual=false){if(S.syncing||!vault?.key||!S.boot||S.boot.actor.role!=='interviewer')return;if(!navigator.onLine){toast('Sin red. El archivo cifrado se conserva.');return;}S.syncing=true;
 try{const rows=await vault.entries(),attempted=rows.filter(x=>x.status!=='received'&&(manual||!x.blocked));for(const row of attempted){
  if(!vault?.key||!S.boot)break;
  try{const r=await api.rpc('v3_submit_response',{p_event:row.event,p_client:C.CLIENT});await vault.acknowledge(row.event,r);}
  catch(e){await vault.failure(row.event,e);if(/V3_ACCOUNT_DISABLED|V3_SESSION_REQUIRED|V3_TASK_DENIED|V3_WORKER_NOT_APPROVED/.test(e.message)){error(e);break;}if(/network|fetch|timeout/i.test(e.message))break;}
 }S.queue=await vault.entries();if(S.pack)await api.rpc('v3_ping',{p_grant:S.pack.grant.id,p_pending:S.queue.filter(x=>x.status!=='received').length}).catch(()=>{});
 if(manual||attempted.length)toast(S.queue.some(x=>x.status!=='received')?'Revise los pendientes sin confirmar.':'Todos los registros locales tienen recibo.');if(S.page==='queue')render();
 }finally{S.syncing=false;}}
async function logout(){if(S.syncing)throw new Error('V3_WAIT_FOR_SYNC');if(vault?.key){const rows=await vault.entries(),n=rows.filter(x=>x.status!=='received').length;if(n&&!confirm(`Hay ${n} pendiente(s) cifrado(s). Se conservarán para esta misma persona; la siguiente no podrá enviarlos. ¿Bloquear archivo y salir?`))return;await vault.write('pack',S.pack);vault.lock();}
 if(navigator.onLine)await api.logout();else if(!S.simulation){const sb=await api.client();await sb.auth.signOut({scope:'local'}).catch(()=>{});}S.boot=null;S.session=null;S.pack=null;S.queue=[];S.unlock=false;S.error=null;close();render();}
function credentials(r){if(r.credentials_unavailable){modal('Acceso creado',`<p>La cuenta existe, pero no se vuelve a mostrar la contraseña original. Use Restablecer clave tras confirmar el estado.</p><pre>${E(r.code||'')}</pre>`);return;}const c=r.credential;modal('Credenciales privadas',`<p>Cuenta creada. Entregue solamente esta credencial a su titular.</p><div class="credential">${E(c.code)}<br>${E(c.password)}</div><button class="primary wide" data-action="download-credential">Guardar credencial privada</button><p class="inline-note">No guardar en GitHub ni en una carpeta pública.</p>`);S.credential=c;}
function updatePaperCandidates(){const el=document.querySelector('#paper-task');if(!el)return;const t=currentTask(el.value),q=S.boot.questionnaires.find(q=>q.id===t?.questionnaire_id),list=document.querySelector('#paper-candidate-list');if(list)list.innerHTML=(q?.items||[]).map(c=>`<option value="${E(c.id)}">${E(c.name)} · ${E(c.list)}</option>`).join('');}
function stationForm(id){const s=S.boot.stations.find(s=>s.id===id);commandForm(s?'Editar local':'Añadir local','station.save',(s?hid('id',s.id):V.select('Ciudad','district_id',permittedCity()))+V.field('Código interno único','code',s?.code||'','text','required maxlength="60"')+V.field('Nombre real del local','name',s?.name||'','text','required maxlength="160"')+V.field('Dirección','address',s?.address||'','text','required minlength="5" maxlength="250"')+V.field('Código oficial (opcional)','official_code',s?.official_code||'','text','maxlength="100"'),s?.revision);}
function pointForm(id){const p=currentPoint(id);commandForm(p?'Editar punto':'Añadir punto','point.save',(p?hid('id',p.id):V.select('Local','station_id',S.boot.stations.map(s=>({id:s.id,name:cityLabel(s)}))))+V.field('Código único del punto','code',p?.code||'','text','required maxlength="60"')+V.field('Ubicación concreta de la encuesta','label',p?.label||'','text','required minlength="2" maxlength="150"')+`<label class="check"><input type="checkbox" name="planned" ${p?.planned!==false?'checked':''}>Punto previsto en el plan</label><div class="formgrid">`+V.field('Latitud opcional','latitude',p?.latitude??'','number','step="any" min="-90" max="90" data-type="nullable-number"')+V.field('Longitud opcional','longitude',p?.longitude??'','number','step="any" min="-180" max="180" data-type="nullable-number"')+'</div>',p?.revision);}
const cityLabel=s=>`${C.city(s.district_id)} · ${s.code} · ${s.name}`;
function questionnaireForm(id,copy=false){const q=S.boot.questionnaires.find(q=>q.id===id);form('Formulario versionado','questionnaire-form',(q&&!copy?hid('id',q.id):'')+V.select('Ciudad','district_id',C.CITIES,q?.district_id)+V.field('Cargo','contest',q?.contest||S.boot.operation.contest,'text','required maxlength="120"')+V.field('Seleccionar cada N.º elector','sample_interval',q?.sample_interval||5,'number','required min="1" max="100" data-type="number"')+V.textarea('Protocolo de selección y rechazos','methodology',q?.methodology||'','required minlength="20" maxlength="4000"')+V.field('Referencia verificada','reference',q?.verified_reference||'','text','required minlength="5" maxlength="1000"')+`<h3>Candidaturas en orden</h3><div id="candidate-rows">${(q?.items||[{id:C.uuid(),name:'',list:''},{id:C.uuid(),name:'',list:''}]).map(c=>candidateEditor(c)).join('')}</div>${V.button('Añadir candidatura','candidate-add')}<p class="inline-note">Conserve UUID si es la misma candidatura. Publicar esta versión requiere otra confirmación.</p>`,`data-revision="${q&&!copy?q.revision:0}"`);}
const candidateEditor=c=>`<div class="formgrid" data-candidate="${E(c.id)}">${V.field('Nombre','candidate_name',c.name,'text','required maxlength="100"')}${V.field('Lista','candidate_list',c.list,'text','required maxlength="100"')}${V.button('Quitar esta fila','candidate-remove',c.id,'small danger')}</div>`;
async function click(action,id,el){
 switch(action){
 case 'close-modal':S.credential=null;close();break;
 case 'nav':await navigate(id);break;
 case 'refresh':S.error=null;await refresh(true);break;
 case 'logout':await logout();break;
 case 'enter-code':S.join=' ';S.error=null;render();break;
 case 'offline-open':{let hint;try{hint=JSON.parse(localStorage.getItem('pulso-v3-last')||'null');}catch{}if(!hint||hint.environment!==environment())throw new Error('V3_NO_LOCAL_ARCHIVE');S.offline=!navigator.onLine;await openVault(hint.user);break;}
 case 'station-new':stationForm();break;case 'station-edit':stationForm(id);break;
 case 'point-new':pointForm();break;case 'point-edit':pointForm(id);break;
 case 'point-approve':{const p=currentPoint(id);commandForm('Aprobar lugar real','point.approve',hid('id',id)+`<p>${E(V.namePoint(S.boot,id))}</p><label class="check"><input name="verified" type="checkbox" required>Verifiqué el lugar, el permiso operativo y su pertenencia a la ciudad.</label>`+reason(),p.revision);break;}
 case 'point-open':case 'point-pause':case 'point-close':{const p=currentPoint(id);commandForm('Cambiar estado del punto','point.state',hid('id',id)+hid('state',{'point-open':'open','point-pause':'paused','point-close':'closed'}[action])+`<p>${E(V.namePoint(S.boot,id))}. No cambia otros puntos.</p>`+reason(),p.revision);break;}
 case 'person-new':commandForm('Incorporar persona','person.add',V.select('Ciudad','district_id',permittedCity())+V.select('Punto de incorporación (opcional)','point_id',[{id:'',name:'Sin punto específico (requiere permiso de ciudad)'},...S.boot.points.map(p=>({id:p.id,name:V.namePoint(S.boot,p.id)}))])+V.field('Nombre / denominación reconocible','display_name','','text','required maxlength="100"'));break;
 case 'person-approve':case 'person-suspend':case 'person-restore':{const p=currentPerson(id);commandForm(action==='person-approve'?'Aprobar persona':action==='person-suspend'?'Suspender persona':'Revisar y restaurar',action.replace('-','.'),hid('id',id)+`<p>${E(p.code)} · ${E(p.display_name)}</p>`+reason(),p.revision);break;}
 case 'issue':{const p=currentPerson(id);if(!confirm(`¿Generar un acceso de un solo uso para ${p.display_name}? Reemplaza cualquier invitación previa no completada.`))break;const r=await api.edge({action:'issue',person_id:id,point_id:p.recruit_point,request_id:C.uuid()});if(!r.token)throw new Error('V3_INVITE_REISSUE_REQUIRED');const link=new URL(location.pathname,location.origin);link.hash='join='+r.token;const qr=await QRCode.toDataURL(link.href,{errorCorrectionLevel:'M',margin:2,width:320});modal('Acceso de una sola persona',`<div class="qr"><h3>${E(p.code)} · ${E(p.display_name)}</h3><img src="${qr}" alt="QR de incorporación individual"><p>Vence ${C.time(r.expires_at)}. No lo publique en grupos.</p><div class="credential">${E(r.token)}</div><p class="inline-note">Escanear abre la misma dirección de esta versión. La persona debe confirmar y capacitarse.</p>${V.button('Revocar este acceso','revoke-invite',r.id,'danger')}</div>`);await refresh();break;}
 case 'revoke-invite':await api.edge({action:'revoke',id});close();await refresh(true);break;
 case 'task-new':form('Asignar tarea','assignment-form',V.select('Persona','person_id',S.boot.people.map(p=>({id:p.id,name:p.code+' · '+p.display_name})),id)+V.select('Punto aprobado','point_id',S.boot.points.filter(p=>['approved','paused','open'].includes(p.state)).map(p=>({id:p.id,name:V.namePoint(S.boot,p.id)})))+reason());break;
 case 'task-finish':case 'task-revoke':{const t=currentTask(id);commandForm(action==='task-finish'?'Finalizar tarea / permitir pendientes':'Revocar dispositivo','assignment.'+(action==='task-finish'?'finish':'revoke_device'),hid('id',id)+`<p>${E(V.namePoint(S.boot,t.point_id))}. Los registros anteriores conservan su origen.</p>`+reason(),t.revision);break;}
 case 'task-ack':{const t=currentTask(id);await api.rpc('v3_ack_assignment',{p_assignment:id,p_version:t.revision,p_questionnaire:t.questionnaire_id,p_point:t.point_id,p_client:C.CLIENT});await refresh(true);break;}
 case 'task-start':{if(!vault?.key)throw new Error('V3_VAULT_LOCKED');S.pack=await api.rpc('v3_start_task',{p_assignment:id,p_device:device(),p_client:C.CLIENT});await vault.write('pack',S.pack);await refresh();await navigate('capture');break;}
 case 'training':form('Capacitación breve + práctica','training-form',`<p>Esta práctica nunca genera una encuesta. Seleccione las respuestas correctas y simule una captura local.</p>`+V.select('¿A quién puede entrevistar?','first',[{id:'',name:'Seleccione'},{id:'after_voting',name:'A quien confirma que ya votó'},{id:'anyone',name:'A cualquier persona'}]) +V.select('¿La persona puede negarse?','second',[{id:'',name:'Seleccione'},{id:'voluntary',name:'Sí, la participación es voluntaria'},{id:'mandatory',name:'No, debe responder'}])+V.select('¿Pendiente local significa recibido?','third',[{id:'',name:'Seleccione'},{id:'pending_not_received',name:'No; falta la confirmación del servidor'},{id:'same',name:'Sí, ya cuenta en resultados'}])+`<div class="ack"><strong>Práctica separada</strong><p>Persona ya votó y rechaza participar. Elija:</p>${V.select('Registro de práctica','practice',[{id:'',name:'Seleccione'},{id:'refused',name:'Rechaza la encuesta; sin candidatura'},{id:'guess',name:'Asignar una candidatura probable'}])}</div><label class="check"><input name="ack" type="checkbox" required>Comprendí la diferencia entre práctica, pendiente y recibo.</label>`);break;
 case 'choice':S.choice={outcome:el.dataset.outcome,candidate_id:el.dataset.outcome==='candidate'?id:null,label:el.dataset.label};document.querySelectorAll('.choice').forEach(b=>{const yes=b===el;b.classList.toggle('selected',yes);b.setAttribute('aria-pressed',yes);b.querySelector('.mark').textContent=yes?'✓':'○';});{const c=document.querySelector('#capture-form [name=consent]');c.disabled=S.choice.outcome==='refused';if(c.disabled)c.checked=false;}document.getElementById('selection-summary').textContent=S.choice.label;document.querySelector('.capture-actions')?.classList.add('ready');break;
 case 'gps':if(!navigator.geolocation)S.geo={status:'unavailable'};else S.geo=await new Promise(resolve=>navigator.geolocation.getCurrentPosition(p=>resolve({status:'granted',latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy_m:p.coords.accuracy,captured_at:new Date(p.timestamp).toISOString()}),e=>resolve({status:e.code===1?'denied':'unavailable'}),{timeout:10000,enableHighAccuracy:true,maximumAge:30000}));toast(S.geo.status==='granted'?'GPS obtenido. Se conserva la selección actual.':'No se obtuvo GPS; el punto asignado sigue registrado.');break;
 case 'clear-gps':S.geo={status:'not_requested'};toast('GPS omitido.');break;
 case 'sync':await sync(true);break;
 case 'recover-upload':{const row=S.queue.find(x=>x.event.id===id);if(!row)throw new Error('V3_NOT_FOUND');if(!confirm('¿Solicitar envío de esta tarea anterior? Solo sus registros; quedarán pendientes de revisión, nunca contados automáticamente.'))break;await api.rpc('v3_recover_upload',{p_grant:row.event.grant_id});await sync(true);break;}
 case 'finish-my-task':if(confirm('¿Finalizar esta tarea? No podrá añadir visitas; los pendientes se conservan.')){await api.rpc('v3_finish_my_task',{p_assignment:id,p_reason:'Fin de tarea solicitado por el encuestador'});await refresh(true);}break;
 case 'void':if(confirm('¿Anular un error propio? Se conserva el registro y deja de contar.')){await api.rpc('v3_void_own',{p_id:id,p_reason:'capture_error'});const receipts=await api.rpc('v3_receipts',{p_ids:[id]});const old=await vault?.read('response:'+id);if(old&&receipts[0])await vault.acknowledge(old.event,receipts[0]);await refresh(true);}break;
 case 'more-records':await loadRecords(true);render();break;
 case 'questionnaire-new':questionnaireForm();break;case 'questionnaire-edit':questionnaireForm(id);break;case 'questionnaire-copy':questionnaireForm(id,true);break;
 case 'candidate-add':{const rows=document.querySelectorAll('[data-candidate]');if(rows.length>=12)throw new Error('V3_TOO_MANY_CANDIDATES');document.getElementById('candidate-rows').insertAdjacentHTML('beforeend',candidateEditor({id:C.uuid(),name:'',list:''}));break;}
 case 'candidate-remove':if(document.querySelectorAll('[data-candidate]').length<=2)throw new Error('V3_CANDIDATES_REQUIRED');el.closest('[data-candidate]').remove();break;
 case 'questionnaire-publish':{const q=S.boot.questionnaires.find(q=>q.id===id);commandForm('Publicar formulario verificado','questionnaire.publish',hid('id',id)+`<p>${E(C.city(q.district_id))} v${q.version}. Se pausarán los puntos y tareas anteriores de esa ciudad.</p><label class="check"><input type="checkbox" name="confirmed" required>Verifiqué cargo, candidaturas, listas, orden y protocolo con evidencia.</label>`,q.revision);break;}
 case 'access-new':form('Crear acceso de coordinación / lectura','access-form',V.select('Rol','role',[{id:'coordinator',name:'Coordinador'},{id:'viewer',name:'Viewer'},{id:'admin',name:'Administrador completo'}])+V.field('Código único','code','','text','required pattern="(COORD|VIEW|ADMIN)-[A-Z0-9]{3,12}" placeholder="COORD-001"')+V.field('Nombre','display_name','','text','required maxlength="100"')+'<p>Asignar alcances es un paso separado. Un administrador tiene acceso global.</p>');break;
 case 'grant-new':{const a=currentActor(id);commandForm('Autorizar alcance','grant.save',hid('user_id',id)+V.select('Ciudad','district_id',C.CITIES)+(a.role==='viewer'?'':V.select('Punto','point_id',[{id:'',name:'Todos los puntos de la ciudad'},...S.boot.points.map(p=>({id:p.id,name:V.namePoint(S.boot,p.id)}))]))+V.field('Válido hasta','valid_until','','datetime-local','required')+(a.role==='viewer'?hid('viewer_cap','true'):`<p>Autorice solamente funciones necesarias:</p>${['operations','recruit','assign','manage_points','control_points'].map(k=>`<label class="check"><input type="checkbox" name="cap" data-array value="${k}">${E({operations:'Ver operación',recruit:'Incorporar personal',assign:'Asignar tareas',manage_points:'Crear / aprobar puntos',control_points:'Abrir / pausar puntos'}[k])}</label>`).join('')}`));break;}
 case 'grant-revoke':{const g=S.boot.grants.find(g=>g.id===id);if(confirm('¿Revocar este alcance?')){await api.command('grant.revoke',{id},g.revision);await refresh(true);}break;}
 case 'actor-enable':{const a=currentActor(id);commandForm('Reactivar con nuevo inicio de sesión','actor.enable',hid('id',id)+reason(),a.revision);break;}
 case 'actor-disable':{const a=currentActor(id);if(confirm('¿Desactivar '+a.code+'?')){await api.command('actor.disable',{id},a.revision);await refresh(true);}break;}
 case 'reset-worker':if(confirm('¿Restablecer acceso? Revoca las sesiones y autorizaciones anteriores. Guarde y entregue la nueva clave solo al titular.'))credentials(await api.edge({action:'reset_password',user_id:id}));break;
 case 'download-credential':if(S.credential){C.download(C.credentialText(S.credential),'PULSO_CREDENCIAL_PRIVADA_NO_PUBLICAR.txt','text/plain;charset=utf-8');S.credential=null;close();}break;
 case 'viewer-toggle':commandForm('Acceso a instantáneas de ciudad','viewer.access',hid('enabled',!S.boot.operation.viewer_enabled)+reason(),S.boot.operation.revision);break;
 case 'viewer-publish':commandForm('Publicar instantánea autorizada','viewer.publish',hid('district_id',id)+`<p>${E(C.city(id))}. Los conteos pequeños se suprimen. La publicación no sustituye autorización normativa.</p><label class="check"><input name="release_authorized" type="checkbox" required>Tengo autorización para divulgar esta instantánea a sus viewers.</label>`+reason());break;
 case 'review-decision':{const r=S.records.find(r=>r.id===id);commandForm('Revisión independiente','review.decide',hid('id',id)+`<p>Registro ${E(id)} · ${E(r.reason_code)} · ${E(r.source)}</p>`+V.select('Decisión','decision',[{id:'excluded',name:'Excluir'},{id:'accepted',name:'Aceptar'}])+reason(),r.revision);break;}
 case 'import-apply':if(S.preview?.valid&&confirm('¿Aplicar exactamente este lote validado? No abre puntos ni publica formularios.')){await api.rpc('v3_import_apply',{p_batch:S.preview.batch_id,p_hash:S.preview.hash});S.preview=null;await refresh(true);}break;
 case 'operation-run':case 'operation-pause':case 'operation-close':commandForm('Control global','operation.state',hid('state',{'operation-run':'running','operation-pause':'paused','operation-close':'closed'}[action])+`<p>Esta operación afecta la disponibilidad global. Los puntos se abren por separado.</p>`+reason(),S.boot.operation.revision);break;
 case 'preflight':modal('Preflight de V3',`<pre>${E(JSON.stringify(await api.rpc('v3_preflight'),null,2))}</pre><p>Los pendientes en teléfonos y las pruebas físicas no se verifican por este RPC.</p>`);break;
 case 'activate':form('Activación técnica controlada','activate-form',`<p>No habilita encuestas automáticamente. Tras activar, el cliente V2 no podrá consultar ni escribir. No revierte datos.</p><label class="check"><input name="outbox" type="checkbox" required>Se han preservado y reconciliado las colas V2 de todos los titulares.</label>`+V.field('Referencia de respaldo y restauración comprobada','backup','','text','required minlength="10"')+V.field('Referencia de aceptación externa firmada','acceptance','','text','required minlength="10"'));break;
 case 'password':form('Cambiar mi contraseña','password-form',V.field('Nueva contraseña','password','','password','required minlength="16" autocomplete="new-password"')+V.field('Repetir','repeat','','password','required minlength="16" autocomplete="new-password"'));break;
 case 'rescue-export':if(!vault?.key)throw new Error('V3_VAULT_LOCKED');C.download(JSON.stringify(await vault.exportEncrypted()),'PULSO_COPIA_CIFRADA_'+new Date().toISOString().slice(0,10)+'.json','application/json');break;
 case 'rescue-import':form('Recuperar copia de mi propia identidad','rescue-form',V.field('Copia cifrada','file','','file','required accept=".json"')+V.field('Frase usada en la copia','phrase','','password','required minlength="12"')+'<p>No cambia el origen ni las respuestas. La misma cuenta debe volver a autenticarse.</p>');break;
 case 'attachments':{const rows=await api.rpc('v3_attachments',{p_point:id});modal('Documentos del punto',`<p>Solo permiso del local, protocolo o incidente. No fotografías, documentos ni identificadores de votantes.</p><form id="attachment-form" data-point="${E(id)}">${V.select('Tipo','purpose',[{id:'site_authorization',name:'Autorización del punto'},{id:'methodology',name:'Protocolo'},{id:'incident',name:'Incidente'}])}${V.field('PDF / PNG / JPEG hasta 10 MB','file','','file','required accept=".pdf,.png,.jpg,.jpeg"')}<button type="submit" class="primary">Adjuntar</button></form>${rows.map(r=>`<div class="listrow"><span>${E(r.file_name)}</span>${V.button('Abrir por enlace temporal','attachment-open',r.object_path,'small')}</div>`).join('')}`);break;}
 case 'attachment-open':{const url=await api.attachmentURL(id);modal('Documento privado',`<a class="button primary" href="${E(url)}" target="_blank" rel="noopener noreferrer">Abrir documento (enlace válido 60 s)</a>`);break;}
 case 'demo-account':{if(!S.simulation)throw new Error('V3_SCOPE_DENIED');await enter(await api.demoLogin(id));break;}
 default:throw new Error('V3_UNKNOWN_ACTION');
 }}
async function submit(formEl){let data=values(formEl);const request=formEl.dataset.request||(formEl.dataset.request=C.uuid());switch(formEl.id){
 case 'login-form':S.loginCode=data.code;await enter(await api.login(data.code,data.password));break;
 case 'join-form':{let claim;try{claim=JSON.parse(sessionStorage.getItem('pulso-v3-claim')||'null');}catch{}if(!claim||claim.token!==data.token)claim={token:data.token,secret:C.token(),lock:C.uuid()};sessionStorage.setItem('pulso-v3-claim',JSON.stringify(claim));const session=await api.claim(claim.token,claim.secret,claim.lock);sessionStorage.removeItem('pulso-v3-claim');S.join=null;await enter(session);break;}
 case 'vault-form':{if(!S.vaultExists&&data.phrase!==data.repeat)throw new Error('V3_VAULT_WRONG_KEY');await vault.unlock(data.phrase);S.unlock=false;S.error=null;
  if(!S.boot){if(navigator.onLine){const ss=await api.session();if(!ss||ss.user.id!==vault.user)throw new Error('V3_SESSION_REQUIRED');S.session=ss;S.boot=await api.rpc('v3_bootstrap',{p_client:C.CLIENT});}else{S.boot=await vault.read('bootstrap');if(!S.boot||S.boot.actor.role!=='interviewer')throw new Error('V3_NO_LOCAL_TASK');S.offline=true;}}
  if(S.boot.actor.user_id!==vault.user)throw new Error('V3_VAULT_WRONG_KEY');await vault.write('bootstrap',S.boot);S.pack=await vault.read('pack');S.queue=await vault.entries();S.page='task';render();if(navigator.onLine){await refresh();await api.connect(()=>refresh());await sync();}break;}
 case 'command-form':{if(data.point_id==='')data.point_id=null;if(data.enabled==='true'||data.enabled==='false')data.enabled=data.enabled==='true';if(formEl.dataset.command==='grant.save'){data.capabilities=data.viewer_cap?['view_results']:[...formEl.querySelectorAll('[name=cap]:checked')].map(x=>x.value);delete data.cap;delete data.viewer_cap;data.valid_until=new Date(data.valid_until).toISOString();}await api.command(formEl.dataset.command,data,expected(formEl),request);close();await refresh(true);toast('Operación confirmada.');break;}
 case 'assignment-form':await api.command('assignment.create',data,0,request);close();await refresh(true);break;
 case 'operation-form':data.lease_minutes=Number(data.lease_minutes);data.drain_hours=Number(data.drain_hours);await api.command('operation.save',data,expected(formEl),request);await refresh(true);break;
 case 'training-form':if(data.practice!=='refused'||!data.ack)throw new Error('V3_TRAINING_RETRY');await api.rpc('v3_training',{p_answers:[data.first,data.second,data.third],p_practice_ack:true,p_client:C.CLIENT});close();await refresh(true);toast('Práctica completada. Espere aprobación del coordinador.');break;
 case 'capture-form':{if(!S.choice)throw new Error('V3_INVALID_ANSWER');if(S.boot.operation.phase!=='running')throw new Error('V3_POINT_OR_VERSION_CLOSED');let geo={...S.geo};if(geo.status==='granted'&&Date.now()-Date.parse(geo.captured_at)>900000)geo={status:'stale'};
  const e={id:C.uuid(),assignment_id:S.pack.assignment.id,grant_id:S.pack.grant.id,questionnaire_id:S.pack.questionnaire.id,point_id:S.pack.point.id,started_at:S.started,captured_at:new Date().toISOString(),candidate_id:S.choice.candidate_id,outcome:S.choice.outcome,consent:S.choice.outcome!=='refused'&&data.consent===true,already_voted:data.voted===true,geo};
  C.validateCapture(e,S.pack);await vault.add(e);S.choice=null;S.started=new Date().toISOString();S.queue=await vault.entries();render();scrollTo(0,0);toast('Guardado cifrado. Esperando recibo del servidor.');await sync();break;}
 case 'questionnaire-form':{data.items=[...formEl.querySelectorAll('[data-candidate]')].map(r=>({id:r.dataset.candidate,name:r.querySelector('[name=candidate_name]').value.trim(),list:r.querySelector('[name=candidate_list]').value.trim()}));delete data.candidate_name;delete data.candidate_list;await api.command('questionnaire.save',data,expected(formEl),request);close();await refresh(true);break;}
 case 'access-form':if(data.role==='admin'&&!confirm('¿Crear un administrador con acceso completo?'))break;credentials(await api.edge({action:'create_access',...data,request_id:request}));await refresh();break;
 case 'import-form':S.preview=await api.rpc('v3_import_preview',{p_kind:data.kind,p_rows:await parseFile(data.file,data.kind),p_client:C.CLIENT});render();break;
 case 'export-form':{const r=await api.command('export.create',{kind:data.kind,district_id:data.district_id||null},0,request);let all=[],offset=0;do{const p=await api.rpc('v3_export_page',{p_id:r.id,p_offset:offset,p_limit:250});if(Array.isArray(p.data))all.push(...p.data);else{all=p.data;offset=null;break;}offset=p.next_offset;}while(offset!==null);if(Array.isArray(all)){const keys=all.length?Object.keys(all[0]):['id'];C.download(C.csv([keys,...all.map(x=>keys.map(k=>typeof x[k]==='object'?JSON.stringify(x[k]):x[k]))]),'Pulso_V3_INTERNO_'+data.kind+'.csv','text/csv');}else C.download(JSON.stringify(all,null,2),'Pulso_V3_INTERNO_'+data.kind+'.json','application/json');toast('Instantánea completa descargada.');delete formEl.dataset.request;break;}
 case 'paper-form':data.response_id=formEl.dataset.responseId||(formEl.dataset.responseId=C.uuid());data.started_at=new Date(data.started_at).toISOString();data.captured_at=new Date(data.captured_at).toISOString();if(data.outcome!=='candidate')data.candidate_id=null;if(data.outcome==='refused')data.consent=false;await api.command('paper.submit',data,0,request);toast('Papel transcrito; revisión independiente obligatoria.');formEl.reset();delete formEl.dataset.request;delete formEl.dataset.responseId;break;
 case 'password-form':if(data.password!==data.repeat)throw new Error('V3_PASSWORD_MISMATCH');await api.changePassword(data.password);close();toast('Contraseña actualizada.');break;
 case 'rescue-form':{if(data.file.size>20*1024*1024)throw new Error('V3_IMPORT_LIMIT');const result=await vault.importEncrypted(JSON.parse(await data.file.text()),data.phrase);close();toast(result.imported+' registros recuperados; se comprobarán los recibos.');await sync();break;}
 case 'attachment-form':{const f=data.file;if(f.size>10485760||!['application/pdf','image/png','image/jpeg'].includes(f.type))throw new Error('V3_INVALID_ATTACHMENT');const first=new Uint8Array(await f.slice(0,8).arrayBuffer());if(f.type==='application/pdf'&&new TextDecoder().decode(first).slice(0,5)!=='%PDF-'||f.type==='image/png'&&(first[0]!==137||first[1]!==80)||f.type==='image/jpeg'&&(first[0]!==255||first[1]!==216))throw new Error('V3_INVALID_ATTACHMENT');const r=await api.command('attachment.reserve',{id:formEl.dataset.point,purpose:data.purpose,file_name:f.name,media_type:f.type,bytes:f.size},0,request);await api.attachmentUpload(r.path,f);await api.rpc('v3_attachment_confirm',{p_id:r.id});close();toast('Documento privado guardado.');break;}
 case 'activate-form':if(!confirm('¿Activar V3 después de la aceptación externa? Cierra las interfaces V2.'))break;await api.rpc('v3_activate',{p_legacy_outbox_handled:data.outbox,p_backup_reference:data.backup,p_acceptance_reference:data.acceptance});close();await refresh(true);break;
 default:throw new Error('V3_UNKNOWN_FORM');}}
document.addEventListener('click',async event=>{const el=event.target.closest('[data-action]');if(!el)return;event.preventDefault();if(S.busy)return;S.error=null;setBusy(true);el.disabled=true;try{await click(el.dataset.action,el.dataset.id,el);}catch(e){error(e,el.closest('form'));}finally{setBusy(false);if(el.isConnected)el.disabled=false;}});
document.addEventListener('submit',async event=>{event.preventDefault();const form=event.target;if(S.busy||!form.reportValidity())return;setBusy(true);const buttons=[...form.querySelectorAll('button')];buttons.forEach(b=>b.disabled=true);try{S.error=null;await submit(form);}catch(e){error(e,form);}finally{setBusy(false);buttons.filter(b=>b.isConnected).forEach(b=>b.disabled=false);}});
document.addEventListener('change',e=>{if(e.target.id==='mobile-nav'){if(S.busy){e.target.value=S.page;toast('Espere a que termine la operación antes de cambiar de pantalla.');}else navigate(e.target.value).catch(error);}if(e.target.id==='paper-task')updatePaperCandidates();if(e.target.name==='outcome'&&e.target.closest('#paper-form')){const f=e.target.form;f.elements.consent.disabled=e.target.value==='refused';if(f.elements.consent.disabled)f.elements.consent.checked=false;}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&S.modal&&!S.busy)close();if(e.key==='Tab'&&S.modal){const nodes=[...document.querySelectorAll('.modal button:not([disabled]),.modal input:not([disabled]),.modal select,.modal textarea,.modal a[href]')].filter(x=>x.offsetParent);if(!nodes.length)return;const a=nodes[0],b=nodes.at(-1);if(e.shiftKey&&document.activeElement===a){e.preventDefault();b.focus();}else if(!e.shiftKey&&document.activeElement===b){e.preventDefault();a.focus();}}});
window.addEventListener('offline',()=>{S.offline=true;if(S.boot&&!S.busy&&!S.modal&&S.page!=='capture')render();});window.addEventListener('online',()=>{refresh(true).then(()=>sync()).catch(error);});document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh().then(()=>sync()).catch(()=>{});});
setInterval(()=>{if(S.boot&&!S.unlock&&!S.busy){refresh();if(S.page!=='capture'||!S.choice)sync();}},20000);
async function init(){const fragment=new URLSearchParams(location.hash.slice(1));if(fragment.has('join')){S.join=fragment.get('join');history.replaceState(null,'',location.pathname+location.search);}const legacy=await legacyPending();if(legacy.count)S.error={code:'V2_OUTBOX_PRESENT',title:'Pendientes de otra versión',message:`Hay ${legacy.count} pendiente(s) V2 en este navegador. V3 no los modifica. Coordine su preservación antes de cambiar de operativo.`};
 if(S.simulation){const {createSimulation}=await import('./simulation.mjs');api=await createSimulation();S.demoAccounts=api.accounts;}
 render();if(S.join)return;
 try{const session=await api.session();if(session)await enter(session);}catch(e){error(e);}
 if(!S.simulation&&'serviceWorker'in navigator&&window.isSecureContext)await navigator.serviceWorker.register('./sw.js');}
init().catch(error);
