/** Company hierarchy on real disposable Auth/PostgREST/Edge. No remote credentials. */
import fs from 'node:fs/promises';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import pg from 'pg';import {createClient} from '@supabase/supabase-js';
const ctx=JSON.parse(await fs.readFile('/tmp/pulso-v3-local-context.json','utf8'));
if(new URL(ctx.url).hostname!=='127.0.0.1'||new URL(ctx.dbUrl).hostname!=='127.0.0.1')throw Error('Disposable localhost only');
const db=new pg.Client({connectionString:ctx.dbUrl,statement_timeout:30000});await db.connect();const checks=[],clients=[];
const make=()=>{const c=createClient(ctx.url,ctx.key,{auth:{persistSession:false,autoRefreshToken:false}});clients.push(c);return c;};
const root=make(),company=make(),viewer=make();let companyCredential,viewerCredential,owner;
const rpc=async(c,name,args={})=>{const r=await c.rpc(name,args).abortSignal(AbortSignal.timeout(20000));if(r.error)throw Object.assign(new Error(r.error.message),r.error);return r.data;};
const cmd=(c,action,data,expected=0)=>rpc(c,'v3_command',{p_action:action,p_data:data,p_expected:expected,p_request_id:randomUUID(),p_client:30000});
const edge=async(c,body)=>{const t=(await c.auth.getSession()).data.session;const r=await fetch(ctx.url+'/functions/v1/field-enrollment',{method:'POST',headers:{Origin:'http://127.0.0.1:8044',apikey:ctx.key,'Content-Type':'application/json',Authorization:'Bearer '+t.access_token},body:JSON.stringify(body),signal:AbortSignal.timeout(30000)});const d=await r.json();if(!r.ok)throw new Error(d.error||'HTTP_ERROR');return d;};
async function login(c,code,password){const r=await c.auth.signInWithPassword({email:code.includes('@')?code:code.toLowerCase()+'@pulso-encuestadores.invalid',password});if(r.error)throw r.error;return r.data.user;}
const check=async(name,f)=>{try{await f();checks.push({name,pass:true});console.log('PASS',name);}catch(e){checks.push({name,pass:false,error:String(e.message).slice(0,300)});throw e;}};
try{
 owner=await login(root,ctx.adminMail,ctx.adminPassword);
 const before=(await db.query('select count(*)::int n from pulso_v3.responses')).rows[0].n;
 await check('012 additive module preserves existing real-HTTP synthetic records',async()=>{await db.query(await fs.readFile(new URL('../../supabase/migrations/012_v3_company_admin.sql',import.meta.url),'utf8'));await db.query("insert into pulso_v3.super_admins(user_id,authorization_reference) values($1,'Disposable QA fixture owner, not production authorization')",[owner.id]);await new Promise(r=>setTimeout(r,1500));assert.equal((await db.query('select count(*)::int n from pulso_v3.responses')).rows[0].n,before);assert.equal((await rpc(root,'v3_bootstrap')).actor.is_super_admin,true);});
 await check('Super Admin creates a separate company admin through actual Edge and Auth',async()=>{const r=await edge(root,{action:'create_access',request_id:randomUUID(),role:'admin',code:'ADMIN-COMPANY',display_name:'Administración de empresa QA'});assert(r.completed&&r.credential?.password);companyCredential=r.credential;await login(company,companyCredential.code,companyCredential.password);const b=await rpc(company,'v3_bootstrap');assert.equal(b.actor.role,'admin');assert.equal(b.actor.is_super_admin,false);});
 await check('Company admin cannot create an admin through old compatible Edge route',()=>assert.rejects(edge(company,{action:'create_access',request_id:randomUUID(),role:'admin',code:'ADMIN-ILLEGAL',display_name:'Forbidden'}),/SUPER_ADMIN_ONLY/));
 await check('Company admin cannot reset owner password through real Edge',()=>assert.rejects(edge(company,{action:'reset_password',user_id:owner.id}),/PROTECTED_ACCOUNT/));
 await check('Company admin cannot disable owner through RPC',()=>assert.rejects(cmd(company,'actor.disable',{id:owner.id},1),/PROTECTED_ACCOUNT/));
 await check('Company admin creates ordinary Viewer through real Edge',async()=>{const r=await edge(company,{action:'create_access',request_id:randomUUID(),role:'viewer',code:'VIEW-COMPANY',display_name:'Viewer de empresa QA'});viewerCredential=r.credential;await login(viewer,r.credential.code,r.credential.password);assert.equal((await rpc(viewer,'v3_bootstrap')).actor.role,'viewer');});
 await check('Authenticated company form writes and reads with audit and revision',async()=>{let b=await rpc(company,'v3_bootstrap');const r=await rpc(company,'v3_company_command',{p_action:'company.save',p_data:{name:'Empresa de prueba HTTP',contact_name:'Responsable de prueba',support_email:'qa@example.invalid',support_phone:'',notes:'INTERNAL_QA_ONLY'},p_expected:b.company.revision,p_request_id:randomUUID()});assert(r.saved);b=await rpc(company,'v3_bootstrap');assert.equal(b.company.name,'Empresa de prueba HTTP');assert.equal(b.company.notes,'INTERNAL_QA_ONLY');});
 await check('Viewer receives only public company contact fields',async()=>{const b=await rpc(viewer,'v3_bootstrap');assert.equal(b.company.notes,undefined);assert.equal(b.company.contact_name,undefined);await assert.rejects(rpc(viewer,'v3_company_command',{p_action:'company.save',p_data:{name:'Forbidden'},p_expected:2,p_request_id:randomUUID()}),/ADMIN_ONLY/);});
 await check('Ordinary admin cannot fake the super flag in company configuration',async()=>{const b=await rpc(company,'v3_bootstrap');await assert.rejects(rpc(company,'v3_company_command',{p_action:'company.save',p_data:{name:'Forbidden',is_super_admin:true},p_expected:b.company.revision,p_request_id:randomUUID()}),/COMPANY_INVALID/);});
 await check('Owner can correct an administrator label without changing identity',async()=>{const b=await rpc(root,'v3_bootstrap'),target=b.actors.find(a=>a.code==='ADMIN-COMPANY');await rpc(root,'v3_company_command',{p_action:'actor.rename',p_data:{id:target.user_id,display_name:'Administración de empresa corregida',reason:'Same person spelling correction QA'},p_expected:target.revision,p_request_id:randomUUID()});assert.equal((await rpc(company,'v3_bootstrap')).actor.display_name,'Administración de empresa corregida');});
 await check('Old true-name publication API remains blocked after module installation',()=>assert.rejects(cmd(company,'viewer.publish',{district_id:'cde'}),/USE_ALIAS_REPORTS/));
 await check('Code-only Viewer results and live feed remain unchanged',async()=>{const prior=JSON.parse(await fs.readFile('/tmp/pulso-live-private.json','utf8')),v=make();await login(v,prior.viewer.code,prior.viewer.password);const b=await rpc(v,'v3_bootstrap'),d=await rpc(v,'v3_dashboard');assert(b.operation.viewer_enabled);assert(d.cities.every(c=>c.schema==='pulso-external-1'));for(const c of d.cities)for(const item of c.candidates||[])assert.equal(item.name,undefined);const live=await rpc(v,'v3_live_board');assert.equal(live.audience,'released');});
 await check('Private super registry cannot be queried from browser credentials',async()=>{assert((await company.schema('pulso_v3').from('super_admins').select('*')).error);});
 await check('Company administrator cannot activate technical V3 through RPC',()=>assert.rejects(rpc(company,'v3_activate',{p_legacy_outbox_handled:true,p_backup_reference:'QA reference, not actual production',p_acceptance_reference:'QA reference, not actual production'}),/SUPER_ADMIN_ONLY/));
 await check('Legacy provision-team service table access is fenced before Auth mutation',async()=>{assert.equal((await db.query("select has_table_privilege('service_role','public.profiles','SELECT') ok")).rows[0].ok,false);});
 await check('Owner disables, rejects existing session, and reactivates a company admin',async()=>{let b=await rpc(root,'v3_bootstrap'),a=b.actors.find(x=>x.code==='ADMIN-COMPANY');await cmd(root,'actor.disable',{id:a.user_id},a.revision);await assert.rejects(rpc(company,'v3_bootstrap'),/ACCOUNT_DISABLED/);b=await rpc(root,'v3_bootstrap');a=b.actors.find(x=>x.user_id===a.user_id);await cmd(root,'actor.enable',{id:a.user_id,reason:'QA owner reactivation'},a.revision);await assert.rejects(rpc(company,'v3_bootstrap'),/SESSION_REQUIRED/);await login(company,companyCredential.code,companyCredential.password);assert((await rpc(company,'v3_bootstrap')).actor.active);});
 await fs.writeFile('/tmp/pulso-company-private.json',JSON.stringify({url:ctx.url,key:ctx.key,admin:{code:ctx.adminMail,password:ctx.adminPassword},company:companyCredential,viewer:viewerCredential}),{mode:0o600});
}catch(e){console.error('Company native verification failed',e.message);if(!checks.some(c=>!c.pass))checks.push({name:'Fixture setup',pass:false,error:String(e.message).slice(0,300)});process.exitCode=1;}finally{await fs.writeFile(new URL('../evidence/company-native.json',import.meta.url),JSON.stringify({scope:'Disposable native Supabase, real Auth/Edge/HTTP; not production or physical hardware',passed:checks.filter(c=>c.pass).length,failed:checks.filter(c=>!c.pass).length,checks},null,2));await db.end();for(const c of clients)await c.realtime.disconnect();}
process.exit(process.exitCode||0);
