/** Delegation SQL regressions. Disposable PGlite; identities are explicit fixtures. */
import {database,as,admin as root,adminSession as rs} from './db-fixture.mjs';
import fs from 'node:fs/promises';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';
const db=await database(),checks=[];
const rpc=async(name,args=[],u=root,s=rs)=>Object.values((await as(db,u,s,`select public.${name}(${args.map((_,i)=>'$'+(i+1)).join(',')}) r`,args))[0])[0];
const save=(o,b,a,rev,u,s,key=randomUUID())=>rpc('v3_company_readiness_save',[o,b,a,rev,key],u,s);
const activate=(rev,u,s,key=randomUUID())=>rpc('v3_company_activate',[rev,key],u,s);
const state=(u=root,s=rs)=>rpc('v3_company_readiness',[],u,s);
async function check(name,fn){try{await fn();checks.push({name,pass:true});console.log('PASS',name);}catch(e){checks.push({name,pass:false,error:e.message});throw e;}}
try{
 for(const f of ['009_v3_reports.sql','010_v3_live_board.sql','011_v3_live_console.sql','012_v3_company_admin.sql'])await db.exec(await fs.readFile(new URL('../../supabase/migrations/'+f,import.meta.url),'utf8'));
 await db.query('insert into pulso_v3.super_admins(user_id,authorization_reference) values($1,$2)',[root,'Explicit synthetic owner fixture only']);
 const ca=randomUUID(),cs=randomUUID(),va=randomUUID(),vs=randomUUID(),co=randomUUID(),cos=randomUUID();
 for(const [u,s,code,role]of[[ca,cs,'ADMIN-HANDOFF','admin'],[va,vs,'VIEW-HANDOFF','viewer'],[co,cos,'COORD-HANDOFF','coordinator']]){
  await db.query('insert into auth.users(id,email,email_confirmed_at) values($1,$2,now())',[u,code+'@example.invalid']);await db.query('insert into auth.sessions values($1,$2)',[s,u]);await db.query('insert into pulso_v3.actors(user_id,code,display_name,role,enrolled) values($1,$2,$2,$3,true)',[u,code,role]);
 }
 const install=await fs.readFile(new URL('../../supabase/V3_1_1_COMPANY_HANDOFF.sql',import.meta.url),'utf8');
 await check('013 installs without activating or fabricating any confirmation',async()=>{await db.exec(install);let d=await state();assert.equal(d.operation_mode,'v2');assert.equal(d.outbox_handled,false);assert.equal(d.ready,false);assert.equal(d.updated_at,null);assert.equal(d.activated_at,null);});
 await check('Super Admin is read-only for company declarations',async()=>{const d=await state();assert.equal(d.can_edit,false);assert.equal(d.backup_reference,null);await assert.rejects(save(false,'','',1,root,rs),/COMPANY_ADMIN_ONLY/);await assert.rejects(activate(1,root,rs),/COMPANY_ADMIN_ONLY/);});
 await check('Ordinary company admin can edit without requesting Super Admin approval',async()=>{assert.equal((await state(ca,cs)).can_edit,true);assert.equal((await save(false,'','',1,ca,cs)).revision,2);assert.equal((await state(ca,cs)).ready,false);});
 await check('Partial company drafts remain pending and do not activate',async()=>{await save(true,'QA backup reference only','',2,ca,cs);const d=await state(ca,cs);assert.equal(d.backup_recorded,true);assert.equal(d.acceptance_recorded,false);assert.equal(d.operation_mode,'v2');await assert.rejects(activate(d.revision,ca,cs),/CONFIRMATIONS_PENDING/);});
 await check('Viewer and coordinator cannot read or submit private readiness',async()=>{for(const[u,s]of[[va,vs],[co,cos]]){await assert.rejects(state(u,s),/ADMIN_ONLY/);await assert.rejects(save(false,'','',3,u,s),/COMPANY_ADMIN_ONLY/);await assert.rejects(activate(3,u,s),/COMPANY_ADMIN_ONLY/);}});
 await check('Anonymous cannot execute readiness RPCs and no role can read draft table directly',async()=>{for(const sig of ['public.v3_company_readiness()','public.v3_company_readiness_save(boolean,text,text,bigint,uuid)','public.v3_company_activate(bigint,uuid)'])assert.equal((await db.query("select has_function_privilege('anon',$1,'EXECUTE') ok",[sig])).rows[0].ok,false);await assert.rejects(as(db,ca,cs,'select * from pulso_v3.company_readiness'),/permission denied/);});
 await check('Stale admin drafts cannot overwrite another version',()=>assert.rejects(save(false,'','',1,ca,cs),/RELOAD_REQUIRED/));
 await check('Draft retry is idempotent and not an additional audit',async()=>{const key=randomUUID(),first=await save(false,'','',3,ca,cs,key),again=await save(false,'','',3,ca,cs,key);assert.equal(again.duplicate,true);assert.equal(again.revision,first.revision);assert.equal((await db.query("select count(*)::int n from pulso_v3.audit where request_id=$1",[key])).rows[0].n,1);await assert.rejects(save(true,'','',3,ca,cs,key),/IDEMPOTENCY_CONFLICT/);});
 await check('Null and oversized values do not become assertions',async()=>{for(const args of [[null,'','',4],[false,null,'',4],[false,'',null,4],[false,'','',null],[false,'x'.repeat(2001),'',4]])await assert.rejects(save(...args,ca,cs),/INVALID_READINESS/);});
 await check('Old activation endpoint cannot bypass new workflow for root or company',async()=>{for(const[u,s]of[[root,rs],[ca,cs]])await assert.rejects(rpc('v3_activate',[true,'Arbitrary typed reference','Arbitrary acceptance reference'],u,s),/USE_COMPANY_CONFIRMATIONS/);});
 await check('Three completed draft values still do not switch mode',async()=>{await save(true,'Synthetic verified backup QA only','Synthetic signed acceptance QA only',4,ca,cs);const d=await state(ca,cs);assert(d.ready);assert.equal(d.operation_mode,'v2');assert.equal(d.updated_by_code,'ADMIN-HANDOFF');});
 await check('Reinstall does not reset company draft or produce owner attestations',async()=>{await db.exec(install);const d=await state(ca,cs);assert.equal(d.revision,5);assert.equal(d.backup_reference,'Synthetic verified backup QA only');assert.equal(d.activated_at,null);});
 await check('Existing Super Admin account protection is unchanged',()=>assert.rejects(rpc('v3_command',['actor.disable',{id:root},randomUUID(),1,30000],ca,cs),/PROTECTED_ACCOUNT/));
 await check('Cutover still blocks legacy actor drift',async()=>{await db.query('update public.profiles set active=false where id=$1',[root]);await assert.rejects(activate(5,ca,cs),/LEGACY_ACTOR_DRIFT/);await db.query('update public.profiles set active=true where id=$1',[root]);});
 await check('Cutover still blocks non-preparation state',async()=>{await db.query("update public.settings set state='open',opened_at=now() where id=1");await db.query("update pulso_v3.operations set phase='paused' where id=1");await assert.rejects(activate(5,ca,cs),/LEGACY_DATA_NEEDS_REVIEW/);await db.query("update pulso_v3.operations set phase='setup' where id=1");await db.query("update public.settings set state='setup',opened_at=NULL where id=1");});
 await check('All installed version gates remain required',async()=>{await db.query('delete from pulso_v3.schema_versions where version=11');await assert.rejects(activate(5,ca,cs),/CONFIRMATIONS_PENDING/);await db.query('insert into pulso_v3.schema_versions(version) values(11)');});
 await check('Final approval checks the current saved revision',()=>assert.rejects(activate(4,ca,cs),/RELOAD_REQUIRED/));
 await check('Company activates once; no survey or point starts; audit attributes company',async()=>{const key=randomUUID(),r=await activate(5,ca,cs,key);assert.equal(r.active,true);assert.equal(r.fieldwork_open,false);assert.equal((await activate(5,ca,cs,key)).duplicate,true);const d=await state();assert.equal(d.operation_mode,'v3');assert.equal(d.activated_by_code,'ADMIN-HANDOFF');assert.equal((await db.query('select phase from pulso_v3.operations where id=1')).rows[0].phase,'setup');const rows=(await db.query("select actor_id,detail from pulso_v3.audit where action='operation.v3_activated'")).rows;assert.equal(rows.length,1);assert.equal(rows[0].actor_id,ca);});
 await check('Drafts are immutable after successful activation and role boundary persists',async()=>{await assert.rejects(save(false,'','',5,ca,cs),/READINESS_ALREADY_ACTIVATED/);await assert.rejects(activate(5,root,rs),/COMPANY_ADMIN_ONLY/);});
 await check('No old API, publication permission, questionnaire or answer was opened by delegation',async()=>{assert.equal((await db.query("select has_function_privilege('authenticated','public.submit_response_v2(jsonb)','EXECUTE') ok")).rows[0].ok,false);assert.equal((await db.query('select count(*)::int n from pulso_v3.responses')).rows[0].n,0);});
}catch(e){console.error('FAIL',e.message);process.exitCode=1;}finally{await fs.mkdir(new URL('../evidence/',import.meta.url),{recursive:true});await fs.writeFile(new URL('../evidence/company-handoff.json',import.meta.url),JSON.stringify({scope:'Disposable PGlite SQL; fixture users; no hosted production mutation',passed:checks.filter(x=>x.pass).length,failed:checks.filter(x=>!x.pass).length,checks},null,2));await db.close();}
