// 013's activation UX has been intentionally retired by the direct-use release.
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {isCompanyAdmin,readinessCard} from '../web/modules/company-readiness.mjs';import {settings,shell} from '../web/modules/views.mjs';
const state=(role='admin',owner=false,mode='v3',d=null)=>({boot:{actor:{role,is_super_admin:owner},operation_mode:mode,operation:{phase:'setup'}},readiness:d});
test('No role sees activation button or declaration fields',()=>{for(const owner of [true,false])for(const mode of ['v2','v3']){const S=state('admin',owner,mode);const h=readinessCard(S)+settings(S);for(const bad of ['name="backup"','name="acceptance"','name="outbox"','data-action="activate"','data-action="company-activate"'])assert(!h.includes(bad));}});
test('Prepared company administrator can continue without filling any declaration',()=>{const h=readinessCard(state());assert.equal(h,'');assert(!h.includes('<form'));assert(!h.includes('confirmar'))});
test('Missing installation read is unknown, not claimed absent or verified',()=>{const h=readinessCard(state('admin',true,'v2'));assert.equal(h,'');assert(!h.includes('Super Admin'))});
test('Owner sees actual installation flags from authenticated readback',()=>{const h=readinessCard(state('admin',true,'v3',{module_013_installed:true,module_014_installed:true}));assert.equal(h,'')});
test('Ordinary roles cannot render private module details',()=>{for(const role of ['viewer','coordinator','interviewer'])assert.equal(readinessCard(state(role)), '');assert(!readinessCard(state()).includes('Módulo 013:'))});
test('Read error is escaped and old references are not inserted in DOM',()=>{const s=state('admin',true);s.readinessError='<script>bad()</script>';s.readiness={backup_reference:'PRIVATE_QA_VALUE'};const h=readinessCard(s);assert.equal(h,'');assert(!h.includes('<script>'));assert(!h.includes('PRIVATE_QA_VALUE'))});
test('No browser handler invokes either activation RPC',()=>{const s=fs.readFileSync(new URL('../web/app.mjs',import.meta.url),'utf8');assert(!s.includes("api.rpc('v3_activate'"));assert(!s.includes("api.rpc('v3_company_activate'"));assert(!s.includes("case 'company-activate'"));assert(s.includes("api.rpc('v3_installation_status'"))});
test('Company role still cannot be inferred from a typed email',()=>{assert(!isCompanyAdmin({actor:{role:'admin',email:'jaimehuang168@gmail.com'}}));assert(isCompanyAdmin(state().boot))});
