/** Real PostgreSQL engine (PGlite); Auth/session rows are explicitly synthetic fixtures. */
import {database,as,admin,adminSession} from './db-fixture.mjs';
import {randomUUID} from 'node:crypto';import assert from 'node:assert/strict';import fs from 'node:fs/promises';
const db=await database(),checks=[];const root=admin,rs=adminSession;
const rpc=async(name,args=[],u=root,s=rs)=>Object.values((await as(db,u,s,`select public.${name}(${args.map((_,i)=>'$'+(i+1)).join(',')}) r`,args))[0])[0];
const cmd=(action,data,expected=0,u=root,s=rs,key=randomUUID())=>rpc('v3_command',[action,data,key,expected],u,s);
const cc=(action,data,expected=0,u=root,s=rs,key=randomUUID())=>rpc('v3_company_command',[action,data,key,expected],u,s);
const revision=async(table,id,key='user_id')=>(await db.query(`select revision from pulso_v3.${table} where ${key}=$1`,[id])).rows[0].revision;
async function test(name,f){try{await f();checks.push({name,pass:true});console.log('PASS',name);}catch(e){checks.push({name,pass:false,error:e.message});throw e;}}
const service=async(step,data)=>{await db.exec('BEGIN;SET LOCAL ROLE service_role');try{const x=(await db.query('select public.v3_access_service($1,$2) r',[step,data])).rows[0].r;await db.exec('COMMIT');return x;}catch(e){await db.exec('ROLLBACK');throw e;}};
try{
 for(const f of ['009_v3_reports.sql','010_v3_live_board.sql','011_v3_live_console.sql'])await db.exec(await fs.readFile(new URL('../../supabase/migrations/'+f,import.meta.url),'utf8'));
 const install=await fs.readFile(new URL('../../supabase/V3_1_COMPANY_UPGRADE.sql',import.meta.url),'utf8');
 await test('Atomic installer rejects missing designated verified owner without partial installation',async()=>{await assert.rejects(db.exec(install),/JAIME_VERIFIED_ADMIN_REQUIRED/);await db.exec('ROLLBACK');assert.equal((await db.query("select to_regclass('pulso_v3.super_admins') x")).rows[0].x,null);});
 await db.query('update auth.users set email=$1 where id=$2',['jaimehuang168@gmail.com',root]);
 await test('Owner installer designates only exact existing confirmed admin and does not activate',async()=>{await db.exec(install);assert.equal((await rpc('v3_bootstrap')).actor.is_super_admin,true);assert.equal((await rpc('v3_preflight')).operation_mode,'v2');});
 await test('Repeat installation is safe and does not duplicate owner audit',async()=>{await db.exec(install);assert.equal((await db.query("select count(*)::int n from pulso_v3.super_admins")).rows[0].n,1);assert.equal((await db.query("select count(*)::int n from pulso_v3.audit where action='governance.super_admin_designated'")).rows[0].n,1);});
 let ca=randomUUID(),cs=randomUUID(),va=randomUUID(),vs=randomUUID(),wa=randomUUID(),ws=randomUUID(),person=randomUUID();
 for(const [u,s,code,role]of [[ca,cs,'ADMIN-TEST','admin'],[va,vs,'VIEW-TEST','viewer']]){await db.query('insert into auth.users(id,email,email_confirmed_at) values($1,$2,now())',[u,code+'@example.invalid']);await db.query('insert into auth.sessions values($1,$2)',[s,u]);await db.query('insert into pulso_v3.actors(user_id,code,display_name,role,enrolled) values($1,$2,$2,$3,true)',[u,code,role]);}
 const newActor=(u,s)=>({actor_id:u,session_id:s,request_id:randomUUID(),code:'ADMIN-'+randomUUID().replaceAll('-','').slice(0,8).toUpperCase(),role:'admin',display_name:'Synthetic new admin'});
 await test('Company admin receives a false super-admin flag',async()=>{const b=await rpc('v3_bootstrap',[],ca,cs);assert.equal(b.actor.is_super_admin,false);assert.equal(b.company_schema_version,12);});
 await test('Legacy provisioning cannot read profiles with service key before cutover',async()=>{assert.equal((await db.query("select has_table_privilege('service_role','public.profiles','SELECT') ok")).rows[0].ok,false);});
 await test('Ordinary admin cannot use previous Edge service path to create admin',()=>assert.rejects(service('prepare',newActor(ca,cs)),/SUPER_ADMIN_ONLY/));
 await test('Root can prepare a new administrative account',async()=>{assert.equal((await service('prepare',newActor(root,rs))).role,'admin');});
 await test('Ordinary admin can prepare a coordinator account',async()=>{const d=newActor(ca,cs);d.role='coordinator';d.code='COORD-TESTNEW';assert.equal((await service('prepare',d)).role,'coordinator');});
 await test('Null account role is rejected explicitly',async()=>{const d=newActor(root,rs);d.role=null;await assert.rejects(service('prepare',d),/INVALID_ACCESS_ACCOUNT/);});
 await test('Lower admin cannot reset root through service path',()=>assert.rejects(service('reset_check',{actor_id:ca,session_id:cs,user_id:root}),/PROTECTED_ACCOUNT/));
 await test('Lower admin cannot reset another admin',()=>assert.rejects(service('reset_check',{actor_id:ca,session_id:cs,user_id:ca}),/SUPER_ADMIN_ONLY/));
 await test('Root can reset company admin',async()=>assert.equal((await service('reset_check',{actor_id:root,session_id:rs,user_id:ca})).user_id,ca));
 await test('Lower admin cannot demote root using legacy command',async()=>{await assert.rejects(cmd('actor.promote',{id:root,role:'viewer',reason:'Unauthorized lower admin demotion'},1,ca,cs),/PROTECTED_ACCOUNT/);});
 await test('Even root cannot disable the protected owner',()=>assert.rejects(cmd('actor.disable',{id:root},1),/PROTECTED_ACCOUNT/));
 await test('Existing field/access identities cannot be promoted to admin',async()=>{await assert.rejects(cmd('actor.promote',{id:va,role:'admin',reason:'Should use a separately provisioned account'},1),/CREATE_ADMIN_SEPARATELY/);});
 await test('Root can disable and reactivate company admin while fencing old sessions',async()=>{await cmd('actor.disable',{id:ca},1);await assert.rejects(rpc('v3_bootstrap',[],ca,cs),/ACCOUNT_DISABLED/);await cmd('actor.enable',{id:ca,reason:'Reactivated by owner after account review'},2);await assert.rejects(rpc('v3_bootstrap',[],ca,cs),/SESSION_REQUIRED/);cs=randomUUID();await db.query('insert into auth.sessions values($1,$2)',[cs,ca]);assert.equal((await rpc('v3_bootstrap',[],ca,cs)).actor.active,true);});
 await test('Ordinary admin cannot activate technical cutover',()=>assert.rejects(rpc('v3_activate',[true,'Synthetic backup reference only','Synthetic testing reference only'],ca,cs),/SUPER_ADMIN_ONLY/));
 const company={name:'Empresa DEMO',contact_name:'Responsable DEMO',support_email:'soporte@example.invalid',support_phone:'',notes:'INTERNAL_ONLY_NOTE'};
 await test('Company admin can save company profile through authenticated RPC',async()=>assert.equal((await cc('company.save',company,1,ca,cs)).revision,2));
 await test('Optimistic version prevents overwriting another administrator',()=>assert.rejects(cc('company.save',company,1),/RELOAD_REQUIRED/));
 await test('Role injection in profile fields is rejected',()=>assert.rejects(cc('company.save',{...company,is_super_admin:true},2),/COMPANY_INVALID/));
 await test('Malformed support address is rejected',()=>assert.rejects(cc('company.save',{...company,support_email:'not-an-email'},2),/COMPANY_INVALID/));
 await test('Company save retries return same receipt without another revision',async()=>{const k=randomUUID(),first=await cc('company.save',company,2,root,rs,k),again=await cc('company.save',company,2,root,rs,k);assert.equal(again.duplicate,true);assert.equal(again.revision,first.revision);});
 await test('Same key with another company payload is refused',async()=>{const k=randomUUID();await cc('company.save',company,3,root,rs,k);await assert.rejects(cc('company.save',{...company,name:'OTHER'},3,root,rs,k),/IDEMPOTENCY_CONFLICT/);});
 await test('Owner designation does not reopen old true-name publication',()=>assert.rejects(cmd('viewer.publish',{district_id:'cde'}),/USE_ALIAS_REPORTS/));
 await test('Private command-before-reports helper remains inaccessible to browser',()=>assert.rejects(as(db,root,rs,"select pulso_v3.command_before_reports('actor.disable','{}',gen_random_uuid())"),/permission denied/));
 await test('Sensitive registry and company table cannot be read or modified directly',async()=>{for(const q of ['select * from pulso_v3.super_admins','delete from pulso_v3.super_admins','select * from pulso_v3.company_profile'])await assert.rejects(as(db,ca,cs,q),/permission denied/);});
 await test('Owner can rename an admin but company admin cannot rename root',async()=>{await cc('actor.rename',{id:ca,display_name:'Administración corregida',reason:'Name spelling correction, same person'},await revision('actors',ca));await assert.rejects(cc('actor.rename',{id:root,display_name:'ATTACK',reason:'Unauthorized administrative name change'},1,ca,cs),/PROTECTED_ACCOUNT/);});
 await test('Owner can activate technical mode without opening fieldwork',async()=>{await rpc('v3_activate',[true,'Isolated QA backup reference only','Isolated QA acceptance reference only']);const b=await rpc('v3_bootstrap');assert.equal(b.operation_mode,'v3');assert.equal(b.operation.phase,'setup');});
 await test('Viewer cannot save company fields and does not receive private notes',async()=>{await assert.rejects(cc('company.save',company,4,va,vs),/ADMIN_ONLY/);const b=await rpc('v3_bootstrap',[],va,vs);assert.equal(b.company.notes,undefined);assert.equal(b.company.name,'Empresa DEMO');});
 await test('Name correction preserves original identity and writes audit',async()=>{const p=(await cmd('person.add',{district_id:'cde',display_name:'Persona DEMO'})).id;const r=await cc('person.rename',{id:p,display_name:'Persona DEMO corregida',reason:'Correction of the same actual person'},1);assert.equal(r.id,p);const n=(await db.query("select count(*)::int n from pulso_v3.audit where action='person.rename' and subject_id=$1",[p])).rows[0].n;assert.equal(n,1);});
 await test('Unknown governance actions and null inputs fail closed',async()=>{for(const a of [null,'set_super_admin','v3_activate'])await assert.rejects(cc(a,{},0),/INVALID_COMMAND/);});
 await test('No synthetic survey response inserted by governance tests',async()=>assert.equal((await db.query('select count(*)::int n from pulso_v3.responses')).rows[0].n,0));
}catch(e){console.error('FAILED',e.message,e.detail||'');process.exitCode=1;}finally{await fs.mkdir(new URL('../evidence/',import.meta.url),{recursive:true});await fs.writeFile(new URL('../evidence/company.json',import.meta.url),JSON.stringify({scope:'PGlite SQL engine; fixture Auth identities, not production',passed:checks.filter(c=>c.pass).length,failed:checks.filter(c=>!c.pass).length,checks},null,2));await db.close();}
