/** Executes the exact owner installer in disposable PostgreSQL/PGlite fixtures. */
import{database,as,admin,adminSession}from'./db-fixture.mjs';import fs from'node:fs/promises';import assert from'node:assert/strict';import{randomUUID}from'node:crypto';
const db=await database(),checks=[];const file=await fs.readFile(new URL('../../supabase/V3_1_DIRECT_USE.sql',import.meta.url),'utf8');
const install=async()=>{try{return await db.exec(file)}catch(e){await db.exec('ROLLBACK');throw e}};
const read=async(sql,args=[])=>(await db.query(sql,args)).rows;
const rpc=async(n,u=admin,s=adminSession)=>Object.values((await as(db,u,s,'select public.'+n+'() r'))[0])[0];
const check=async(n,f)=>{try{await f();checks.push({name:n,pass:true})}catch(e){checks.push({name:n,pass:false,error:e.message});throw e}};
try{
 for(const n of ['009_v3_reports.sql','010_v3_live_board.sql','011_v3_live_console.sql','012_v3_company_admin.sql'])await db.exec(await fs.readFile(new URL('../../supabase/migrations/'+n,import.meta.url),'utf8'));
 await db.query('insert into pulso_v3.super_admins(user_id,authorization_reference) values($1,$2)',[admin,'Synthetic fixture, not production authorization']);
 await check('Wrong designated owner aborts before installing 013 or switching mode',async()=>{await assert.rejects(install(),/DESIGNATED_OWNER_REQUIRED/);assert.equal((await read("select to_regclass('pulso_v3.company_readiness') x"))[0].x,null);});
 await db.query("update auth.users set email='jaimehuang168@gmail.com' where id=$1",[admin]);
 await check('Legacy account drift aborts the entire automatic 013 plus 014 transaction',async()=>{await db.query('update public.profiles set active=false where id=$1',[admin]);await assert.rejects(install(),/LEGACY_ACTOR_DRIFT/);assert.equal((await read("select to_regclass('pulso_v3.company_readiness') x"))[0].x,null);await db.query('update public.profiles set active=true where id=$1',[admin]);});
 await check('Non-preparation state is refused without resetting it',async()=>{await db.exec("update pulso_v3.operations set phase='paused' where id=1");await assert.rejects(install(),/LEGACY_DATA_NEEDS_REVIEW/);assert.equal((await read('select phase from pulso_v3.operations'))[0].phase,'paused');await db.exec("update pulso_v3.operations set phase='setup' where id=1");});
 await check('Missing baseline aborts atomically',async()=>{await db.exec('delete from pulso_v3.schema_versions where version=11');await assert.rejects(install(),/BASELINE_REQUIRED/);await db.exec('insert into pulso_v3.schema_versions(version) values(11)');});
 const date=(await read('select fieldwork_date from pulso_v3.operations'))[0].fieldwork_date;
 await check('Exact owner installer adds 013 and 014 with no activation RPC',async()=>{await install();const d=await rpc('v3_installation_status');assert(d.module_013_installed&&d.module_014_installed);assert.equal(d.operation_mode,'v3');assert.equal(d.activation_required,false)});
 await check('Company declarations remain false/blank/unattributed',async()=>{const d=(await read('select * from pulso_v3.company_readiness'))[0];assert.equal(d.outbox_handled,false);assert.equal(d.backup_reference,'');assert.equal(d.acceptance_reference,'');assert.equal(d.activated_at,null);assert.equal(d.activated_by,null)});
 await check('Installation does not fabricate backup or phone acceptance',async()=>{assert.equal((await read('select backup_verified_at from pulso_v3.operations'))[0].backup_verified_at,null);assert.equal((await read("select count(*)::int n from pulso_v3.audit where action='operation.v3_activated'"))[0].n,0)});
 await check('Server responses stay empty and election date unchanged',async()=>{for(const t of ['public.responses','pulso_v3.responses'])assert.equal((await read('select count(*)::int n from '+t))[0].n,0);assert.deepEqual((await read('select fieldwork_date from pulso_v3.operations'))[0].fieldwork_date,date)});
 await check('Collection and publication remain closed',async()=>{const d=(await read('select phase,viewer_enabled from pulso_v3.operations'))[0];assert.equal(d.phase,'setup');assert.equal(d.viewer_enabled,false);assert.equal((await read("select count(*)::int n from pulso_v3.points where state='open'"))[0].n,0)});
 await check('Old activation endpoints are inaccessible for all API roles',async()=>{for(const role of ['anon','authenticated','service_role'])for(const sig of ['public.v3_activate(boolean,text,text)','public.v3_company_activate(bigint,uuid)'])assert.equal((await read('select has_function_privilege($1,$2,\'EXECUTE\') ok',[role,sig]))[0].ok,false)});
 await check('Legacy V2 tables and functions are closed, not deleted',async()=>{assert.equal((await read("select has_function_privilege('authenticated','public.submit_response_v2(jsonb)','EXECUTE') ok"))[0].ok,false);assert.equal((await read("select has_table_privilege('service_role','public.profiles','SELECT') ok"))[0].ok,false);assert((await read('select count(*)::int n from public.profiles'))[0].n>0)});
 await check('Repeat installation preserves revision and single deployment audit',async()=>{const before=(await read('select revision from pulso_v3.operations'))[0].revision;await install();assert.deepEqual((await read('select revision from pulso_v3.operations'))[0].revision,before);assert.equal((await read("select count(*)::int n from pulso_v3.audit where action='deployment.direct_use_installed'"))[0].n,1)});
 await check('Existing optional company notes are not erased on reinstall',async()=>{await db.exec("update pulso_v3.company_readiness set backup_reference='Real reference placeholder in test fixture' where id=1");await install();assert.equal((await read('select backup_reference from pulso_v3.company_readiness'))[0].backup_reference,'Real reference placeholder in test fixture')});
 const ca=randomUUID(),cs=randomUUID();await db.query('insert into auth.users(id,email,email_confirmed_at) values($1,$2,now())',[ca,'company@fixture.invalid']);await db.query('insert into auth.sessions values($1,$2)',[cs,ca]);await db.query("insert into pulso_v3.actors(user_id,code,display_name,role,enrolled) values($1,'ADMIN-DIRECT','Company fixture','admin',true)",[ca]);
 await check('Company logs in and reads V3 with no declaration/activation step',async()=>{const d=await rpc('v3_bootstrap',ca,cs);assert.equal(d.operation_mode,'v3');assert.equal(d.actor.is_super_admin,false);assert.equal((await rpc('v3_installation_status',ca,cs)).activation_required,false)});
 await check('Company can edit its own data immediately',async()=>{const b=await rpc('v3_bootstrap',ca,cs);await as(db,ca,cs,'select public.v3_company_command($1,$2,$3,$4)',['company.save',{name:'Direct use QA company'},randomUUID(),b.company.revision]);assert.equal((await rpc('v3_bootstrap',ca,cs)).company.name,'Direct use QA company')});
 await check('Company cannot disable protected Super Admin',async()=>{await assert.rejects(as(db,ca,cs,'select public.v3_command($1,$2,$3,$4,$5)',['actor.disable',{id:admin},randomUUID(),1,30000]),/PROTECTED_ACCOUNT/)});
 await check('Private state retains RLS and anonymous cannot read status',async()=>{assert.equal((await read("select has_function_privilege('anon','public.v3_installation_status()','EXECUTE') ok"))[0].ok,false);assert.equal((await read("select count(*)::int n from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='pulso_v3' and c.relkind='r' and not c.relrowsecurity"))[0].n,0)});
 await check('Company state reader exposes no keys, answers, evidence or names',async()=>{const d=await rpc('v3_installation_status',ca,cs);assert.deepEqual(Object.keys(d).sort(),['activation_required','app_version','fieldwork_phase','module_013_installed','module_014_installed','operation_mode'].sort())});
}catch(e){console.error(e);process.exitCode=1}finally{await fs.mkdir(new URL('../evidence/',import.meta.url),{recursive:true});await fs.writeFile(new URL('../evidence/direct-use-sql.json',import.meta.url),JSON.stringify({scope:'Exact owner installer in disposable SQL fixtures; not a hosted 013 audit',passed:checks.filter(x=>x.pass).length,failed:checks.filter(x=>!x.pass).length,checks},null,2));await db.close()}
