import {database,as,admin,adminSession} from './db-fixture.mjs';import {randomUUID,createHash} from 'node:crypto';import assert from 'node:assert/strict';import fs from 'node:fs/promises';
const db=await database(),results=[];const hash=s=>createHash('sha256').update(s).digest('hex');
const cmd=async(a,d,r=0)=>Object.values((await as(db,admin,adminSession,'select public.v3_command($1,$2,$3,$4)',[a,d,randomUUID(),r]))[0])[0];
const service=async(fn,step,data)=>{await db.exec('BEGIN;SET LOCAL ROLE service_role;');try{const result=(await db.query(`select public.${fn}($1,$2) r`,[step,data])).rows[0].r;await db.exec('COMMIT');return result;}catch(e){await db.exec('ROLLBACK');throw e;}};
async function test(name,f){try{await f();results.push({name,pass:true});console.log('PASS',name);}catch(e){results.push({name,pass:false,error:e.message,where:e.where});console.log('FAIL',name,e.message,e.where);throw e;}}
const call=(step,data)=>service('v3_enrollment_service',step,data);let person,point,invite,authid=randomUUID(),ss=randomUUID();const tk=hash('token synthetic'),claim=hash('claim synthetic'),lock=randomUUID();const shared={token_hash:tk,claim_hash:claim,lock_id:lock};
try{
const site=(await cmd('station.save',{district_id:'cde',code:'QA-SITE',name:'Centro sintético',address:'Calle sintética 10'})).id;point=(await cmd('point.save',{station_id:site,code:'QA-POINT',label:'Acceso QA'})).id;person=(await cmd('person.add',{district_id:'cde',point_id:point,display_name:'Persona invitada QA'})).id;
await test('Issue single-person hashed invitation',async()=>{invite=await call('issue',{actor_id:admin,session_id:adminSession,person_id:person,point_id:point,token_hash:tk,request_id:randomUUID()});assert(invite.id);assert.equal(invite.token,undefined);});
await test('Bogus token cannot retrieve identity',async()=>{await assert.rejects(call('claim',{...shared,token_hash:hash('wrong')}),/INVITE_UNAVAILABLE/);});
let state;await test('One claimant acquires saga',async()=>{state=await call('claim',shared);assert.equal(state.person_id,person);assert.equal(state.auth_user_id,null);});
await test('Second claimant denied even before Auth creation',async()=>{await assert.rejects(call('claim',{...shared,claim_hash:hash('other')}),/INVITE_ALREADY_CLAIMED/);});
await test('Concurrent processor of same claimant gets lease conflict',async()=>{await assert.rejects(call('claim',{...shared,lock_id:randomUUID()}),/ENROLLMENT_BUSY/);});
await test('Auth id must have server-owned person marker',async()=>{await db.query('insert into auth.users(id,email,raw_app_meta_data) values($1,$2,$3)',[authid,state.email,{}]);await assert.rejects(call('auth_record',{...shared,auth_user_id:authid}),/AUTH_ID_MISMATCH/);await db.query('update auth.users set raw_app_meta_data=$1 where id=$2',[{pulso_v3_person:person},authid]);await call('auth_record',{...shared,auth_user_id:authid});});
await test('Profile ready cannot grant admin privilege',async()=>{await call('ready',shared);const actor=(await db.query('select * from pulso_v3.actors where user_id=$1',[authid])).rows[0];assert.equal(actor.role,'interviewer');assert.equal(actor.enrolled,false);const link=await call('native_link',shared);assert.equal(link.enrollment_id,invite.id);});
await db.query('insert into auth.sessions values($1,$2)',[ss,authid]);
await test('Completion requires the exact authenticated claimant',async()=>{await assert.rejects(as(db,admin,adminSession,'select public.v3_enrollment_complete($1)',[invite.id]),/CLAIM_IDENTITY_MISMATCH/);const r=await as(db,authid,ss,'select public.v3_enrollment_complete($1) r',[invite.id]);assert(r[0].r.completed);});
await test('Completed invite cannot mint another native token',async()=>{await assert.rejects(call('native_link',shared),/INVITE_UNAVAILABLE/);});
await test('Reusing completed person is not a second person',async()=>{await assert.rejects(call('issue',{actor_id:admin,session_id:adminSession,person_id:person,point_id:point,token_hash:hash('new'),request_id:randomUUID()}),/ALREADY_ENROLLED/);});
await test('Unauthenticated SQL clients cannot use service endpoints',async()=>{await assert.rejects(as(db,authid,ss,'select public.v3_enrollment_service($1,$2)',['issue',{}]),/permission denied/);});
const req=randomUUID(),au=randomUUID(),args={actor_id:admin,session_id:adminSession,request_id:req,code:'COORD-QATEST',display_name:'Coordinador QA',role:'coordinator'};
await test('Privileged creation saga verifies fixed role and marked Auth identity',async()=>{const s=await service('v3_access_service','prepare',args);await db.query('insert into auth.users(id,email,raw_app_meta_data) values($1,$2,$3)',[au,s.email,{pulso_v3_access_request:req}]);await service('v3_access_service','complete',{...args,auth_user_id:au});const a=(await db.query('select * from pulso_v3.actors where user_id=$1',[au])).rows[0];assert.equal(a.role,'coordinator');await assert.rejects(service('v3_access_service','prepare',{...args,role:'admin'}),/IDEMPOTENCY_CONFLICT/);});
await test('Service checks real session record, not caller user-id only',async()=>{await assert.rejects(service('v3_access_service','prepare',{...args,session_id:randomUUID()}),/SESSION_REQUIRED/);});
await test('Reset revokes retained sessions, without deleting survey records',async()=>{await service('v3_access_service','reset_finish',{actor_id:admin,session_id:adminSession,user_id:authid});await assert.rejects(as(db,authid,ss,'select public.v3_bootstrap()'),/SESSION_REQUIRED/);});
await test('Rate budget denial persists its counter',async()=>{for(let i=1;i<=17;i++){await db.exec('BEGIN;SET LOCAL ROLE service_role;');const r=(await db.query("select public.v3_request_budget('join_token',$1) ok",[hash('rate fixture')])).rows[0];await db.exec('COMMIT');assert.equal(r.ok,i<=15);}const n=(await db.query('select attempts from pulso_v3.rate_limits where bucket=$1',['join_token:'+hash('rate fixture')])).rows[0].attempts;assert.equal(n,17);});
}catch{process.exitCode=1;}await fs.mkdir(new URL('../evidence/',import.meta.url),{recursive:true});await fs.writeFile(new URL('../evidence/enrollment.json',import.meta.url),JSON.stringify({engine:'PGlite, simulated Auth records; does NOT verify native generateLink or verifyOtp',passed:results.filter(r=>r.pass).length,failed:results.filter(r=>!r.pass).length,results},null,2));await db.close();
