/** PGlite actual SQL with synthetic Auth sessions. Never a hosted project. */
import {database,as,admin,adminSession} from './db-fixture.mjs';import fs from 'node:fs/promises';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {validate,CITIES,exportCSV,exportSVG} from '../live/core.mjs';
const db=await database(),results=[],forbidden=[];
const rpc=(name,args=[],u=admin,s=adminSession)=>as(db,u,s,`select public.${name}(${args.map((_,i)=>'$'+(i+1)).join(',')}) r`,args).then(x=>x[0].r);
const cmd=(name,data,rev=0)=>rpc('v3_command',[name,data,randomUUID(),rev]);
const revision=async(t,id)=>(await db.query(`select revision from pulso_v3.${t} where id=$1`,[id])).rows[0].revision;
async function test(name,f){try{await f();results.push({name,pass:true});console.log('PASS',name);}catch(e){results.push({name,pass:false,error:e.message});throw e;}}
const fixtures=[],viewer=randomUUID(),vs=randomUUID(),co=randomUUID(),cs=randomUUID();
const event=(f,index=0,outcome='candidate')=>({id:randomUUID(),assignment_id:f.task,grant_id:f.pack.grant.id,point_id:f.point,questionnaire_id:f.q,started_at:new Date().toISOString(),captured_at:new Date().toISOString(),outcome,candidate_id:outcome==='candidate'?f.items[index].id:null,consent:outcome!=='refused',already_voted:true,geo:{status:'not_requested'}});
const send=(f,index=0,outcome='candidate')=>rpc('v3_submit_response',[event(f,index,outcome)],f.user,f.session);
const leak=value=>{const s=typeof value==='string'?value:JSON.stringify(value);for(const word of forbidden)assert(!s.includes(word),'Private field in projection');};
try{
 await db.exec(await fs.readFile(new URL('../../supabase/migrations/009_v3_reports.sql',import.meta.url),'utf8'));
 const migration=await fs.readFile(new URL('../../supabase/migrations/010_v3_live_board.sql',import.meta.url),'utf8');
 await test('Live installation is repeatable and never opens collection',async()=>{await db.exec(migration);await db.exec(migration);assert.equal((await db.query('select operation_mode from public.settings')).rows[0].operation_mode,'v2');assert.equal((await db.query('select phase from pulso_v3.operations')).rows[0].phase,'setup');});
 await test('Zero-data four-city panel does not invent zero-vote results',async()=>{const r=validate(await rpc('v3_live_board',['internal']));assert.equal(r.cities.length,4);assert(r.cities.every(c=>c.state==='catalog_pending'&&c.counts===null&&c.candidates.length===0));});
 await test('Anonymous direct calls and private release tables are not readable',async()=>{await db.exec('begin;set local role anon');try{await assert.rejects(db.query("select public.v3_live_board('codes')"),/permission denied/);}finally{await db.exec('rollback');}await assert.rejects(as(db,admin,adminSession,'select * from pulso_v3.live_releases'),/permission denied/);});
 await rpc('v3_activate',[true,'Synthetic backup reference','Synthetic acceptance reference']);
 const today=(await db.query("select (now() at time zone 'America/Asuncion')::date::text d")).rows[0].d;
 await cmd('operation.save',{title:'Synthetic live exercise',contest:'Intendencia municipal',fieldwork_date:today,retention_policy:'Synthetic only, no real votes'},await revision('operations',1));
 for(const[i,c]of CITIES.entries()){
  const f={...c,user:randomUUID(),session:randomUUID()};
  f.station=(await cmd('station.save',{district_id:c.id,code:'L-S-'+i,name:'Centro SINTÉTICO '+i,address:'Dirección de pruebas '+i+' sin datos reales'})).id;
  f.point=(await cmd('point.save',{station_id:f.station,code:'L-P-'+i,label:'Punto SINTÉTICO '+i})).id;await cmd('point.approve',{id:f.point,verified:true,reason:'Synthetic approval for live testing'},1);
  f.items=Array.from({length:i%2?4:2},(_,j)=>({id:randomUUID(),name:'Candidatura SINTÉTICA '+i+' '+String.fromCharCode(65+j),list:'Lista PRIVADA '+(j+1)}));
  f.q=(await cmd('questionnaire.save',{district_id:c.id,contest:'Intendencia municipal',methodology:'Synthetic every-fifth-visitor fixture; no actual investigation.',sample_interval:5,reference:'Synthetic live source',items:f.items})).id;
  await cmd('questionnaire.publish',{id:f.q,confirmed:true},1);
  f.person=(await cmd('person.add',{district_id:c.id,point_id:f.point,display_name:'Persona de pruebas '+i})).id;
  await db.query('insert into auth.users(id,email) values($1,$2)',[f.user,'worker'+i+'@example.invalid']);await db.query('insert into auth.sessions values($1,$2)',[f.session,f.user]);
  await db.query("insert into pulso_v3.actors(user_id,code,display_name,role,person_id,enrolled) values($1,$2,$2,'interviewer',$3,true)",[f.user,'LIVE-EN-'+i,f.person]);
  await rpc('v3_training',[['after_voting','voluntary','pending_not_received'],true],f.user,f.session);await cmd('person.approve',{id:f.person,reason:'Synthetic supervisor approval'},2);
  f.task=(await cmd('assignment.create',{person_id:f.person,point_id:f.point,reason:'Synthetic live task'})).id;await rpc('v3_ack_assignment',[f.task,1,f.q,f.point],f.user,f.session);
  fixtures.push(f);forbidden.push(f.q,f.person,f.point,f.station,...f.items.flatMap(x=>[x.id,x.name,x.list]));
 }
 await test('Real-name admin display is available before collection has started',async()=>{const r=validate(await rpc('v3_live_board',['internal']));assert(r.cities.every(c=>c.state==='no_data'));assert.equal(r.cities[0].candidates[0].real_name,fixtures[0].items[0].name);});
 await test('Missing aliases never fall back to real names on code screens',async()=>{const r=validate(await rpc('v3_live_board',['codes']));assert(r.cities.every(c=>c.state==='codes_pending'));leak(r);});
 for(const f of fixtures)await rpc('v3_report_alias_save',[f.q,f.items.map((c,j)=>({candidate_id:c.id,code:f.code+'-'+String.fromCharCode(65+j)})),0,true]);
 await cmd('operation.state',{state:'running',reason:'Synthetic live running state'},await revision('operations',1));
 for(const f of fixtures){await cmd('point.state',{id:f.point,state:'open',reason:'Synthetic live point opening'},2);f.pack=await rpc('v3_start_task',[f.task,randomUUID()],f.user,f.session);for(let j=0;j<f.items.length;j++)for(let n=0;n<12;n++)await send(f,j);await send(f,0,'blank');}
 await test('Live counts update while polls remain open without creating a cut',async()=>{const f=fixtures[0],before=validate(await rpc('v3_live_board',['codes','cde']));const cuts=(await db.query('select count(*) n from pulso_v3.report_cuts')).rows[0].n;await send(f);const after=validate(await rpc('v3_live_board',['codes','cde']));assert.equal(after.cities[0].counts.candidate_base,before.cities[0].counts.candidate_base+1);assert.equal((await db.query('select count(*) n from pulso_v3.report_cuts')).rows[0].n,cuts);assert.equal((await db.query('select phase from pulso_v3.operations')).rows[0].phase,'running');});
 await test('Four cities have separate denominators and a single server cutoff',async()=>{const r=validate(await rpc('v3_live_board',['codes']));assert.deepEqual(r.cities.map(c=>c.counts.candidate_base),[25,48,24,48]);assert(r.cities.every(c=>Date.parse(c.last_received)<=Date.parse(r.server_time)));});
 await test('A single-city query does not return other cities',async()=>{const r=validate(await rpc('v3_live_board',['internal','minga']));assert.deepEqual(r.cities.map(c=>c.id),['minga']);assert.equal(r.cities[0].candidates.length,4);});
 await test('Code JSON CSV SVG contain no private identities or names',async()=>{const r=validate(await rpc('v3_live_board',['codes']));leak(r);leak(exportCSV(r,'all'));leak(exportSVG(r,'all'));assert(!JSON.stringify(r).includes('candidate_id'));assert(!exportCSV(r,'all').includes('Nombre interno'));});
 await test('Invalid audience and district fail closed',async()=>{for(const mode of[null,'INTERNAL','raw'])await assert.rejects(rpc('v3_live_board',[mode]),/BAD_AUDIENCE/);await assert.rejects(rpc('v3_live_board',['codes','not-a-city']),/SCOPE_DENIED/);});
 for(const[u,s,code,role]of[[viewer,vs,'VIEW-LIVE','viewer'],[co,cs,'COORD-LIVE','coordinator']]){await db.query('insert into auth.users(id,email) values($1,$2)',[u,code+'@example.invalid']);await db.query('insert into auth.sessions values($1,$2)',[s,u]);await db.query('insert into pulso_v3.actors(user_id,code,display_name,role,enrolled) values($1,$2,$2,$3,true)',[u,code,role]);}
 await cmd('grant.save',{user_id:viewer,district_id:'cde',capabilities:['view_results'],valid_until:new Date(Date.now()+86400000).toISOString()});
 await test('Interviewer and coordinator cannot open result displays',async()=>{for(const[u,s]of[[co,cs],[fixtures[0].user,fixtures[0].session]])for(const mode of['auto','internal','codes','released'])await assert.rejects(rpc('v3_live_board',[mode],u,s),/SCOPE_DENIED/);});
 await test('Viewer cannot get private names or private code previews',async()=>{for(const mode of['internal','codes'])await assert.rejects(rpc('v3_live_board',[mode],viewer,vs),/ADMIN_ONLY/);await assert.rejects(rpc('v3_live_board',['auto'],viewer,vs),/VIEWER_RESULTS_PENDING/);});
 await cmd('viewer.access',{enabled:true,reason:'Synthetic live viewer test'},await revision('operations',1));
 await test('Viewer sees only own city and withholding without live authorization',async()=>{const r=validate(await rpc('v3_live_board',['auto'],viewer,vs));assert.equal(r.audience,'released');assert.deepEqual(r.cities.map(c=>c.id),['cde']);assert.equal(r.cities[0].state,'withheld');leak(r);});
 await test('Future release policy cannot be bypassed by live authorization',async()=>{await rpc('v3_report_policy_save',[true,new Date(Date.now()+3600000).toISOString(),'Synthetic future release reference',1]);await assert.rejects(rpc('v3_live_authorize',['cde',true,new Date(Date.now()+7200000).toISOString(),'Synthetic independent feed authorization',true]),/RELEASE_BLOCKED/);});
 await rpc('v3_report_policy_save',[true,new Date(Date.now()-60000).toISOString(),'Synthetic active policy reference',2]);
 await test('Frozen cut does not silently authorize continuous feed',async()=>{const cut=(await rpc('v3_report_create',[fixtures[0].q,null,randomUUID()])).id;await rpc('v3_report_release',[cut,true,'Synthetic frozen cut approval']);assert.equal((await rpc('v3_live_board',['auto'],viewer,vs)).cities[0].state,'withheld');});
 await test('NULL consent and expired or missing expiry fail closed',async()=>{for(const[expiry,confirm]of[[null,true],[new Date(Date.now()-1000).toISOString(),true],[new Date(Date.now()+3600000).toISOString(),null]])await assert.rejects(rpc('v3_live_authorize',['cde',true,expiry,'Synthetic validity regression',confirm]),/RELEASE_BLOCKED|AUTHORIZATION_REQUIRED/);});
 await rpc('v3_live_authorize',['cde',true,new Date(Date.now()+3600000).toISOString(),'Synthetic explicit continuous authorization',true]);
 await test('Authorized Viewer feed updates current counts with codes only',async()=>{const a=validate(await rpc('v3_live_board',['auto'],viewer,vs));assert.equal(a.cities[0].state,'live');assert.equal(a.private,false);await send(fixtures[0]);const b=validate(await rpc('v3_live_board',['auto'],viewer,vs));assert.equal(b.cities[0].counts.candidate_base,a.cities[0].counts.candidate_base+1);assert.deepEqual(Object.keys(b.cities[0].counts),['candidate_base']);leak(b);});
 await test('Server validity is bounded by actual authorization expiry',async()=>{const until=new Date(Date.now()+9000).toISOString();await rpc('v3_live_authorize',['cde',true,until,'Synthetic short continuous authorization',true]);const r=validate(await rpc('v3_live_board',['auto'],viewer,vs));assert(Date.parse(r.valid_until)<=Date.parse(until));await rpc('v3_live_authorize',['cde',true,new Date(Date.now()+3600000).toISOString(),'Synthetic normal expiry restored',true]);});
 await test('Viewer cross-city query and self-authorization refused',async()=>{await assert.rejects(rpc('v3_live_board',['auto','minga'],viewer,vs),/SCOPE_DENIED/);await assert.rejects(rpc('v3_live_authorize',['cde',false,null,'Synthetic revoke attempt',true],viewer,vs),/ADMIN_ONLY/);});
 await test('Excluded answers leave numerator without changing historical answers',async()=>{const f=fixtures[0],r=await send(f),before=(await rpc('v3_live_board',['internal','cde'])).cities[0];await rpc('v3_void_own',[r.response_id,'capture_error'],f.user,f.session);const after=(await rpc('v3_live_board',['internal','cde'])).cities[0];assert.equal(after.counts.candidate_base,before.counts.candidate_base-1);assert.equal(after.counts.received,before.counts.received);assert.equal(after.counts.excluded,before.counts.excluded+1);});
 await test('Mapping change invalidates continuous authorization by version',async()=>{const f=fixtures[0];await rpc('v3_report_alias_save',[f.q,f.items.map((c,j)=>({candidate_id:c.id,code:'N-'+String.fromCharCode(65+j)})),1,true]);assert.equal((await rpc('v3_live_board',['auto'],viewer,vs)).cities[0].state,'withheld');});
 await rpc('v3_live_authorize',['cde',true,new Date(Date.now()+3600000).toISOString(),'Synthetic reauthorization after alias revision',true]);
 await test('Revoking a channel does not stop the survey',async()=>{await rpc('v3_live_authorize',['cde',false,null,'Synthetic immediate live withdrawal',true]);assert.equal((await rpc('v3_live_board',['auto'],viewer,vs)).cities[0].state,'withheld');assert.equal((await db.query('select phase from pulso_v3.operations')).rows[0].phase,'running');});
 await test('New questionnaire version cannot inherit earlier counts',async()=>{const f=fixtures[0],q=(await cmd('questionnaire.save',{district_id:'cde',contest:'Intendencia municipal',methodology:'Synthetic new version test only; every fifth person.',sample_interval:5,reference:'Synthetic replacement reference',items:f.items})).id;await cmd('questionnaire.publish',{id:q,confirmed:true},1);const r=validate(await rpc('v3_live_board',['internal','cde']));assert.equal(r.cities[0].state,'no_data');assert.equal(r.cities[0].counts.candidate_base,0);assert(r.cities[0].questionnaire_version>1);assert.equal((await rpc('v3_live_board',['codes','cde'])).cities[0].state,'codes_pending');});
 await test('Disabled accounts cannot use their retained session',async()=>{await cmd('actor.disable',{id:viewer},1);await assert.rejects(rpc('v3_live_board',['auto'],viewer,vs),/ACCOUNT_DISABLED/);});
}catch(e){console.error('LIVE SQL FAIL',e.message);process.exitCode=1;}
finally{await fs.mkdir(new URL('../evidence/',import.meta.url),{recursive:true});await fs.writeFile(new URL('../evidence/live-sql.json',import.meta.url),JSON.stringify({scope:'PGlite actual SQL/receipt RPC; synthetic Auth identities; not hosted or HTTP authentication',passed:results.filter(r=>r.pass).length,failed:results.filter(r=>!r.pass).length,results},null,2));await db.close();}
