/** Real Auth, PostgREST and report/live APIs on the disposable CI backend. Never hosted. */
import fs from 'node:fs/promises';import assert from 'node:assert/strict';import{randomUUID,randomBytes}from'node:crypto';import pg from'pg';import{createClient}from'@supabase/supabase-js';
import{validate}from'../live/core.mjs';
const ctx=JSON.parse(await fs.readFile('/tmp/pulso-v3-local-context.json','utf8')),prior=JSON.parse(await fs.readFile('/tmp/pulso-v3-browser-private.json','utf8'));
if(!/^http:\/\/127\.0\.0\.1:/.test(ctx.url)||new URL(ctx.dbUrl).hostname!=='127.0.0.1')throw Error('Disposable localhost required');
const db=new pg.Client({connectionString:ctx.dbUrl,statement_timeout:30000});await db.connect();const results=[],clients=[],out=new URL('../evidence/',import.meta.url);
const client=()=>{const c=createClient(ctx.url,ctx.key,{auth:{persistSession:false,autoRefreshToken:false}});clients.push(c);return c;},admin=client(),anon=client();
const rpc=async(c,name,args={})=>{const r=await c.rpc(name,args).abortSignal(AbortSignal.timeout(20000));if(r.error)throw Object.assign(Error(r.error.message),r.error,{status:r.status});return r.data;};
const cmd=(action,data,revision=0)=>rpc(admin,'v3_command',{p_action:action,p_data:data,p_expected:revision,p_request_id:randomUUID(),p_client:30000});
const edge=async(body,c=admin)=>{const sess=c?(await c.auth.getSession()).data.session:null;const r=await fetch(ctx.url+'/functions/v1/field-enrollment',{method:'POST',headers:{Origin:'http://127.0.0.1:8044',apikey:ctx.key,'Content-Type':'application/json',...(sess?{Authorization:'Bearer '+sess.access_token}:{})},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw Error(data.error);return data;};
const check=async(name,f)=>{try{await f();results.push({name,pass:true});console.log('PASS',name);}catch(e){results.push({name,pass:false,error:String(e.message).slice(0,400)});throw e;}};
let viewer,viewerAll,viewerAllPassword,workerBrowser,cut,configs=[],state;
try{
 const login=await admin.auth.signInWithPassword({email:ctx.adminMail,password:ctx.adminPassword});if(login.error)throw login.error;
 await check('Install 009, 010 and 011 on real PostgreSQL without changing answers',async()=>{const before=(await db.query('select count(*) n from pulso_v3.responses')).rows[0].n;for(const file of['009_v3_reports.sql','010_v3_live_board.sql','011_v3_live_console.sql'])await db.query(await fs.readFile(new URL('../../supabase/migrations/'+file,import.meta.url),'utf8'));await new Promise(r=>setTimeout(r,1200));assert.equal((await db.query('select count(*) n from pulso_v3.responses')).rows[0].n,before);});
 await check('Native admin state is authorized and exposes four independent cities',async()=>{state=await rpc(admin,'v3_live_admin_state');assert.equal(state.cities.length,4);await assert.rejects(rpc(anon,'v3_live_admin_state'));});
 await check('Internal totals are available while operation is running, not only after closure',async()=>{assert.equal(state.operation.phase,'running');const d=validate(await rpc(admin,'v3_live_board',{p_audience:'internal'}));assert(d.cities[0].counts.candidate_base>100);assert(d.cities[0].candidates[0].real_name);});
 await check('No confirmed aliases means no names in codes-only projection',async()=>{const d=validate(await rpc(admin,'v3_live_board',{p_audience:'codes'}));assert.equal(d.cities[0].state,'codes_pending');assert(!JSON.stringify(d).includes('Candidatura DEMO'));});
 for(const [city,count]of[['cde',2],['minga',4],['hernandarias',2],['franco',4]]){
  let point,q;if(city==='cde'){point=ctx.point;q=ctx.q;}else{
   const st=(await cmd('station.save',{district_id:city,code:'LIVE-S-'+city.toUpperCase(),name:'Centro sintético '+city,address:'Dirección sintética 2026'})).id;
   point=(await cmd('point.save',{station_id:st,code:'LIVE-P-'+city.toUpperCase(),label:'Acceso sintético'})).id;await cmd('point.approve',{id:point,verified:true,reason:'Native isolated location approval'},1);
   q=(await cmd('questionnaire.save',{district_id:city,contest:'Intendencia municipal',methodology:'Every fifth exiting participant; synthetic integration data',sample_interval:5,reference:'Synthetic native catalogue only',items:Array.from({length:count},(_,i)=>({id:randomUUID(),name:'Candidatura FICTICIA '+city+' '+String.fromCharCode(65+i),list:'Lista DEMO '+i}))})).id;await cmd('questionnaire.publish',{id:q,confirmed:true},1);
  }
  await check('Native field enrollment and task preparation '+city,async()=>{
   const person=(await cmd('person.add',{district_id:city,point_id:point,display_name:'Persona sintética '+city})).id;
   const invite=await edge({action:'issue',person_id:person,point_id:point,request_id:randomUUID()}),claim=await edge({action:'claim',token:invite.token,claim_secret:randomBytes(32).toString('base64url'),lock_id:randomUUID()},null),w=client();
   const verified=await w.auth.verifyOtp({token_hash:claim.token_hash,type:'email'});if(verified.error)throw verified.error;await rpc(w,'v3_enrollment_complete',{p_enrollment:claim.enrollment_id});await rpc(w,'v3_training',{p_answers:['after_voting','voluntary','pending_not_received'],p_practice_ack:true,p_client:30000});
   const boot=await rpc(w,'v3_bootstrap'),personData=boot.people.find(p=>p.id===person);await cmd('person.approve',{id:person,reason:'Observed native synthetic practice'},personData.revision);
   const task=(await cmd('assignment.create',{person_id:person,point_id:point,reason:'Native live integration task'})).id;
   if(city==='cde'){const password=randomBytes(24).toString('base64url');const changed=await w.auth.updateUser({password});if(changed.error)throw changed.error;workerBrowser={code:boot.actor.code,password,task,point,person};}
   else{await rpc(w,'v3_ack_assignment',{p_assignment:task,p_version:1,p_questionnaire:q,p_point:point,p_client:30000});await cmd('point.state',{id:point,state:'open',reason:'Native one point live test'},2);const pack=await rpc(w,'v3_start_task',{p_assignment:task,p_device:randomUUID(),p_client:30000});for(let i=0;i<40;i++)await rpc(w,'v3_submit_response',{p_event:{id:randomUUID(),assignment_id:task,grant_id:pack.grant.id,point_id:point,questionnaire_id:q,started_at:new Date().toISOString(),captured_at:new Date().toISOString(),outcome:'candidate',candidate_id:pack.questionnaire.items[i%count].id,consent:true,already_voted:true,geo:{status:'not_requested'}},p_client:30000});}
  });
  const config=await rpc(admin,'v3_report_config',{p_questionnaire:q});configs.push(await rpc(admin,'v3_report_alias_save',{p_questionnaire:q,p_items:config.items.map(x=>({candidate_id:x.candidate_id,code:x.code})),p_expected:config.alias_revision,p_confirmed:true}));
 }
 await check('Four-city HTTP DTO has 2/4/2/4 codes, independent counts and no private candidate fields',async()=>{const d=validate(await rpc(admin,'v3_live_board',{p_audience:'codes'}));assert.deepEqual(d.cities.map(c=>c.candidates.length),[2,4,2,4]);assert.deepEqual(d.cities.slice(1).map(c=>c.counts.candidate_base),[40,40,40]);for(const config of configs)for(const x of config.items){assert(!JSON.stringify(d).includes(x.real_name));assert(!JSON.stringify(d).includes(x.candidate_id));}});
 await check('Actual Viewer login cannot read internal projection or private console state',async()=>{const row=(await db.query("select user_id,revision from pulso_v3.actors where code='VIEW-NATIVE'")).rows[0];await cmd('actor.enable',{id:row.user_id,reason:'Native live access check'},row.revision);viewer=client();const l=await viewer.auth.signInWithPassword({email:'view-native@pulso-encuestadores.invalid',password:prior.viewer.password});if(l.error)throw l.error;await assert.rejects(rpc(viewer,'v3_live_board',{p_audience:'internal'}),/ADMIN_ONLY/);await assert.rejects(rpc(viewer,'v3_live_admin_state'),/ADMIN_ONLY/);await assert.rejects(rpc(viewer,'v3_live_board',{p_district:'minga'}),/SCOPE_DENIED/);});
 await check('Live external permission cannot be granted before release policy',async()=>{await assert.rejects(rpc(admin,'v3_live_authorize',{p_district:'cde',p_enabled:true,p_expires:new Date(Date.now()+600000).toISOString(),p_reference:'Synthetic premature release',p_confirmed:true}),/RELEASE_BLOCKED/);});
 state=await rpc(admin,'v3_live_admin_state');await rpc(admin,'v3_report_policy_save',{p_enabled:true,p_not_before:new Date(Date.now()-60000).toISOString(),p_reference:'ISOLATED QA AUTHORIZATION ONLY',p_expected:state.policy.revision});await cmd('viewer.access',{enabled:true,reason:'Isolated viewer live acceptance'},state.operation.revision);
 await check('Native continuous authorization permits authorized CDE viewer, not other cities',async()=>{for(const c of state.cities)await rpc(admin,'v3_live_authorize',{p_district:c.id,p_enabled:true,p_expires:new Date(Date.now()+1800000).toISOString(),p_reference:'ISOLATED SYNTHETIC LIVE QA ONLY',p_confirmed:true});const d=validate(await rpc(viewer,'v3_live_board'));assert.equal(d.cities.length,1);assert.equal(d.cities[0].id,'cde');assert.equal(d.audience,'released');assert(!JSON.stringify(d).includes('real_name'));});
 await check('A report snapshot uses the same accepted total but remains frozen as live view changes',async()=>{cut=(await rpc(admin,'v3_report_create',{p_questionnaire:ctx.q,p_cutoff:null,p_request_id:randomUUID()})).id;const inside=await rpc(admin,'v3_report_read',{p_id:cut,p_audience:'internal'}),external=await rpc(admin,'v3_report_read',{p_id:cut,p_audience:'external'}),live=await rpc(admin,'v3_live_board',{p_audience:'internal',p_district:'cde'});assert.equal(inside.stats.candidate_base,external.candidate_base);assert.equal(external.candidate_base,live.cities[0].counts.candidate_base);assert.equal(external.status,'draft');assert(inside.total_records>500);let ids=[],offset=0;do{const page=await rpc(admin,'v3_report_read',{p_id:cut,p_audience:'internal',p_offset:offset,p_limit:500});ids.push(...page.records.map(r=>r.id));offset=page.next_offset;}while(offset!==null);assert.equal(ids.length,inside.total_records);assert.equal(new Set(ids).size,ids.length);});
 await check('Native frozen external report excludes identities and is separately authorized',async()=>{await assert.rejects(rpc(viewer,'v3_report_read',{p_id:cut,p_audience:'external'}),/SCOPE_DENIED/);await rpc(admin,'v3_report_release',{p_id:cut,p_confirmed:true,p_reference:'ISOLATED CUT RELEASE QA ONLY'});const d=await rpc(viewer,'v3_report_read',{p_id:cut,p_audience:'external'});for(const x of configs[0].items){assert(!JSON.stringify(d).includes(x.real_name));assert(!JSON.stringify(d).includes(x.candidate_id));}await assert.rejects(rpc(viewer,'v3_report_read',{p_id:cut,p_audience:'internal'}),/ADMIN_ONLY/);});
 await check('Private tables remain unreadable by direct authenticated and anonymous APIs',async()=>{assert((await admin.schema('pulso_v3').from('report_cuts').select('*')).error);await assert.rejects(rpc(anon,'v3_live_board'));await assert.rejects(rpc(viewer,'v3_live_authorize',{p_district:'cde',p_enabled:false,p_expires:null,p_reference:'Unauthorized request',p_confirmed:true}),/ADMIN_ONLY/);});
 await check('Revoking a live channel hides it while collection stays running',async()=>{await rpc(admin,'v3_live_authorize',{p_district:'cde',p_enabled:false,p_expires:null,p_reference:'ISOLATED REVOCATION QA ONLY',p_confirmed:true});assert.equal((await rpc(viewer,'v3_live_board')).cities[0].state,'withheld');assert.equal((await rpc(admin,'v3_live_admin_state')).operation.phase,'running');await rpc(admin,'v3_live_authorize',{p_district:'cde',p_enabled:true,p_expires:new Date(Date.now()+1800000).toISOString(),p_reference:'ISOLATED RESTORE CHANNEL QA',p_confirmed:true});});
 const made=await edge({action:'create_access',request_id:randomUUID(),code:'VIEW-LIVE-ALL',role:'viewer',display_name:'Viewer cuatro ciudades QA'});viewerAllPassword=made.credential.password;viewerAll=client();const l=await viewerAll.auth.signInWithPassword({email:'view-live-all@pulso-encuestadores.invalid',password:viewerAllPassword});if(l.error)throw l.error;for(const c of state.cities)await cmd('grant.save',{user_id:l.data.user.id,district_id:c.id,capabilities:['view_results'],valid_until:new Date(Date.now()+1800000).toISOString()});
 await check('Four-city Viewer gets four code-only cards without private access',async()=>{assert.equal(validate(await rpc(viewerAll,'v3_live_board')).cities.length,4);await assert.rejects(rpc(viewerAll,'v3_live_admin_state'),/ADMIN_ONLY/);});
 await fs.writeFile('/tmp/pulso-live-private.json',JSON.stringify({url:ctx.url,key:ctx.key,admin:{code:ctx.adminMail,password:ctx.adminPassword},viewer:{code:'VIEW-NATIVE',password:prior.viewer.password},viewerAll:{code:'VIEW-LIVE-ALL',password:viewerAllPassword},worker:workerBrowser,cut,configs}),{mode:0o600});
}catch(e){console.error('Live native failure',e.message);process.exitCode=1;}finally{await fs.mkdir(out,{recursive:true});await fs.writeFile(new URL('live-native.json',out),JSON.stringify({scope:'Actual native Auth/PostgREST/Edge on isolated local Supabase; not hosted, not physical mobile devices',passed:results.filter(r=>r.pass).length,failed:results.filter(r=>!r.pass).length,results},null,2));await db.end();for(const c of clients)await c.realtime.disconnect();}
process.exit(process.exitCode||0);
