/** 60/120 distinct native Auth users against disposable localhost, never production. */
import fs from 'node:fs/promises';import assert from 'node:assert/strict';import {randomUUID,randomBytes} from 'node:crypto';import {performance} from 'node:perf_hooks';import pg from 'pg';import {createClient} from '@supabase/supabase-js';
const x=JSON.parse(await fs.readFile('/tmp/pulso-v3-local-context.json','utf8'));
if(!/^http:\/\/127\.0\.0\.1:/.test(x.url)||!x.dbUrl.includes('127.0.0.1'))throw Error('Local sandbox required');
const svc=createClient(x.url,x.secret,{auth:{persistSession:false,autoRefreshToken:false}}),admin=createClient(x.url,x.key,{auth:{persistSession:false,autoRefreshToken:false}}),db=new pg.Client({connectionString:x.dbUrl});await db.connect();
const login=await admin.auth.signInWithPassword({email:x.adminMail,password:x.adminPassword});if(login.error)throw login.error;const adminId=login.data.user.id;
const rpc=async(c,name,args={})=>{const r=await c.rpc(name,args);if(r.error)throw r.error;return r.data;};
const cmd=(action,data,rev=0)=>rpc(admin,'v3_command',{p_action:action,p_data:data,p_request_id:randomUUID(),p_expected:rev});
const users=[],metrics=[],results=[];const dlist=['cde','minga','hernandarias','franco'];const points={cde:{point:x.point,q:x.q}};
try{
 for(const d of dlist.slice(1)){const station=(await cmd('station.save',{district_id:d,code:'LOAD-S-'+d.toUpperCase(),name:'Centro QA carga '+d,address:'Dirección sintética prueba de carga'})).id;const point=(await cmd('point.save',{station_id:station,code:'LOAD-P-'+d.toUpperCase(),label:'Punto sintético de carga'})).id;await cmd('point.approve',{id:point,verified:true,reason:'Synthetic load-only authorization'},1);const q=(await cmd('questionnaire.save',{district_id:d,contest:'Intendencia municipal',methodology:'Synthetic controlled load; no real respondents involved',sample_interval:5,reference:'Load fixture only',items:[{id:randomUUID(),name:'Candidatura DEMO A',list:'Lista DEMO A'},{id:randomUUID(),name:'Candidatura DEMO B',list:'Lista DEMO B'}]})).id;await cmd('questionnaire.publish',{id:q,confirmed:true},1);points[d]={point,q};}
 for(let i=0;i<120;i++){
  const code='LOAD-'+String(i+1).padStart(4,'0'),mail=code.toLowerCase()+'@pulso-test.invalid',password=randomBytes(24).toString('base64url');const made=await svc.auth.admin.createUser({email:mail,password,email_confirm:true});if(made.error)throw made.error;const user=made.data.user.id,d=dlist[i%4],point=points[d].point,q=points[d].q,person=randomUUID(),task=randomUUID();
  await db.query("INSERT INTO pulso_v3.people(id,display_name,home_district,recruit_point,approval,training_passed_at,training_practice_ack,approved_by,approved_at,created_by) VALUES($1,$2,$3,$4,'approved',now(),true,$5,now(),$5)",[person,code,d,point,adminId]);
  await db.query("INSERT INTO pulso_v3.actors(user_id,person_id,code,display_name,role,enrolled) VALUES($1,$2,$3,$3,'interviewer',true)",[user,person,code]);
  await db.query("INSERT INTO pulso_v3.assignments(id,person_id,point_id,questionnaire_id,status,created_by,acknowledged_at,reason) VALUES($1,$2,$3,$4,'acknowledged',$5,now(),'Synthetic load setup')",[task,person,point,q,adminId]);
  const client=createClient(x.url,x.key,{auth:{persistSession:false,autoRefreshToken:false}});const auth=await client.auth.signInWithPassword({email:mail,password});if(auth.error)throw auth.error;
  users.push({client,task,point,q,d,person});
 }
 for(const d of dlist.slice(1))await cmd('point.state',{id:points[d].point,state:'open',reason:'Open load-only point'},2);
 for(const u of users)u.pack=await rpc(u.client,'v3_start_task',{p_assignment:u.task,p_device:randomUUID(),p_client:30000});
 const before=Number((await db.query('select count(*) n from pulso_v3.responses')).rows[0].n);
 const make=u=>({id:randomUUID(),assignment_id:u.task,grant_id:u.pack.grant.id,point_id:u.point,questionnaire_id:u.q,started_at:new Date().toISOString(),captured_at:new Date().toISOString(),outcome:'candidate',candidate_id:u.pack.questionnaire.items[0].id,consent:true,already_voted:true,geo:{status:'not_requested'}});
 const submit=async(u,e)=>{const begin=performance.now(),r=await rpc(u.client,'v3_submit_response',{p_event:e,p_client:30000});metrics.push(performance.now()-begin);assert.equal(r.disposition,'accepted');return r;};
 let expected=0;
 for(const phase of [{name:'60 native users / 600 writes',n:60,each:10},{name:'120 native users / 240 writes',n:120,each:2},{name:'60 native users / 3000 backlog writes',n:60,each:50}]){const start=performance.now(),base=metrics.length;await Promise.all(users.slice(0,phase.n).map(async u=>{for(let j=0;j<phase.each;j++)await submit(u,make(u));}));expected+=phase.n*phase.each;const durations=metrics.slice(base).sort((a,b)=>a-b),after=Number((await db.query('select count(*) n from pulso_v3.responses')).rows[0].n);assert.equal(after,before+expected);results.push({name:phase.name,pass:true,distinct_native_users:phase.n,records:phase.n*phase.each,seconds:(performance.now()-start)/1000,p95_ms:durations[Math.floor(durations.length*.95)],count_verified:after});console.log('PASS',phase.name);}
 const u=users[0],e=make(u);const retry=await Promise.all(Array.from({length:20},()=>submit(u,e)));assert.equal(new Set(retry.map(r=>r.receipt_id)).size,1);expected+=1;assert.equal(Number((await db.query('select count(*) n from pulso_v3.responses')).rows[0].n),before+expected);results.push({name:'20 concurrent retries, one receipt and one row',pass:true});
 const snap=await cmd('export.create',{kind:'responses'});let offset=0,total=0;do{const p=await rpc(admin,'v3_export_page',{p_id:snap.id,p_offset:offset,p_limit:500});total+=p.data.length;offset=p.next_offset;}while(offset!==null);assert.equal(total,before+expected);results.push({name:'Full export pagination equals database after load',pass:true,rows:total});
}catch(e){results.push({name:'Load execution',pass:false,error:String(e.message||e).slice(0,400)});console.error('LOAD FAIL',e.message||e);process.exitCode=1;}finally{await fs.writeFile(new URL('../evidence/load-native.json',import.meta.url),JSON.stringify({environment:'Disposable Supabase CLI only; native Auth users and HTTP PostgREST; not physical phones or production plan',auth_limits:'CI sign-in budget raised to 1000 only to seed native sessions; onboarding rate not certified for production',results,passed:results.filter(x=>x.pass).length,failed:results.filter(x=>!x.pass).length},null,2));await db.end();}
