import {verifyRealtime} from './realtime-probe.mjs';
/** Native Auth + PostgREST + Edge + Storage integration, local Docker only. Never production. */
import fs from 'node:fs/promises';import assert from 'node:assert/strict';import {randomUUID,randomBytes,createHash} from 'node:crypto';
import pg from 'pg';import {createClient} from '@supabase/supabase-js';
const status=JSON.parse(await fs.readFile(process.env.LOCAL_STATUS_FILE,'utf8'));
const url=status.API_URL||status.api_url,key=status.ANON_KEY||status.anon_key,secret=status.SERVICE_ROLE_KEY||status.service_role_key,dbUrl=status.DB_URL||status.db_url;
if(!/^http:\/\/(127\.0\.0\.1|localhost):/.test(url)||!dbUrl?.includes('127.0.0.1'))throw Error('Only disposable local Supabase permitted');
const origin='http://127.0.0.1:8044',results=[],evidence=new URL('../evidence/',import.meta.url);await fs.mkdir(evidence,{recursive:true});
const db=new pg.Client({connectionString:dbUrl,statement_timeout:20000,query_timeout:25000});await db.connect();const service=createClient(url,secret,{auth:{persistSession:false,autoRefreshToken:false}});
const client=()=>createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}});
const pw=()=>randomBytes(24).toString('base64url');const adminMail='qa-v3-admin@pulso-test.invalid',adminPassword=pw();
const check=async(name,f)=>{console.log('BEGIN',name);try{await f();results.push({name,pass:true});console.log('PASS',name);}catch(e){results.push({name,pass:false,error:String(e.message||e).slice(0,400)});throw e;}finally{await fs.writeFile(new URL('native-progress.json',evidence),JSON.stringify({completed:false,results},null,2));}};
const rpc=async(c,name,data={})=>{const {data:r,error}=await c.rpc(name,data);if(error)throw Object.assign(new Error(error.message),error);return r;};
const command=(c,a,d,e=0,r=randomUUID())=>rpc(c,'v3_command',{p_action:a,p_data:d,p_expected:e,p_request_id:r,p_client:30000});
const row=async(t,id)=> (await db.query(`select * from pulso_v3.${t} where ${t==='actors'?'user_id':'id'}=$1`,[id])).rows[0];
const revision=async()=> (await db.query('select revision from pulso_v3.operations where id=1')).rows[0].revision;
const edge=async(c,body,anonymous=false)=>{const session=anonymous?null:(await c.auth.getSession()).data.session;const r=await fetch(url+'/functions/v1/field-enrollment',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json',apikey:key,...(session?{Authorization:'Bearer '+session.access_token}:{})},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw Object.assign(new Error(data.error),{status:r.status});return data;};
let admin,user,worker,point,station,q,task,pack,workerPassword,viewerSession,viewerUser,viewerPwd,workerCode,coord,coordId;
try{
 await check('Install unchanged V2 then additive V3 on native PostgreSQL',async()=>{for(const f of ['001_schema.sql','002_municipales_2026.sql','003_safeupdate_compatibility.sql'])await db.query(await fs.readFile(new URL('../../supabase/migrations/'+f,import.meta.url),'utf8'));const made=await service.auth.admin.createUser({email:adminMail,password:adminPassword,email_confirm:true});if(made.error)throw made.error;user=made.data.user.id;await db.query("INSERT INTO public.profiles(id,code,role) VALUES($1,'COORD-01','admin')",[user]);for(const f of ['004_v3_expand.sql','005_v3_api.sql','006_v3_enrollment.sql','007_v3_cutover.sql','008_v3_storage.sql'])await db.query(await fs.readFile(new URL('../../supabase/migrations/'+f,import.meta.url),'utf8'));await db.query("NOTIFY pgrst,'reload schema'");await new Promise(r=>setTimeout(r,1500));});
 await check('Native admin password login creates a real Auth session',async()=>{admin=client();const r=await admin.auth.signInWithPassword({email:adminMail,password:adminPassword});if(r.error)throw r.error;assert((await rpc(admin,'v3_bootstrap')).actor.role==='admin');assert((await db.query('select count(*) from auth.sessions where user_id=$1',[user])).rows[0].count>0);});
 await check('Anonymous and non-bearer Edge requests remain denied',async()=>{await assert.rejects(()=>edge(null,{action:'issue'},true),/SESSION_REQUIRED/);const r=await fetch(url+'/functions/v1/field-enrollment',{method:'OPTIONS',headers:{Origin:'https://unapproved.example'}});assert.equal(r.status,403);const r2=await fetch(url+'/functions/v1/field-enrollment',{method:'OPTIONS',headers:{Origin:origin}});assert.equal(r2.status,204);});
 await check('Explicit cutover fences the old deployed account API and tables',async()=>{await rpc(admin,'v3_activate',{p_legacy_outbox_handled:true,p_backup_reference:'Isolated fixture; production backup not attested',p_acceptance_reference:'Native test sandbox activation only'});const r=await service.from('profiles').select('id').limit(1);assert(r.error);await assert.rejects(()=>rpc(admin,'bootstrap'),/permission|function/);});
 const today=(await db.query("select (now() at time zone 'America/Asuncion')::date::text d")).rows[0].d;
 await check('Configure one verified point without a fixed staff quota',async()=>{await command(admin,'operation.save',{title:'Native integration only',contest:'Intendencia municipal',fieldwork_date:today,retention_policy:'Disposable test records only'},await revision());station=(await command(admin,'station.save',{district_id:'cde',code:'NATIVE-S01',name:'Centro sintético de pruebas',address:'Dirección técnica de prueba 100'})).id;point=(await command(admin,'point.save',{station_id:station,code:'NATIVE-P01',label:'Entrada QA'})).id;await command(admin,'point.approve',{id:point,verified:true,reason:'Only isolated fixture approval'},(await row('points',point)).revision);q=(await command(admin,'questionnaire.save',{district_id:'cde',contest:'Intendencia municipal',methodology:'Every fifth exiting consenting participant; synthetic only',sample_interval:5,reference:'Native QA fixture',items:[{id:randomUUID(),name:'Candidatura DEMO A',list:'Lista DEMO A'},{id:randomUUID(),name:'Candidatura DEMO B',list:'Lista DEMO B'}]})).id;await command(admin,'questionnaire.publish',{id:q,confirmed:true},1);});
 let person,invitation,claimSecret=randomBytes(32).toString('base64url'),claimLock=randomUUID(),claim;
 await check('Issue a scoped invitation in the actual Edge runtime',async()=>{person=(await command(admin,'person.add',{district_id:'cde',point_id:point,display_name:'Persona de prueba nativa'})).id;invitation=await edge(admin,{action:'issue',person_id:person,point_id:point,request_id:randomUUID()});assert.match(invitation.token,/^[A-Za-z0-9_-]{43}$/);});
 await check('Claim invitation creates native Auth + profile, then native OTP',async()=>{claim=await edge(null,{action:'claim',token:invitation.token,claim_secret:claimSecret,lock_id:claimLock},true);worker=client();const verified=await worker.auth.verifyOtp({token_hash:claim.token_hash,type:'email'});if(verified.error)throw verified.error;workerCode=(await rpc(worker,'v3_bootstrap')).actor.code;await rpc(worker,'v3_enrollment_complete',{p_enrollment:claim.enrollment_id});assert.equal((await rpc(worker,'v3_bootstrap')).actor.enrolled,true);});
 await check('Consumed invitation cannot mint access for a second claimant',async()=>{await assert.rejects(()=>edge(null,{action:'claim',token:invitation.token,claim_secret:randomBytes(32).toString('base64url'),lock_id:randomUUID()},true),/V3_/);});
 await check('Native viewer access creation and duplicate request recovery',async()=>{const request=randomUUID(),args={action:'create_access',request_id:request,code:'VIEW-NATIVE',role:'viewer',display_name:'Viewer QA'};const c=await edge(admin,args);viewerPwd=c.credential.password;const v=client(),r=await v.auth.signInWithPassword({email:'view-native@pulso-encuestadores.invalid',password:viewerPwd});if(r.error)throw r.error;viewerSession=v;viewerUser=r.data.user.id;assert((await edge(admin,args)).credentials_unavailable);await command(admin,'grant.save',{user_id:viewerUser,district_id:'cde',capabilities:['view_results'],valid_until:new Date(Date.now()+86400000).toISOString()});await assert.rejects(()=>rpc(v,'v3_dashboard'),/VIEWER_RESULTS_PENDING/);});
 await check('Native coordinator has only explicitly issued operational scope',async()=>{const c=await edge(admin,{action:'create_access',request_id:randomUUID(),code:'COORD-NATIVE',role:'coordinator',display_name:'Coordinador QA'});coord=client();const r=await coord.auth.signInWithPassword({email:'coord-native@pulso-encuestadores.invalid',password:c.credential.password});if(r.error)throw r.error;coordId=r.data.user.id;await command(admin,'grant.save',{user_id:coordId,district_id:'cde',point_id:point,capabilities:['recruit','assign','manage_points','control_points','operations'],valid_until:new Date(Date.now()+86400000).toISOString()});await assert.rejects(()=>command(coord,'person.add',{district_id:'minga',display_name:'forbidden'}),/SCOPE_DENIED/);await assert.rejects(()=>edge(coord,{action:'create_access',request_id:randomUUID(),code:'ADMIN-BAD',role:'admin',display_name:'forbidden'}),/ADMIN_ONLY/);});
 await check('Training, owner acknowledgement, one-person point opening',async()=>{await rpc(worker,'v3_training',{p_answers:['after_voting','voluntary','pending_not_received'],p_practice_ack:true,p_client:30000});await command(coord,'person.approve',{id:person,reason:'Observed synthetic practice'},(await row('people',person)).revision);task=(await command(coord,'assignment.create',{person_id:person,point_id:point,reason:'Native morning assignment'})).id;await rpc(worker,'v3_ack_assignment',{p_assignment:task,p_version:1,p_questionnaire:q,p_point:point,p_client:30000});await command(admin,'operation.state',{state:'running',reason:'Native isolated test opening'},await revision());await command(coord,'point.state',{id:point,state:'open',reason:'One worker ready in this point'},(await row('points',point)).revision);pack=await rpc(worker,'v3_start_task',{p_assignment:task,p_device:randomUUID(),p_client:30000});});
 const event=()=>({id:randomUUID(),assignment_id:task,grant_id:pack.grant.id,point_id:point,questionnaire_id:q,started_at:new Date().toISOString(),captured_at:new Date().toISOString(),outcome:'candidate',candidate_id:pack.questionnaire.items[0].id,consent:true,already_voted:true,geo:{status:'not_requested'}});
 await check('Native HTTP response write/readback and concurrent UUID idempotency',async()=>{const e=event(),receipts=await Promise.all(Array.from({length:12},()=>rpc(worker,'v3_submit_response',{p_event:e,p_client:30000})));assert.equal(new Set(receipts.map(r=>r.receipt_id)).size,1);assert.equal(receipts[0].disposition,'accepted');assert.equal(Number((await db.query('select count(*) from pulso_v3.responses where id=$1',[e.id])).rows[0].count),1);});
 await check('Realtime delivers a scoped revision notification after a confirmed write',()=>verifyRealtime({admin,worker,service,db,event,rpc,evidence})).catch(()=>{});
 await check('Actual private Storage upload/read permitted only for scoped owner',async()=>{const bytes=new TextEncoder().encode('%PDF-1.4\n% isolated test fixture only\n%%EOF');const a=await command(coord,'attachment.reserve',{id:point,purpose:'methodology',file_name:'qa.pdf',media_type:'application/pdf',bytes:bytes.length});let r=await coord.storage.from('pulso-v3-docs').upload(a.path,bytes,{contentType:'application/pdf',upsert:false});if(r.error)throw r.error;await rpc(coord,'v3_attachment_confirm',{p_id:a.id});r=await coord.storage.from('pulso-v3-docs').download(a.path);if(r.error)throw r.error;assert.equal(await r.data.text(),new TextDecoder().decode(bytes));const denied=await viewerSession.storage.from('pulso-v3-docs').download(a.path);assert(denied.error);});
 await check('Password reset revokes the previous live worker session',async()=>{const boot=await rpc(worker,'v3_bootstrap'),r=await edge(admin,{action:'reset_password',user_id:boot.actor.user_id});workerPassword=r.credential.password;await assert.rejects(()=>rpc(worker,'v3_bootstrap'),/SESSION_REQUIRED/);worker=client();const login=await worker.auth.signInWithPassword({email:workerCode.toLowerCase()+'@pulso-encuestadores.invalid',password:workerPassword});if(login.error)throw login.error;assert.equal((await rpc(worker,'v3_bootstrap')).actor.role,'interviewer');await rpc(worker,'v3_finish_my_task',{p_assignment:task,p_reason:'End native API task before independent browser assignment'});});
 await check('Disable viewer rejects its existing native session',async()=>{await command(admin,'actor.disable',{id:viewerUser},(await row('actors',viewerUser)).revision);await assert.rejects(()=>rpc(viewerSession,'v3_bootstrap'),/ACCOUNT_DISABLED/);});
 // Browser fixture is deliberately outside evidence; it contains disposable passwords and is never uploaded.
 await fs.writeFile('/tmp/pulso-v3-browser-private.json',JSON.stringify({url,key,admin:{code:adminMail,password:adminPassword},worker:{code:workerCode,password:workerPassword},viewer:{code:'VIEW-NATIVE',password:viewerPwd},point,person,task}),{mode:0o600});
 await fs.writeFile('/tmp/pulso-v3-local-context.json',JSON.stringify({url,key,secret,dbUrl,adminMail,adminPassword,point,q}),{mode:0o600});
}catch(e){console.error('Native test failed:',e.message||e);process.exitCode=1;
 try{const facts=await db.query("select exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='v3_signals') publication_ok,has_function_privilege('authenticated','public.v3_can_read_signal(text)','execute') signal_function_grant,has_table_privilege('authenticated','public.v3_signals','select') signal_table_grant");await fs.writeFile(new URL('native-diagnostic.json',evidence),JSON.stringify({facts:facts.rows,scope:'Boolean permissions only; no tokens or answers'}));}catch{}
}finally{await fs.writeFile(new URL('native.json',evidence),JSON.stringify({environment:'DISPOSABLE SUPABASE CLI 2.117.0; native Auth/PostgREST/Edge/Storage/Realtime; NOT production',auth_limits:'Local CI sign_in_sign_ups=1000; not a production throughput claim',at:new Date().toISOString(),passed:results.filter(r=>r.pass).length,failed:results.filter(r=>!r.pass).length,results},null,2));await Promise.all([admin,worker,coord,viewerSession,service].filter(Boolean).map(async c=>{await c.removeAllChannels().catch(()=>{});await c.realtime.disconnect();}));await db.end();}
if(results.some(r=>!r.pass))process.exitCode=1;
process.exit(process.exitCode||0);
