import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {generatedPassword,hasSimple,accountFields,waiting} from '../web/modules/simple-login.mjs';
test('Only server module flag opts into simple login',()=>{assert(hasSimple({simple_login_version:15}));for(const b of [{},{simple_login_version:'15'},{is_admin:true},null])assert(!hasSimple(b));});
test('Individual generated password has 20 unambiguous random characters',()=>{const passwords=Array.from({length:100},generatedPassword);assert.equal(new Set(passwords).size,100);for(const s of passwords)assert.match(s,/^[A-HJ-NP-Za-km-z2-9]{20}$/);});
test('Form requires individual code/password and optional scoped point; no role injection',()=>{const s=accountFields();assert(s.includes('minlength="16"'));assert(s.includes('ENC-CDE-001'));assert(!s.includes('name="role"'));assert(!s.includes('Super Admin'));});
test('Waiting does not bypass absent assignment',()=>{const s=waiting({simpleState:'waiting_assignment'});assert(s.includes('Espere la asignación'));assert(!s.includes('capture-form'));});
test('Server account call never carries password into SQL',()=>{const s=fs.readFileSync(new URL('../../supabase/functions/interviewer-access/index.ts',import.meta.url),'utf8');const args=s.slice(s.indexOf('const args='),s.indexOf('const call='));assert(!args.includes('password'));assert(s.includes('service.auth.getUser'));assert(s.includes("origins.includes(origin)"));});
test('Legacy storage is copied, not deleted or rekeyed',()=>{const s=fs.readFileSync(new URL('../web/modules/device-vault.mjs',import.meta.url),'utf8');assert(s.includes('pulso-personal-device-v1'));assert(!s.includes('deleteDatabase'));assert(!s.includes("this.legacy.put"));assert(s.includes('legacy_preserved:true'));});
test('Automatic account authorization never fabricates training',()=>{const s=fs.readFileSync(new URL('../../supabase/migrations/015_v3_simple_interviewers.sql',import.meta.url),'utf8');assert(s.includes("'training_completed',false"));assert(!s.includes('SET training_passed_at'));assert(s.includes("a.role<>'admin'"));});
