import {internalCSV} from '../web/modules/report-render.mjs';
import {parseCSV} from '../web/modules/importer.mjs';
/** PGlite actual SQL with synthetic Auth sessions. Never a hosted project. */
import {database,as,admin,adminSession} from './db-fixture.mjs';import fs from 'node:fs/promises';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {validate,CITIES,exportCSV,exportSVG,percentage,card,donut} from '../live/core.mjs';
const db=await database(),results=[],forbidden=[];
const rpc=(name,args=[],u=admin,s=adminSession)=>as(db,u,s,`select public.${name}(${args.map((_,i)=>'$'+(i+1)).join(',')}) r`,args).then(x=>x[0].r);
const cmd=(name,data,rev=0)=>rpc('v3_command',[name,data,randomUUID(),rev]);
const revision=async(t,id)=>(await db.query(`select revision from pulso_v3.${t} where id=$1`,[id])).rows[0].revision;
async function test(name,f){try{await f();results.push({name,pass:true});console.log('PASS',name);}catch(e){results.push({name,pass:false,error:e.message});throw e;}}
const fixtures=[];
const event=(f,index=0,outcome='candidate')=>({id:randomUUID(),assignment_id:f.task,grant_id:f.pack.grant.id,point_id:f.point,questionnaire_id:f.q,started_at:new Date().toISOString(),captured_at:new Date().toISOString(),outcome,candidate_id:outcome==='candidate'?f.items[index].id:null,consent:outcome!=='refused',already_voted:true,geo:{status:'not_requested'}});
const send=(f,index=0,outcome='candidate')=>rpc('v3_submit_response',[event(f,index,outcome)],f.user,f.session);
const leak=value=>{const s=typeof value==='string'?value:JSON.stringify(value);for(const word of forbidden)assert(!s.includes(word),'Private field in projection');};
try{
 await db.exec(await fs.readFile(new URL('../../supabase/migrations/009_v3_reports.sql',import.meta.url),'utf8'));
 const migration=await fs.readFile(new URL('../../supabase/migrations/010_v3_live_board.sql',import.meta.url),'utf8');
 await test('Live installation is repeatable and never opens collection',async()=>{await db.exec(migration);await db.exec(migration);assert.equal((await db.query('select operation_mode from public.settings')).rows[0].operation_mode,'v2');assert.equal((await db.query('select phase from pulso_v3.operations')).rows[0].phase,'setup');});
 await test('Zero-data four-city panel does not invent zero-vote results',async()=>{const r=validate(await rpc('v3_live_board',['internal']));assert.equal(r.cities.length,4);assert(r.cities.every(c=>c.state==='catalog_pending'&&c.counts===null&&c.candidates.length===0));});
 await test('Anonymous direct calls and private release tables are not readable',async()=>{await db.exec('begin;set local role anon');try{await assert.rejects(db.query("select public.v3_live_board('codes')"),/permission denied/);}finally{await db.exec('rollback');}await assert.rejects(as(db,admin,adminSession,'select * from pulso_v3.live_releases'),/permission denied/);});
 await rpc('v3_activate',[true,'Synthetic backup reference','Synthetic acceptance reference']);
 const today=(await db.query("select (now() at time zone 'America/Asuncion')::date::text d")).rows[0].d;
 await cmd('operation.save',{title:'Synthetic live exercise',contest:'Intendencia municipal',fieldwork_date:today,retention_policy:'Synthetic only, no real votes'},await revision('operations',1));
 for(const[i,c]of CITIES.entries()){
  const f={...c,user:randomUUID(),session:randomUUID()};
  f.station=(await cmd('station.save',{district_id:c.id,code:'L-S-'+i,name:'Centro SINTÉTICO '+i,address:'Dirección de pruebas '+i+' sin datos reales'})).id;
  f.point=(await cmd('point.save',{station_id:f.station,code:'L-P-'+i,label:'Punto SINTÉTICO '+i})).id;await cmd('point.approve',{id:f.point,verified:true,reason:'Synthetic approval for live testing'},1);
  f.items=Array.from({length:i%2?4:2},(_,j)=>({id:randomUUID(),name:'Candidatura SINTÉTICA '+i+' '+String.fromCharCode(65+j),list:'Lista PRIVADA '+(j+1)}));
  f.q=(await cmd('questionnaire.save',{district_id:c.id,contest:'Intendencia municipal',methodology:'Synthetic every-fifth-visitor fixture; no actual investigation.',sample_interval:5,reference:'Synthetic live source',items:f.items})).id;
  await cmd('questionnaire.publish',{id:f.q,confirmed:true},1);
  f.person=(await cmd('person.add',{district_id:c.id,point_id:f.point,display_name:'Persona de pruebas '+i})).id;
  await db.query('insert into auth.users(id,email) values($1,$2)',[f.user,'worker'+i+'@example.invalid']);await db.query('insert into auth.sessions values($1,$2)',[f.session,f.user]);
  await db.query("insert into pulso_v3.actors(user_id,code,display_name,role,person_id,enrolled) values($1,$2,$2,'interviewer',$3,true)",[f.user,'LIVE-EN-'+i,f.person]);
  await rpc('v3_training',[['after_voting','voluntary','pending_not_received'],true],f.user,f.session);await cmd('person.approve',{id:f.person,reason:'Synthetic supervisor approval'},2);
  f.task=(await cmd('assignment.create',{person_id:f.person,point_id:f.point,reason:'Synthetic live task'})).id;await rpc('v3_ack_assignment',[f.task,1,f.q,f.point],f.user,f.session);
  fixtures.push(f);forbidden.push(f.q,f.person,f.point,f.station,...f.items.flatMap(x=>[x.id,x.name,x.list]));
 }
 await test('Real-name admin display is available before collection has started',async()=>{const r=validate(await rpc('v3_live_board',['internal']));assert(r.cities.every(c=>c.state==='no_data'));assert.equal(r.cities[0].candidates[0].real_name,fixtures[0].items[0].name);});
 await test('Missing aliases never fall back to real names on code screens',async()=>{const r=validate(await rpc('v3_live_board',['codes']));assert(r.cities.every(c=>c.state==='codes_pending'));leak(r);});
 for(const f of fixtures)await rpc('v3_report_alias_save',[f.q,f.items.map((c,j)=>({candidate_id:c.id,code:f.code+'-'+String.fromCharCode(65+j)})),0,true]);
 await cmd('operation.state',{state:'running',reason:'Synthetic live running state'},await revision('operations',1));
 for(const f of fixtures){await cmd('point.state',{id:f.point,state:'open',reason:'Synthetic count-audit opening'},2);f.pack=await rpc('v3_start_task',[f.task,randomUUID()],f.user,f.session);}
 const expected=[[2,1],[1,2,3,4],[1,1],[0,1,0,1]],others=[['blank','refused'],['invalid','undisclosed'],[],['blank','blank']],submitted=[];
 for(const [i,f] of fixtures.entries()){
  for(const [j,n] of expected[i].entries())for(let k=0;k<n;k++){const e=event(f,j),receipt=await rpc('v3_submit_response',[e],f.user,f.session);submitted.push({f,e,receipt});}
  for(const outcome of others[i])await send(f,0,outcome);
 }
 await test('Golden totals: A2 B1 blank1 refusal1 yields 5 contacts and candidate base 3',async()=>{
  const c=validate(await rpc('v3_live_board',['internal','cde'])).cities[0];assert.deepEqual(c.counts,{received:5,accepted:5,pending_review:0,excluded:0,candidate_base:3});assert.deepEqual(c.candidates.map(x=>x.count),[2,1]);assert.deepEqual(c.other_answers,{blank:1,invalid:0,undisclosed:0,refused:1});
  assert.equal(percentage(2,3),new Intl.NumberFormat('es-PY',{minimumFractionDigits:1,maximumFractionDigits:1}).format(200/3)+'%');assert.notEqual(percentage(2,3),percentage(2,5));
 });
 await test('Four-city candidate totals stay independent: 3, 10, 2, 2',async()=>{
  const b=validate(await rpc('v3_live_board',['internal']));assert.deepEqual(b.cities.map(c=>c.counts.candidate_base),[3,10,2,2]);assert.deepEqual(b.cities.map(c=>c.counts.received),[5,12,2,4]);
  b.cities.forEach((c,i)=>{assert.deepEqual(c.candidates.map(x=>x.count),expected[i]);assert.deepEqual(c.candidates.map(x=>x.real_name),fixtures[i].items.map(x=>x.name));assert.equal(c.coverage.represented_points,1);assert.equal(c.coverage.configured_points,4);});
  // Each fixture has three retained legacy draft points plus one new approved point.
 });
 await test('All four city filters return exactly the requested city and current name order',async()=>{for(const [i,f]of fixtures.entries()){const b=validate(await rpc('v3_live_board',['internal',f.id]));assert.equal(b.cities.length,1);assert.equal(b.cities[0].id,f.id);assert.deepEqual(b.cities[0].candidates.map(x=>x.count),expected[i]);}});
 await test('Identical UUID retry never increases counts and returns the identical receipt',async()=>{const s=submitted[0],before=(await rpc('v3_live_board',['internal','cde'])).cities[0].counts;const r=await rpc('v3_submit_response',[s.e],s.f.user,s.f.session);assert.equal(r.receipt_id,s.receipt.receipt_id);assert.deepEqual((await rpc('v3_live_board',['internal','cde'])).cities[0].counts,before);});
 await test('Same UUID with a changed candidate is refused without overwriting the original',async()=>{const s=submitted[0];await assert.rejects(rpc('v3_submit_response',[{...s.e,candidate_id:s.f.items[1].id}],s.f.user,s.f.session),/IDEMPOTENCY_CONFLICT/);const row=(await db.query('select candidate_id from pulso_v3.responses where id=$1',[s.e.id])).rows[0];assert.equal(row.candidate_id,s.e.candidate_id);});
 await test('Foreign-city candidate is rejected and no contact or numerator is added',async()=>{const f=fixtures[0],before=(await rpc('v3_live_board',['internal','cde'])).cities[0].counts;await assert.rejects(rpc('v3_submit_response',[{...event(f),candidate_id:fixtures[1].items[0].id}],f.user,f.session),/CANDIDATE_VERSION_MISMATCH/);assert.deepEqual((await rpc('v3_live_board',['internal','cde'])).cities[0].counts,before);});
 await test('Missing voted/consent and a refusal carrying a candidate are all refused',async()=>{const f=fixtures[0];for(const patch of [{already_voted:false},{consent:false},{outcome:'refused',consent:false}])await assert.rejects(rpc('v3_submit_response',[{...event(f),...patch}],f.user,f.session));assert.equal((await rpc('v3_live_board',['internal','cde'])).cities[0].counts.received,5);});
 await test('Internal source records retain immutable person, point, version and both timestamps',async()=>{const s=submitted[0],row=(await db.query('select * from pulso_v3.responses where id=$1',[s.e.id])).rows[0];assert.equal(row.person_id,s.f.person);assert.equal(row.point_id,s.f.point);assert.equal(row.questionnaire_id,s.f.q);assert.equal(row.captured_at.toISOString(),s.e.captured_at);assert(row.received_at);});
 let cut,inside,outside;
 await test('Frozen internal and external report have the identical cutoff and preserve small-sample suppression',async()=>{cut=(await rpc('v3_report_create',[fixtures[0].q,null,randomUUID()])).id;inside=await rpc('v3_report_read',[cut,'internal',0,500]);outside=await rpc('v3_report_read',[cut,'external']);assert.equal(inside.cutoff_at,outside.cutoff_at);assert.equal(inside.total_records,5);assert.equal(inside.stats.candidate_base,3);assert.equal(outside.suppressed,true);assert.equal(outside.candidate_base,null);assert.deepEqual(outside.candidates,[]);leak(outside);});
 await test('Private codes-only preview uses identical numbers without transmitting real names/Lista',async()=>{const named=validate(await rpc('v3_live_board',['internal'])),coded=validate(await rpc('v3_live_board',['codes']));for(let i=0;i<4;i++){assert.deepEqual(coded.cities[i].counts,named.cities[i].counts);assert.deepEqual(coded.cities[i].candidates.map(c=>c.count),named.cities[i].candidates.map(c=>c.count));}leak(coded);leak(exportCSV(coded,'all'));leak(exportSVG(coded,'all'));});
 await test('Rendered bars, percentages and donut segments use unrounded city ratios',async()=>{const b=validate(await rpc('v3_live_board',['codes','cde'])),c=b.cities[0],html=card(c,b.audience);assert(html.includes(percentage(2,3)));assert(html.includes(percentage(1,3)));assert(html.includes('width:'+2/3*100+'%'));const arcs=[...donut(c).matchAll(/stroke-dasharray="([0-9.]+) /g)].map(x=>Number(x[1]));assert(Math.abs(arcs.reduce((a,v)=>a+v,0)-100)<1e-9);});
 await test('Live output changes after a new accepted response but a frozen report does not',async()=>{await send(fixtures[0]);assert.equal((await rpc('v3_live_board',['internal','cde'])).cities[0].counts.candidate_base,4);assert.equal((await rpc('v3_report_read',[cut,'internal',0,500])).stats.candidate_base,3);});
 await test('Voiding removes the numerator, preserves total received and the original answer',async()=>{const s=submitted[0];await rpc('v3_void_own',[s.e.id,'capture_error'],s.f.user,s.f.session);const c=(await rpc('v3_live_board',['internal','cde'])).cities[0];assert.equal(c.counts.received,6);assert.equal(c.counts.candidate_base,3);assert.equal(c.counts.excluded,1);assert.equal((await db.query('select candidate_id from pulso_v3.responses where id=$1',[s.e.id])).rows[0].candidate_id,s.e.candidate_id);});
 await test('Paper record is pending review and excluded from candidate numerator',async()=>{const f=fixtures[0];await cmd('paper.submit',{assignment_id:f.task,response_id:randomUUID(),candidate_id:f.items[1].id,outcome:'candidate',consent:true,already_voted:true,started_at:new Date().toISOString(),captured_at:new Date().toISOString(),time_precision:'minutes',paper_batch:'COUNT-AUDIT',paper_number:'1',reason:'Synthetic paper audit; no real voter'});const c=(await rpc('v3_live_board',['internal','cde'])).cities[0];assert.equal(c.counts.received,7);assert.equal(c.counts.pending_review,1);assert.equal(c.counts.candidate_base,3);});
 await test('Every received contact equals accepted plus pending plus excluded',async()=>{const b=validate(await rpc('v3_live_board',['internal']));for(const c of b.cities){assert.equal(c.counts.received,c.counts.accepted+c.counts.pending_review+c.counts.excluded);assert.equal(c.counts.accepted,c.counts.candidate_base+Object.values(c.other_answers).reduce((a,n)=>a+n,0));}});
 await test('More than one report page is retrieved and internal CSV matches the complete source',async()=>{const f=fixtures[1];for(let i=0;i<490;i++)await send(f,i%4);const id=(await rpc('v3_report_create',[f.q,null,randomUUID()])).id;let records=[],first,offset=0,pages=0;do{const p=await rpc('v3_report_read',[id,'internal',offset,500]);first||=p;assert.equal(p.snapshot_at,first.snapshot_at);records.push(...p.records);offset=p.next_offset;pages++;}while(offset!==null);assert.equal(pages,2);assert.equal(records.length,502);assert.equal(first.total_records,502);assert.equal(new Set(records.map(x=>x.id)).size,502);const csv=internalCSV({...first,records});assert.equal(parseCSV(csv).length,503);assert(records.every(x=>x.station_name==='Centro SINTÉTICO 1'));outside=await rpc('v3_report_read',[id,'external']);assert.equal(outside.candidate_base,500);assert.equal(outside.candidates.reduce((a,x)=>a+x.count,0),500);leak(outside);});
 await test('Zero-count candidates display 0 only when the city actually has a candidate base',async()=>{const c=(await rpc('v3_live_board',['codes','franco'])).cities[0];assert.equal(c.candidates[0].count,0);assert.equal(percentage(0,c.counts.candidate_base),new Intl.NumberFormat('es-PY',{minimumFractionDigits:1,maximumFractionDigits:1}).format(0)+'%');assert.equal(percentage(0,0),'—');});
}catch(e){console.error('COUNT AUDIT FAIL',e.message);process.exitCode=1;}
finally{await fs.mkdir(new URL('../evidence/',import.meta.url),{recursive:true});await fs.writeFile(new URL('../evidence/statistics-review.json',import.meta.url),JSON.stringify({scope:'Actual PGlite SQL with synthetic Auth fixtures. No production database or physical phone. Render functions are the actual live/export code.',passed:results.filter(r=>r.pass).length,failed:results.filter(r=>!r.pass).length,results},null,2));await db.close();}
