"""V3.1 direct-use documentation, applied after the owner-only boundary policy."""
from copy import deepcopy
NOTICE_ES='Solo el Super Admin administra Supabase. Todos los demás trabajan únicamente en la Web App. Después de la actualización de acceso directo no existe un paso Activar V3. La recepción y la difusión conservan sus controles.'
NOTICE_ZH='僅 Super Admin 操作 Supabase，其餘人員只用 Web App。直接使用更新完成後，不再有 Activar V3 步驟；收件及發布仍保留各自控制。'
def apply_direct_policy(base):
 data=deepcopy(base);sections={s['id']:s for s in data}
 changes={
 ('01',4):('Ingrese para preparar datos, gestionar usuarios y usar las funciones autorizadas. No se solicita activar una versión. Abrir la recepción y autorizar difusión siguen siendo decisiones separadas; crear una cuenta no abre entrevistas ni resultados.','登入後即可準備資料、管理使用者及操作獲授權功能，不再要求啟用版本。開放收件及授權發布仍為分開決定；建立帳號不會自動開收或公開結果。'),
 ('03',0):('Solo el Super Admin designado, jaimehuang168@gmail.com, usa Supabase. Para esta actualización se requiere la instalación 004–012 y la cuenta propietaria existente. No se crean proyectos, usuarios de Auth ni contraseñas nuevas.','僅指定 Super Admin（jaimehuang168@gmail.com）使用 Supabase。本次更新要求既有 004–012 安裝及擁有者帳號；不新建專案、Auth 使用者或密碼。'),
 ('03',1):('El Super Admin ejecuta una sola vez V3_1_DIRECT_USE.sql en el proyecto existente. El archivo informa si 013 ya estaba instalado, lo instala solo si falta y aplica el acceso directo 014 en una transacción. No repita los instaladores anteriores.','Super Admin 在既有專案執行一次 V3_1_DIRECT_USE.sql。它回報 013 原先是否已安裝，僅在缺少時補上，再以同一交易套用 014 直接使用更新。不重跑舊安裝檔。'),
 ('03',2):('La actualización cierra las interfaces V2 y conserva sus tablas y registros. Las colas locales V2 no se borran, pero no se migran automáticamente. Si existen respuestas antiguas o un estado incompatible, se detiene la transacción sin borrar datos.','更新關閉 V2 介面但保留資料表及紀錄。本機 V2 待傳不會被刪除，也不會自動遷移；若有舊問卷或不相容狀態，整筆交易停止，不刪資料。'),
 ('03',3):('No se insertan entrevistas, no se cambia la fecha ni se abren puntos. No se inventan respaldos, aceptación ni confirmaciones del personal. Las referencias previas permanecen conservadas. field-enrollment y sus secretos siguen en Supabase.','不新增問卷、不改日期、不開放調查點，也不虛構備份、驗收或人員確認。原有參考紀錄繼續保留；field-enrollment 及金鑰仍留在 Supabase。'),
 ('03',4):('Vuelva a ingresar en /v3/. Empresa e inicio muestra Acceso directo V3.1. El propietario puede consultar Módulo 013 y Acceso directo; un estado sin verificar no demuestra que falte el módulo. No se pide a la empresa ejecutar SQL o confirmar activación.','重新登入 /v3/，Empresa e inicio 顯示 Acceso directo V3.1。擁有者可查看 013 及直接使用狀態；未驗證不代表模組缺少。不要求公司執行 SQL 或確認啟用。'),
 ('04',0):('Super Admin · propietario: administra Supabase, SQL, versiones, Edge Functions, secretos, respaldos y facturación, y gestiona las otras cuentas administrativas desde la App. No necesita rellenar formularios de activación.','Super Admin · propietario 管理 Supabase、SQL、版本、Edge Functions、金鑰、備份、帳務及 App 其他管理者帳號；不用填寫啟用表單。'),
 ('04',1):('Administrador de empresa: solo usa la Web App para configurar empresa, operativo, candidaturas, lugares, personas, tareas, coordinadores, viewers e informes. Empieza a preparar datos al ingresar; no activa versiones ni recibe credenciales de Supabase. No puede administrar otros Admin ni al propietario.','公司 Admin 僅使用 Web App 設定公司、作業、候選人、地點、人員、任務、主管、Viewer 及報表。登入即可準備，不啟用版本、不取得 Supabase 憑證，也不能管理其他 Admin 或擁有者。'),
 ('16',2):('Estado técnico es una lectura reservada al propietario. No hay formulario Activar V3 ni tres declaraciones obligatorias para usar la App. Conserve la documentación operativa que corresponda; no se interpreta el acceso directo como una certificación de respaldo, móviles o muestreo.','Estado técnico 是擁有者的唯讀檢查；不再有 Activar V3 表單或使用 App 前必填的三項聲明。實際作業所需文件仍應保存，直接使用不等於備份、手機或抽樣已認證。'),
 ('26',3):('Este manual describe Pulso 3.1.2 con acceso directo y módulos 012–014. Los ensayos automáticos solo acreditan los escenarios y entornos ensayados. El sistema no sustituye la autorización de trabajo, el muestreo ni la responsabilidad de difusión.','本手冊適用 Pulso 3.1.2 直接使用版及 012–014 模組。自動測試只證明實測情境與環境；系統不替代作業授權、抽樣及發布責任。')}
 for (sid,i),(es,zh) in changes.items():sections[sid]['blocks'][i]={'es':es,'zh':zh}
 assert len(data)==26 and sum(len(s['blocks']) for s in data)==131
 return data
